### ISSUE TITLE
warp-go 脚本 失败

### ISSUE THREAD

**Issue by Memory2014** [fscarmen/warp-sh#10]
进度 1/3: 安装系统依赖…… 

 注册 WARP free 账户中, 最大尝试5次…… 
 第1次尝试 
 第2次尝试 
 第3次尝试 
 第4次尝试 
 第5次尝试 
 注册 WARP free 账户失败，脚本中止，

 进度 3/3: 已找到最佳 MTU 和 Endpoint 

 API 获取不到注册信息，脚本退出，

**Comment by yukaidi1220** [comment]
我也遇到了
