### ISSUE TITLE
无法获得IP 服务器系统重装也不行，日本的VPS

### ISSUE THREAD

**Issue by kiik1254785214** [fscarmen/warp-sh#100]
Job for wg-quick@warp.service failed because the control process exited with error code.
See "systemctl status wg-quick@warp.service" and "journalctl -xeu wg-quick@warp.service" for details.
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
 第2次尝试 
 第3次尝试 
 第4次尝试 
 第5次尝试 
 ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
 当前操作系统: Debian GNU/Linux 12 (bookworm)

 内核:4.14.129-bbrplus 

 菜单选项: 2.  WARP IPv6 转为 WARP 双栈 (warp d) 

 Warning: `/etc/wireguard/warp.conf' is world accessible
[#] ip link add warp type wireguard
RTNETLINK answers: Operation not supported
[!] Missing WireGuard kernel module. Falling back to slow userspace implementation.
[#] wireguard-go warp
┌──────────────────────────────────────────────────────┐
│                                                      │
│   Running wireguard-go is not required because this  │
│   kernel has first class support for WireGuard. For  │
│   information on installing the kernel module,       │
│   please visit:                                      │
│         https://www.wireguard.com/install/           │
│                                                      │
└──────────────────────────────────────────────────────┘
[#] wg setconf warp /dev/fd/63
[#] ip -4 address add 172.16.0.2/32 dev warp
[#] ip -6 address add 2606:4700:110:837b:abba:b9d1:4aa3:8f49/128 dev warp
[#] ip link set mtu 1420 up dev warp
[#] resolvconf -a tun.warp -m 0 -x
[#] wg set warp fwmark 51820
[#] ip -6 route add ::/0 dev warp table 51820
[#] ip -6 rule add not fwmark 51820 table 51820
[#] ip -6 rule add table main suppress_prefixlength 0
[#] nft -f /dev/fd/63
/dev/fd/63:5:1-130: Error: Could not process rule: No such file or directory

/dev/fd/63:6:1-117: Error: Could not process rule: No such file or directory

[#] resolvconf -d tun.warp -f
[#] ip -6 rule delete table 51820
[#] ip -6 rule delete table main suppress_prefixlength 0
[#] ip link delete dev warp
 ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑ 
 失败已超过5次，脚本中止，附上以上错误提示，问题反馈:[https://github.com/fscarmen/warp-sh/issues] 
root@ribenB:~# warp

 所有依赖已存在，不需要额外安装 

 检查环境中…… 
======================================================================================================================

 脚本版本:3.1.1
 功能新增:1. 支持使用自建 warp api: https://www.warpapi.us.kg/?run=pluskey， 生成 1920 PB WARP+ license 升级为 Plus 账户; 2. Client 对 WARP+ 支持不够，只能使用 IPv4，不能使用 IPv6; 3. 优化安装程序，缩短脚本运行时间
 系统信息:
         当前操作系统:Debian GNU/Linux 12 (bookworm)
         内核:4.14.129-bbrplus
         处理器架构:amd64
         虚拟化:microsoft 
         IPv4: 64.176.47.101 日本  The Constant Company 
         IPv6:     
         WARP 网络接口未开启 
         Client 未安装 
         WireProxy 未安装 

======================================================================================================================

 1.  WARP 双栈 转为 WARP IPv4 (warp 4) 
 2.  WARP 双栈 转为 WARP IPv6 (warp 6) 
 3.  变更 WARP 账户 (warp a) 
 4.  打开 WARP (warp o) 
 5.  安装 CloudFlare Client 并设置为 Proxy 模式 (bash menu.sh c) 
 6.  更换支持 Netflix 的 IP (warp i) 
 7.  永久关闭 WARP 网络接口，并删除 WARP、 Linux Client 和 WireProxy (warp u) 
 8.  刷 WARP+ 流量 (warp p) 
 9.  升级内核、安装BBR、DD脚本 (warp b) 
 10. 同步最新版本 (warp v) 
 11. WARP 解锁 Netflix 等流媒体专业一键(支持多平台、多方式和 TG 通知) 
 12. 安装 iptable + dnsmasq + ipset，让 WARP IPv4 only 接管流媒体流量 (不适用于 IPv6 only VPS) (bash menu.sh e) 
 13. 安装 wireproxy，让 WARP 在本地创建一个 socks5 代理 (bash menu.sh w) 
 14. 安装 CloudFlare Client 并设置为 WARP 模式 (bash menu.sh l) 
 0.  退出脚本 

 请选择: 1
Job for wg-quick@warp.service failed because the control process exited with error code.
See "systemctl status wg-quick@warp.service" and "journalctl -xeu wg-quick@warp.service" for details.
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
 第2次尝试 
 第3次尝试 
 第4次尝试 
 第5次尝试 
 ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
 当前操作系统: Debian GNU/Linux 12 (bookworm)

 内核:4.14.129-bbrplus 

 菜单选项: 1.  WARP 双栈 转为 WARP IPv4 (warp 4) 

 Warning: `/etc/wireguard/warp.conf' is world accessible
[#] ip link add warp type wireguard
RTNETLINK answers: Operation not supported
[!] Missing WireGuard kernel module. Falling back to slow userspace implementation.
[#] wireguard-go warp
┌──────────────────────────────────────────────────────┐
│                                                      │
│   Running wireguard-go is not required because this  │
│   kernel has first class support for WireGuard. For  │
│   information on installing the kernel module,       │
│   please visit:                                      │
│         https://www.wireguard.com/install/           │
│                                                      │
└──────────────────────────────────────────────────────┘
[#] wg setconf warp /dev/fd/63
[#] ip -4 address add 172.16.0.2/32 dev warp
[#] ip -6 address add 2606:4700:110:837b:abba:b9d1:4aa3:8f49/128 dev warp
[#] ip link set mtu 1420 up dev warp
[#] resolvconf -a tun.warp -m 0 -x
[#] wg set warp fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev warp table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
[#] nft -f /dev/fd/63
/dev/fd/63:5:1-100: Error: Could not process rule: No such file or directory

[#] resolvconf -d tun.warp -f
[#] ip -4 rule delete table 51820
[#] ip -4 rule delete table main suppress_prefixlength 0
[#] ip link delete dev warp
 ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑ 
 失败已超过5次，脚本中止，附上以上错误提示，问题反馈:[https://github.com/fscarmen/warp-sh/issues] 
root@ribenB:~# warp o
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
 第2次尝试 
 第3次尝试 
 第4次尝试 
 第5次尝试 
 ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
 当前操作系统: Debian GNU/Linux 12 (bookworm)

 内核:4.14.129-bbrplus 

 菜单选项:  

 Warning: `/etc/wireguard/warp.conf' is world accessible
[#] ip link add warp type wireguard
RTNETLINK answers: Operation not supported
[!] Missing WireGuard kernel module. Falling back to slow userspace implementation.
[#] wireguard-go warp
┌──────────────────────────────────────────────────────┐
│                                                      │
│   Running wireguard-go is not required because this  │
│   kernel has first class support for WireGuard. For  │
│   information on installing the kernel module,       │
│   please visit:                                      │
│         https://www.wireguard.com/install/           │
│                                                      │
└──────────────────────────────────────────────────────┘
[#] wg setconf warp /dev/fd/63
[#] ip -4 address add 172.16.0.2/32 dev warp
[#] ip -6 address add 2606:4700:110:837b:abba:b9d1:4aa3:8f49/128 dev warp
[#] ip link set mtu 1420 up dev warp
[#] resolvconf -a tun.warp -m 0 -x
[#] wg set warp fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev warp table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
[#] nft -f /dev/fd/63
/dev/fd/63:5:1-100: Error: Could not process rule: No such file or directory

[#] resolvconf -d tun.warp -f
[#] ip -4 rule delete table 51820
[#] ip -4 rule delete table main suppress_prefixlength 0
[#] ip link delete dev warp
 ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑ 
 失败已超过5次，脚本中止，附上以上错误提示，问题反馈:[https://github.com/fscarmen/warp-sh/issues] 
root@ribenB:~# warp

 所有依赖已存在，不需要额外安装 

 检查环境中…… 
======================================================================================================================

 脚本版本:3.1.1
 功能新增:1. 支持使用自建 warp api: https://www.warpapi.us.kg/?run=pluskey， 生成 1920 PB WARP+ license 升级为 Plus 账户; 2. Client 对 WARP+ 支持不够，只能使用 IPv4，不能使用 IPv6; 3. 优化安装程序，缩短脚本运行时间
 系统信息:
         当前操作系统:Debian GNU/Linux 12 (bookworm)
         内核:4.14.129-bbrplus
         处理器架构:amd64
         虚拟化:microsoft 
         IPv4: 64.176.47.101 日本  The Constant Company 
         IPv6:     
         WARP 网络接口未开启 
         Client 未安装 
         WireProxy 未安装 

======================================================================================================================

 1.  WARP IPv4 转为 WARP IPv6 (warp 6) 
 2.  WARP IPv4 转为 WARP 双栈 (warp d) 
 3.  变更 WARP 账户 (warp a) 
 4.  打开 WARP (warp o) 
 5.  安装 CloudFlare Client 并设置为 Proxy 模式 (bash menu.sh c) 
 6.  更换支持 Netflix 的 IP (warp i) 
 7.  永久关闭 WARP 网络接口，并删除 WARP、 Linux Client 和 WireProxy (warp u) 
 8.  刷 WARP+ 流量 (warp p) 
 9.  升级内核、安装BBR、DD脚本 (warp b) 
 10. 同步最新版本 (warp v) 
 11. WARP 解锁 Netflix 等流媒体专业一键(支持多平台、多方式和 TG 通知) 
 12. 安装 iptable + dnsmasq + ipset，让 WARP IPv4 only 接管流媒体流量 (不适用于 IPv6 only VPS) (bash menu.sh e) 
 13. 安装 wireproxy，让 WARP 在本地创建一个 socks5 代理 (bash menu.sh w) 
 14. 安装 CloudFlare Client 并设置为 WARP 模式 (bash menu.sh l) 
 0.  退出脚本 

 请选择: 2
Job for wg-quick@warp.service failed because the control process exited with error code.
See "systemctl status wg-quick@warp.service" and "journalctl -xeu wg-quick@warp.service" for details.
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
 第2次尝试 
 第3次尝试 
 第4次尝试 
 第5次尝试 
 ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
 当前操作系统: Debian GNU/Linux 12 (bookworm)

 内核:4.14.129-bbrplus 

 菜单选项: 2.  WARP IPv4 转为 WARP 双栈 (warp d) 

 Warning: `/etc/wireguard/warp.conf' is world accessible
[#] ip link add warp type wireguard
RTNETLINK answers: Operation not supported
[!] Missing WireGuard kernel module. Falling back to slow userspace implementation.
[#] wireguard-go warp
┌──────────────────────────────────────────────────────┐
│                                                      │
│   Running wireguard-go is not required because this  │
│   kernel has first class support for WireGuard. For  │
│   information on installing the kernel module,       │
│   please visit:                                      │
│         https://www.wireguard.com/install/           │
│                                                      │
└──────────────────────────────────────────────────────┘
[#] wg setconf warp /dev/fd/63
[#] ip -4 address add 172.16.0.2/32 dev warp
[#] ip -6 address add 2606:4700:110:837b:abba:b9d1:4aa3:8f49/128 dev warp
[#] ip link set mtu 1420 up dev warp
[#] resolvconf -a tun.warp -m 0 -x
[#] wg set warp fwmark 51820
[#] ip -6 route add ::/0 dev warp table 51820
[#] ip -6 rule add not fwmark 51820 table 51820
[#] ip -6 rule add table main suppress_prefixlength 0
[#] nft -f /dev/fd/63
/dev/fd/63:5:1-130: Error: Could not process rule: No such file or directory

/dev/fd/63:6:1-116: Error: Could not process rule: No such file or directory

[#] resolvconf -d tun.warp -f
[#] ip -6 rule delete table 51820
[#] ip -6 rule delete table main suppress_prefixlength 0
[#] ip link delete dev warp
 ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑ 
 失败已超过5次，脚本中止，附上以上错误提示，问题反馈:[https://github.com/fscarmen/warp-sh/issues] 
root@ribenB:~#

**Comment by fscarmen** [comment]
https://github.com/fscarmen/warp-sh/issues/63

**Comment by kiik1254785214** [comment]
感谢大佬，已经解决问题了。是我使用的BBR内核版本太老了，更新到最新版本一次获取IP就成功了。膜拜！！！
