### ISSUE TITLE
找不到配置文件 warp.conf，脚本中止，问题反馈:[https://github.com/fscarmen/warp-sh/issues] 

### ISSUE THREAD

**Issue by siqi7** [fscarmen/warp-sh#101]
找不到配置文件 warp.conf，脚本中止，问题反馈:[https://github.com/fscarmen/warp-sh/issues]

**Comment by fscarmen** [comment]
卸载再运行多次看看呢

**Comment by luoliven** [comment]
我的也是一样，出现了一毛一样的问题

**Comment by fscarmen** [comment]
重装多次依然不行吗？网络环境是如何的？ipv6还是4？如依然不行，方便的话发个ssh我看看，fscarmen@gmail.com

**Comment by engama** [comment]
我的一台机子安装完成后，就是不能是warp命令进入后端，但是神奇的是我的机子解锁chatgpt了，所以就不关心是什么问题了。今天想更新warp看看新出的MASQUE协议有什么可以用的，结果使用warp进入不了，于是尝试使用安装链接进入，结果也提示了“没有找到适合的方案用于修改 warp 配置文件 warp.conf，脚本中止。当你看到此信息，请把该 bug 反馈至:[https://github.com/fscarmen/warp-sh/issues] ”
![屏幕截图 2024-09-28 164151](https://github.com/user-attachments/assets/2fb116d0-4bb2-4335-9ea1-38b59ccd79d9)

**Comment by fscarmen** [comment]
> 我的一台机子安装完成后，就是不能是warp命令进入后端，但是神奇的是我的机子解锁chatgpt了，所以就不关心是什么问题了。今天想更新warp看看新出的MASQUE协议有什么可以用的，结果使用warp进入不了，于是尝试使用安装链接进入，结果也提示了“没有找到适合的方案用于修改 warp 配置文件 warp.conf，脚本中止。当你看到此信息，请把该 bug 反馈至:[https://github.com/fscarmen/warp-sh/issues] ” ![屏幕截图 2024-09-28 164151](https://private-user-images.githubusercontent.com/62509677/371743475-2fb116d0-4bb2-4335-9ea1-38b59ccd79d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MjAyNDksIm5iZiI6MTcyNzUxOTk0OSwicGF0aCI6Ii82MjUwOTY3Ny8zNzE3NDM0NzUtMmZiMTE2ZDAtNGJiMi00MzM1LTllYTEtMzhiNTljY2Q3OWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDEwMzkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlZGRhODk2ZDg1YmJlMDZhNGM1ZmIwMjllNWNlNzM3ZTBhYzllNTczNDljYTRhYWM5NDgyZDc4MWUwNjc3MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.y6juZvIOQhoqP2Bn3kd93RB2kVtvtxXp0Md8p4sq3XY)

你试试运行 `curl -m5 -sL "https://www.warpapi.us.kg/?run=register"` 看是否正确连接api，获取注册信息？
