### ISSUE TITLE
no 4 permission denied any solution?

### ISSUE THREAD

**Issue by tauf91** [fscarmen/warp-sh#102]
Choose: 4
 Maximum 5 attempts to get WARP IP...
 Try 1
 Try 2
 Try 3
 Try 4
 Try 5
 ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
 Operating System: Debian GNU/Linux 11 (bullseye)
 Kernel:5.10.0-32-amd64
 Menu choose: 4.  Turn on WARP (warp o)
 Warning: `/etc/wireguard/warp.conf' is world accessible
[#] ip link add warp type wireguard
[#] wg setconf warp /dev/fd/63
[#] ip -4 address add 172.16.0.2/32 dev warp
[#] ip -6 address add 2606:4700:110:8311:bdef:ac81:ea40:5605/128 dev warp
RTNETLINK answers: Permission denied
[#] ip link delete dev warp

**Comment by fscarmen** [comment]
Does it ok now？

**Comment by tauf91** [comment]
still not.. except uninstall n reinstall again..and will be a same problem
again..

**Comment by fscarmen** [comment]
Try to reset your OS.
