### ISSUE TITLE
pluskey api 生成不了了吗..

### ISSUE THREAD

**Issue by lionkingc** [fscarmen/warp-sh#103]
请选择: 2
 请输入WARP+ License，回车则使用 plusKey api 生成 的 key:
 正在生成 Plus License....
 License 应为26位字符，请重新输入 WARP+ License，回车则使用 plusKey api 生成 的 key (剩余4次):
 正在生成 Plus License....
 License 应为26位字符，请重新输入 WARP+ License，回车则使用 plusKey api 生成 的 key (剩余3次):

**Comment by fscarmen** [comment]
观察了一个月，克隆 key 的方式仍然无效，故刚才升级了一下脚本，把该功能去掉了。
