### ISSUE TITLE
can't change the country

### ISSUE THREAD

**Issue by ILYAGVC** [fscarmen/warp-sh#105]
I get this error when I change the country (warp i):

Failed. IPv4: 104.28.197.7 Germany Cloudflare, Inc.. Retry after 3 seconds. Brush ip runing time:0 days 0 hours 0 minutes 21 seconds

**Comment by fscarmen** [comment]
Yes, warp doesn't change the region, the script lets confirm the region, it's just used in cases where something goes wrong with the ip api and results in a region error.
