### ISSUE TITLE
加上OpenCloudOS支持

### ISSUE THREAD

**Issue by maoxianfly** [fscarmen/warp-sh#11]
执行脚本报错：本脚本只支持 Debian、Ubuntu、CentOS、Fedora、Arch 或 Alpine 系统,问题反馈:[https://github.com/fscarmen/warp-sh/issues]

当前系统：
cat /etc/os-release

NAME="OpenCloudOS"
VERSION="8.8"
ID="opencloudos"
ID_LIKE="rhel fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:oc8"
PRETTY_NAME="OpenCloudOS 8.8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:opencloudos:opencloudos:8"
HOME_URL="https://www.opencloudos.org/"
BUG_REPORT_URL="https://bugs.opencloudos.tech/"

**Comment by fscarmen** [comment]
好

maoxianfly ***@***.***>于2023年12月2日 周六20:50写道：

**Comment by fscarmen** [comment]
> REGEX=("debian" "ubuntu" "centos|red hat|kernel|oracle linux|alma|rocky|opencloudos" "amazon linux" "alpine" "arch linux" "fedora") RELEASE=("Debian" "Ubuntu" "CentOS" "CentOS" "Alpine" "Arch" "Fedora", "OpenCloudOS")
> 
> 即可

这里好像写得有点问题，请问该系统是视作 CentOS 来处理吗？
