### ISSUE TITLE
腾讯云HK升级Ubuntu 24.04后获取IP错误

### ISSUE THREAD

**Issue by Michaol** [fscarmen/warp-sh#111]
Warning: `/etc/wireguard/warp.conf' is world accessible
[#] ip link add warp type wireguard
[#] wg setconf warp /dev/fd/63
[#] ip -4 address add 172.16.0.2/32 dev warp
[#] ip -6 address add 2606:4700:110:8792:6ce5:eb0c:8ea2:c606/128 dev warp
[#] ip link set mtu 1420 up dev warp
[#] resolvconf -a tun.warp -m 0 -x
Failed to resolve interface "tun.warp": No such device
[#] ip link delete dev warp
 ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑ 

无法建立interface？但是同样24.04，AWS Lightsail新加坡就正常获取。麻花云的问题？

**Comment by fscarmen** [comment]
看看后台有没有允许tun的开关，不行换个系统看看。

**Comment by Michaol** [comment]
确实是腾讯云升级的问题，这个诡异的系统。重新直接安装24.04就完全没问题了，内核只能用默认的6.8.0，如果用脚本升级到6.10.10瞬间死网络，幸好VNC还能救命。
