### ISSUE TITLE
 失败已超过5次，脚本中止

### ISSUE THREAD

**Issue by shiny6667** [fscarmen/warp-sh#112]
root@mlin5966:~# wget -N https://gitlab.com/fscarmen/warp/-/raw/main/menu.sh&& bash menu.sh 4
--2024-10-14 17:59:20--  https://gitlab.com/fscarmen/warp/-/raw/main/menu.sh
Resolving gitlab.com (gitlab.com)... 172.65.251.78, 2606:4700:90:0:f22e:fbec:5bed:a9b9
Connecting to gitlab.com (gitlab.com)|172.65.251.78|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 169529 (166K) [text/plain]
Saving to: ‘menu.sh’

menu.sh             100%[===================>] 165.56K  10.4KB/s    in 40s     

Last-modified header missing -- time-stamps turned off.
2024-10-14 18:00:17 (4.09 KB/s) - ‘menu.sh’ saved [169529/169529]

 
 Language:
 1. English (default) 
 2. 简体中文 

 Choose: 2

 所有依赖已存在，不需要额外安装 

 检查环境中…… 
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
 第2次尝试 
 第3次尝试 
 第4次尝试 
 第5次尝试 
 ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
 当前操作系统: Debian GNU/Linux 12 (bookworm)

 内核:6.1.0-10-amd64 

 菜单选项: 0.  退出脚本 

 Warning: `/etc/wireguard/warp.conf' is world accessible
[#] ip link add warp type wireguard
[#] wg setconf warp /dev/fd/63
[#] ip -4 address add 172.16.0.2/32 dev warp
[#] ip -6 address add 2606:4700:110:8e94:ec3d:8cab:8884:4fc0/128 dev warp
[#] ip link set mtu 1280 up dev warp
[#] resolvconf -a warp -m 0 -x
[#] wg set warp fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev warp table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
[#] nft -f /dev/fd/63
 ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑ 
 失败已超过5次，脚本中止，附上以上错误提示，问题反馈:[https://github.com/fscarmen/warp-sh/issues]

**Comment by fscarmen** [comment]
看不出问题出现在哪里。

**Comment by shiny6667** [comment]
这个机子很奇怪，他的环境不全
