### ISSUE TITLE
Warp IPs

### ISSUE THREAD

**Issue by LiamHams** [fscarmen/warp-sh#115]
Hi. I've been using the latest version 3.1.3 recently. I installed warp client to use MASQUE protocol and it works perfectly.However the issue is that it sometimes gives me the IP of another country instead of my VPS country.For instance on my Germany server from hetzner datacenter I get USA warp ip. I tested with both warp free and warp + and also on Wiregaurd. Is there a solution?
Thanks for the help and great script.

**Comment by fscarmen** [comment]
This is not controllable, we have no control over the IP's assigned by WARP. however, as I understand it, the local IP's of the VPS's are assigned.

**Comment by LiamHams** [comment]
Oh okay thanks. I think maybe this is because of the MASQUE protocol. Because when I use IPv4 wiregaurd native it assigns the right IP to the warp. But when I use warp client with MASQUE this issue occures. Thanks for the help
