### ISSUE TITLE
Failed to get load state of wireproxy.service: Access denied

### ISSUE THREAD

**Issue by zhouli1990** [fscarmen/warp-sh#118]
创建快捷 warp 指令成功 
 后台获取 WARP IP 中,最大尝试3次……
 第1次尝试 
Failed to start wireproxy.service: Access denied
See system logs and 'systemctl status wireproxy.service' for details.
 第2次尝试 
Failed to restart wireproxy.service: Access denied
See system logs and 'systemctl status wireproxy.service' for details.
 第3次尝试 
Failed to restart wireproxy.service: Access denied
See system logs and 'systemctl status wireproxy.service' for details.
Failed to stop wireproxy.service: Access denied
See system logs and 'systemctl status wireproxy.service' for details.
Failed to get load state of wireproxy.service: Access denied
 失败已超过3次，脚本中止，附上以上错误提示，问题反馈:[https://github.com/fscarmen/warp-sh/issues]

**Comment by fscarmen** [comment]
卸载重启一下机器再安装试试。
