### ISSUE TITLE
无法安装Client

### ISSUE THREAD

**Issue by zhouli1990** [fscarmen/warp-sh#119]
脚本版本:3.1.3
 功能新增:Linux Client 增加 MASQUE 协议可选项，Proxy 模式（菜单5）和 WarpProxy 模式（菜单14）都可以使用
 系统信息:
         当前操作系统:CentOS Linux 8
         内核:6.7.9-bbrplus.el8.x86_64
         处理器架构:amd64
         虚拟化:kvm 
         IPv4: 198.2.226.33 美国  PEG TECH INC 
         IPv6:     
         WARP 网络接口未开启 
         Client 未安装 
         WireProxy 已安装，状态为断开连接 

======================================================================================================================

 1.  连接 Client (warp r) 
 2.  连接 Wireproxy (warp y) 
 3.  更改 Client 或 WireProxy 端口 
 4.  打开 WARP (warp o) 
 5.  安装 CloudFlare Client 并设置为 Proxy 模式 (bash menu.sh c) 
 6.  更换支持 Netflix 的 IP (warp i) 
 7.  永久关闭 WARP 网络接口，并删除 WARP、 Linux Client 和 WireProxy (warp u) 
 8.  刷 WARP+ 流量 (warp p) 
 9.  升级内核、安装BBR、DD脚本 (warp b) 
 10. 同步最新版本 (warp v) 
 11. WARP 解锁 Netflix 等流媒体专业一键(支持多平台、多方式和 TG 通知) 
 12. 安装 iptable + dnsmasq + ipset，让 WARP IPv4 only 接管流媒体流量 (不适用于 IPv6 only VPS) (bash menu.sh e) 
 13. (!!! 已安装，请勿选择)安装 wireproxy，让 WARP 在本地创建一个 socks5 代理 (bash menu.sh w) 
 14. 安装 CloudFlare Client 并设置为 WARP 模式 (bash menu.sh l) 
 0.  退出脚本 

 请选择: 5

 官方 Client bug，在隧道协议为 WireGuard 时，如使用 WARP+ license，不能使用 IPv6，详见社区：https://community.cloudflare.com/t/losing-ipv6-connectivity-with-warp/568971 

 请选择 WARP 隧道协议:
 1. MASQUE (默认)
 2. WireGuard 

 请选择: 

 账户请选择:
 1. 使用免费账户 (默认)
 2. WARP+ 

 请选择: 
 请自定义 Client 端口号 (1000-65535，如果不输入，会默认40000): 
 进度 1/3: 安装 Client…… 
[cloudflare-warp-stable]
name=cloudflare-warp-stable
baseurl=https://pkg.cloudflareclient.com/rpm
enabled=1
type=rpm
gpgcheck=1
gpgkey=https://pkg.cloudflareclient.com/pubkey.gpg
CentOS Linux 8 - AppStream                          0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'appstream':
  - Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=AppStream&infra=stock [Could not resolve host: mirrorlist.centos.org]
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=AppStream&infra=stock [Could not resolve host: mirrorlist.centos.org]
CentOS Linux 8 - AppStream                          0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'appstream':
  - Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=AppStream&infra=stock [Could not resolve host: mirrorlist.centos.org]
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=AppStream&infra=stock [Could not resolve host: mirrorlist.centos.org]
Failed to retrieve unit state: Access denied
Failed to start warp-svc.service: Access denied
See system logs and 'systemctl status warp-svc.service' for details.
menu.sh: line 2453: /var/lib/cloudflare-warp/mdm.xml: No such file or directory
 进度 2/3: 设置 Client 模式 
menu.sh: line 2460: warp-cli: command not found
 创建 Socks5 代理失败，问题反馈:[https://github.com/fscarmen/warp-sh/issues]

**Comment by fscarmen** [comment]
https://pkg.cloudflareclient.com/
根据官方的指导，你试试以下是否能安装？

Red Hat Enterprise Linux & CentOS
Install the repository with yum (replace <VERSION> with the release version number):
The supported versions are:
8
### Add cloudflare-warp.repo to /etc/yum.repos.d/
curl -fsSl https://pkg.cloudflareclient.com/cloudflare-warp-ascii.repo | sudo tee /etc/yum.repos.d/cloudflare-warp.repo

### Update repo
sudo yum update

### Install
sudo yum install cloudflare-warp
