### ISSUE TITLE
WARP命令提示的client连接状态问题

### ISSUE THREAD

**Issue by truebit** [fscarmen/warp-sh#12]
输入warp后，提示如下

> 系统信息:
> 	当前操作系统:Debian GNU/Linux 11 (bullseye)
> 	内核:5.10.0-26-cloud-amd64
> 	处理器架构:amd64
> 	虚拟化:kvm 
> 	IPv4: xxxx 香港  Cloudflare, Inc. 
> 	IPv6: xxxx 香港  Cloudflare Warp 
> 	WARP+ 网络接口已开启	设备名: xxx	剩余流量: 24.59 PB
> 	工作模式: 全局 
> 	**Client 已安装， 断开状态**

1. warp提示为Client已连接但端口状态；
2. 但使用`warp r`命令尝试连接，却提示`已断开 Client，再次连接可以用 warp r`；
3. 重新使用`warp r`命令，提示`剩余流量: 24.59 PB`。

用的warp-go reserved模式安装；然后安装了CloudFlare Client，想走CloudFlare Client的WARP模式来着。

**Comment by fscarmen** [comment]
不要重复安装了，卸载全部，再用 `bash menu.sh l` 来安装 client 的 warp 模式吧。

**Comment by truebit** [comment]
按你的办法，warp u 后 bash menu.sh l,出现了和其他人一样的问题。
![Screenshot from 2023-12-05 22-05-19](https://github.com/fscarmen/warp-sh/assets/754906/344dd157-5070-486d-8506-23a14231519a)
然后按照其他issue里面的命令，测试如下：
![Screenshot from 2023-12-05 22-09-27](https://github.com/fscarmen/warp-sh/assets/754906/4a61e9af-920b-4687-aeff-6dbe39300966)

**Comment by truebit** [comment]
之前用的xtom的节点，换用EC2的节点也是这样。请问要如何debug呢？

**Comment by fscarmen** [comment]
用免费账户可以了，warp+没有加速效果的。

**Comment by fscarmen** [comment]
> 试了很多次，问题出在更新为warp+账号这步上。如果不成功就出错

昨晚测了一下，client升级为warp+账户那里是有问题，已是使用了官方的 warp-cli 方式升级的了，`warp-cli --accept-tos set-license XXXX-XX`，看到已经升级成功，在1.1.1.1 app也能看到信息，但就是 IPv6 那里有问题，暂时原因不明，不知道是不是官方bug，因为过往的版本是没有问题的。
暂时等等看官方后续有没有把这个问题处理，用免费账户一样速度的。
