### ISSUE TITLE
UDP 被限制了

### ISSUE THREAD

**Issue by superjlhappy** [fscarmen/warp-sh#124]
Selecting previously unselected package wireguard-tools.
(Reading database ... 65272 files and directories currently installed.)
Preparing to unpack .../wireguard-tools_1.0.20210223-1_amd64.deb ...
Unpacking wireguard-tools (1.0.20210223-1) ...
Setting up wireguard-tools (1.0.20210223-1) ...

 WARP 的所有的 endpoint 均不能连通，有可能 UDP 被限制了，可联系供应商了解如何开启，问题反馈:[https://github.com/fscarmen/warp-sh/issues]

**Comment by fscarmen** [comment]
找供应商
