### ISSUE TITLE
不知道為什麼不行

### ISSUE THREAD

**Issue by wfq1971** [fscarmen/warp-sh#126]
进度 3/3: 寻找 MTU 最优值和优选 endpoint 地址已完成 

 创建快捷 warp 指令成功 
 运行 WARP 
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
 第2次尝试 
 第3次尝试 
 第4次尝试 
 第5次尝试 
 ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
 当前操作系统: Ubuntu 22.04.3 LTS

 内核:6.1.85+ 

 菜单选项: 3.  为 IPv4 only 添加 WARP 双栈网络接口 (bash menu.sh d) 

 Warning: `/etc/wireguard/warp.conf' is world accessible
┌──────────────────────────────────────────────────────┐
│                                                      │
│   Running wireguard-go is not required because this  │
│   kernel has first class support for WireGuard. For  │
│   information on installing the kernel module,       │
│   please visit:                                      │
│         https://www.wireguard.com/install/           │
│                                                      │
└──────────────────────────────────────────────────────┘
ERROR: (warp) 2024/11/27 05:58:12 Failed to create TUN device: operation not permitted
Unable to access interface: Operation not permitted
[#] ip link delete dev warp
Cannot find device "warp"

**Comment by fscarmen** [comment]
ERROR: (warp) 2024/11/27 05:58:12 创建 TUN 设备失败：不允许操作

这个可能是厂家禁止了TUN功能，你找客服问问。
