### ISSUE TITLE
warp-go获取warp ip失败

### ISSUE THREAD

**Issue by TheClown0** [fscarmen/warp-sh#13]
1. 为 IPv4 only 添加 WARP IPv4 全局 网络接口，IPv4 优先 (bash warp-go.sh 4) 
 2. 为 IPv4 only 添加 WARP IPv4 全局 网络接口，IPv6 优先 (bash warp-go.sh 4) 
 3. 为 IPv4 only 添加 WARP IPv6 全局 网络接口，IPv4 优先 (bash warp-go.sh 6) 
 4. 为 IPv4 only 添加 WARP IPv6 全局 网络接口，IPv6 优先 (bash warp-go.sh 6) 
 5. 为 IPv4 only 添加 WARP 双栈 全局 网络接口，IPv4 优先 (bash warp-go.sh d) 
 6. 为 IPv4 only 添加 WARP 双栈 全局 网络接口，IPv6 优先 (bash warp-go.sh d) 
 7. 为 IPv4 only 添加 WARP 双栈 非全局 网络接口，IPv4 优先 (bash warp-go.sh n) 
 8. 为 IPv4 only 添加 WARP 双栈 非全局 网络接口，IPv6 优先 (bash warp-go.sh n) 
 9. 同步最新版本 (warp-go v) 
 0. 退出脚本 

 请选择: 3

 如有 WARP+ 或 Teams 账户请选择
 1. WARP+
 2. Teams
 3. 使用免费账户 (默认) 

 请选择: 

 进度 1/3: 安装系统依赖…… 

 注册 WARP free 账户中, 最大尝试5次…… 
 第1次尝试 

 进度 2/3: 已安装 warp-go 

 进度 3/3: 已找到最佳 MTU 和 Endpoint 

 后台获取 WARP IP 中, 最大尝试5次……
 第1次尝试 
 第2次尝试 
 第3次尝试 
 第4次尝试 
 第5次尝试 
 失败已超过5次，脚本中止，问题反馈:[https://github.com/fscarmen/warp-sh/issues] 

搬瓦工LA的VPS，求助~ 因为warp好像对LA的vps不适用，所以想用warp-go

**Comment by fscarmen** [comment]
> 1. 为 IPv4 only 添加 WARP IPv4 全局 网络接口，IPv4 优先 (bash warp-go.sh 4)
> 2. 为 IPv4 only 添加 WARP IPv4 全局 网络接口，IPv6 优先 (bash warp-go.sh 4)
> 3. 为 IPv4 only 添加 WARP IPv6 全局 网络接口，IPv4 优先 (bash warp-go.sh 6)
> 4. 为 IPv4 only 添加 WARP IPv6 全局 网络接口，IPv6 优先 (bash warp-go.sh 6)
> 5. 为 IPv4 only 添加 WARP 双栈 全局 网络接口，IPv4 优先 (bash warp-go.sh d)
> 6. 为 IPv4 only 添加 WARP 双栈 全局 网络接口，IPv6 优先 (bash warp-go.sh d)
> 7. 为 IPv4 only 添加 WARP 双栈 非全局 网络接口，IPv4 优先 (bash warp-go.sh n)
> 8. 为 IPv4 only 添加 WARP 双栈 非全局 网络接口，IPv6 优先 (bash warp-go.sh n)
> 9. 同步最新版本 (warp-go v)
> 10. 退出脚本
> 
> 请选择: 3
> 
> 如有 WARP+ 或 Teams 账户请选择
> 
> 1. WARP+
> 2. Teams
> 3. 使用免费账户 (默认)
> 
> 请选择:
> 
> 进度 1/3: 安装系统依赖……
> 
> 注册 WARP free 账户中, 最大尝试5次…… 第1次尝试
> 
> 进度 2/3: 已安装 warp-go
> 
> 进度 3/3: 已找到最佳 MTU 和 Endpoint
> 
> 后台获取 WARP IP 中, 最大尝试5次…… 第1次尝试 第2次尝试 第3次尝试 第4次尝试 第5次尝试 失败已超过5次，脚本中止，问题反馈:[https://github.com/fscarmen/warp-sh/issues]
> 
> 搬瓦工LA的VPS，求助~ 因为warp好像对LA的vps不适用，所以想用warp-go

可以的，warp脚本已经加入了 reserved 版的 wireguard-go ，你试试。

**Comment by Naughtymud** [comment]
我也是搬瓦工LA的VPS，也碰到了类似的情况，用最新的脚本更新安装，重试3此，说fail。然后用wg-quick up warp
是能看到 V4和V6的IP，用wo看到的情况和另外一个issue里面的一样。ping 1.1.1.1 不通。我之前是是正常的，大概2个月前突然不正常。

![warp](https://github.com/fscarmen/warp-sh/assets/61130190/81078d05-1933-416f-bda2-de8bbeadb5fe)

**Comment by fscarmen** [comment]
现在dns改为8.8.8.8，用免费账户重装看看。

**Comment by Naughtymud** [comment]
> 现在dns改为8.8.8.8，用免费账户
是需要我自己来修改dns 8.8.8.8 么? 谢谢

**Comment by Naughtymud** [comment]
![warp2](https://github.com/fscarmen/warp-sh/assets/61130190/6fb814ba-4e75-4494-9271-7b8980826128)
8.8.8.8 应该已经在了 ？

**Comment by fscarmen** [comment]
哦，我看错了，你试试 menu.sh 脚本

**Comment by Naughtymud** [comment]
好的，8.8.8.8 貌似已经是在了
![warp2](https://github.com/fscarmen/warp-sh/assets/61130190/783684ec-44f9-40cf-8da4-637bab4da9f0)

**Comment by Naughtymud** [comment]
root@localhost:~# wget -N https://gitlab.com/fscarmen/warp/-/raw/main/menu.sh && bash menu.sh
--2023-12-10 09:21:14--  https://gitlab.com/fscarmen/warp/-/raw/main/menu.sh
Resolving gitlab.com (gitlab.com)... ^C

####################################

好像是DNS有什么问题，kill 掉 wireguard-go warp 就可以运行 menu.sh

**Comment by Naughtymud** [comment]
用menu.sh 卸载再重装，结果一样。

用menu 重装的时候，建议用什么参数 ？

**Comment by fscarmen** [comment]
如果你的机器有v4，就选 warp v6

**Comment by Naughtymud** [comment]
> 如果你的机器有v4，就选 warp v6

没有效果，免费账户可以重新申请的么？怎么申请？

**Comment by Naughtymud** [comment]
有idea不？怎么看warp的路由？

**Comment by yahwehX** [comment]
我也出现一模一样的情况，但我是IPV6地址无法获取，IPV4可以。而且三台机器都这样。

**Comment by FANYT** [comment]
脚本版本:3.03
 功能新增:1. 根据 warp-cli 官方更新部分命令； 2. 去掉 Github cdn
 系统信息:
         当前操作系统:Debian GNU/Linux 12 (bookworm)
         内核:6.1.0-15-amd64
         处理器架构:amd64
         虚拟化:kvm
         IPv4: 110.X.1.X China  China Internet Network Information Center
         IPv6:
         WARP 网络接口未开启
         Client 未安装
         WireProxy 未安装

======================================================================================================================

 1.  WARP IPv4 转为 WARP IPv6 (warp 6)
 2.  WARP IPv4 转为 WARP 双栈 (warp d)
 3.  变更 WARP 账户 (warp a)
 4.  打开 WARP (warp o)
 5.  安装 CloudFlare Client 并设置为 Proxy 模式 (bash menu.sh c)
 6.  更换支持 Netflix 的 IP (warp i)
 7.  永久关闭 WARP 网络接口，并删除 WARP、 Linux Client 和 WireProxy (warp u)
 8.  刷 WARP+ 流量 (warp p)
 9.  升级内核、安装BBR、DD脚本 (warp b)
 10. 同步最新版本 (warp v)
 11. WARP 解锁 Netflix 等流媒体专业一键(支持多平台、多方式和 TG 通知)
 12. 安装 iptable + dnsmasq + ipset，让 WARP IPv4 only 接管流媒体流量 (不适用于 IPv6 only VPS) (bash menu.sh e)
 13. 安装 wireproxy，让 WARP 在本地创建一个 socks5 代理 (bash menu.sh w)
 14. 安装 CloudFlare Client 并设置为 WARP 模式 (bash menu.sh l)
 0.  退出脚本

 请选择: 4
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试
 第2次尝试
 第3次尝试
 第4次尝试
 第5次尝试
 失败已超过5次，脚本中止，问题反馈:[https://github.com/fscarmen/warp-sh/issues]
操作完成
按任意键继续...

腾讯云的VPS

**Comment by fscarmen** [comment]
运行 wg-quick up warp 看看什么情况？
