### ISSUE TITLE
找不到配置文件 warp.conf，脚本中止

### ISSUE THREAD

**Issue by YDWangYPL** [fscarmen/warp-sh#134]
Processing triggers for man-db (2.9.1-1) ...##############################################################################################################################################...........................................] 
Not building database; man-db/auto-update is not 'true'.
sed: can't read /etc/wireguard/warp.conf: No such file or directory
sed: can't read /etc/wireguard/warp.conf: No such file or directory
sed: can't read /etc/wireguard/warp.conf: No such file or directory

 进度 3/3: 寻找 MTU 最优值和优选 endpoint 地址已完成 

 创建快捷 warp 指令成功 
 运行 WARP 
 找不到配置文件 warp.conf，脚本中止，问题反馈:[https://github.com/fscarmen/warp-sh/issues]

**Comment by fscarmen** [comment]
你试试 `curl -m5 -sL "https://www.warpapi.us.kg/?run=register"`
