### ISSUE TITLE
这个现在是不是不能用了？-【结论：2024年12月17日晚的确有问题， Wireguard 方式连接后没有网络。18日恢复正常】

### ISSUE THREAD

**Issue by iQNRen** [fscarmen/warp-sh#135]
我今天试了好几次，发现都不能获取ipv4。会不会跟最近的cloudflared的事情有关？

**Comment by Alirezag23** [comment]
I have these issues too.

**Comment by fscarmen** [comment]
me 2

**Comment by iQNRen** [comment]
> me 2.使用Warp客户端而不是wireguard。
> 
> <img alt="image" width="947" src="https://private-user-images.githubusercontent.com/62703343/396545988-b42f5ee0-a227-4f17-9842-a10b0cd875d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0ODY1OTAsIm5iZiI6MTczNDQ4NjI5MCwicGF0aCI6Ii82MjcwMzM0My8zOTY1NDU5ODgtYjQyZjVlZTAtYTIyNy00ZjE3LTk4NDItYTEwYjBjZDg3NWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDAxNDQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzNGRlY2U1YzE0NWYwMTYwZTVkYWU1MWYxNDVmY2MxNDA2ZjlmNDlmMWFkYTgzMTRmYzA3NmYzNWJhNTRlMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cL4fZ5Adhua4RBLqM8v-kRYAgjt2LBk7LAosXgquaec">

用这个方法好像限制更多点。ipv6的vps还有很多资源也访问不了。

**Comment by fscarmen2** [comment]
已经恢复正常了，估计昨晚抽风，我试了3台机器 IPv4 only, IPv6 only 和 双栈，都可以了。

<img width="617" alt="image" src="https://github.com/user-attachments/assets/b2d9d48f-5cea-4399-b059-efae6e7558b9" />
<img width="752" alt="image" src="https://github.com/user-attachments/assets/c6774893-6113-489d-b69f-289381deeaaf" />
<img width="702" alt="image" src="https://github.com/user-attachments/assets/86dd1763-ffaa-4acc-999f-d886c0e8ed38" />

**Comment by fscarmen** [comment]
已经恢复正常了，估计昨晚抽风，我试了3台机器 IPv4 only, IPv6 only 和 双栈，都可以了。

<img width="617" alt="image" src="https://github.com/user-attachments/assets/b2d9d48f-5cea-4399-b059-efae6e7558b9" />
<img width="752" alt="image" src="https://github.com/user-attachments/assets/c6774893-6113-489d-b69f-289381deeaaf" />
<img width="702" alt="image" src="https://github.com/user-attachments/assets/86dd1763-ffaa-4acc-999f-d886c0e8ed38" />
