### ISSUE TITLE
 找不到配置文件 warp.conf，脚本中止，问题反馈:[https://github.com/fscarmen/warp-sh/issues] 

### ISSUE THREAD

**Issue by damahouzicao** [fscarmen/warp-sh#139]
找不到配置文件 warp.conf，脚本中止，问题反馈:[https://github.com/fscarmen/warp-sh/issues] 

前几天还可以 今天如然不行了 所有的配置都是一样的

**Comment by damahouzicao** [comment]
你试试 curl -m5 -sL "https://www.warpapi.us.kg/?run=register"

这个我返回为空

**Comment by damahouzicao** [comment]
Selecting previously unselected package wireguard-tools.
(Reading database ... 69055 files and directories currently installed.)
Preparing to unpack .../wireguard-tools_1.0.20210914-1+b1_amd64.deb ...
Unpacking wireguard-tools (1.0.20210914-1+b1) ...
Setting up wireguard-tools (1.0.20210914-1+b1) ...
wg-quick.target is a disabled or a static unit, not starting it.
Processing triggers for man-db (2.11.2-2) ...
sed: can't read /etc/wireguard/warp.conf: No such file or directory
sed: can't read /etc/wireguard/warp.conf: No such file or directory
sed: can't read /etc/wireguard/warp.conf: No such file or directory

 进度 3/3: 寻找 MTU 最优值和优选 endpoint 地址已完成 

 创建快捷 warp 指令成功 
 运行 WARP 
 找不到配置文件 warp.conf，脚本中止，问题反馈:[https://github.com/fscarmen/warp-sh/issues]

**Comment by fscarmen** [comment]
这个引起的，只能换域名了，中午左右恢复。




damahouzicao ***@***.***>于2024年12月26日 周四08:48写道：

**Comment by fscarmen** [comment]
这个引起的，只能换域名了，中午左右恢复。

<img width="640" alt="image" src="https://github.com/user-attachments/assets/264677f5-b8be-4597-bf80-c1cd17626f9a" />
<img width="616" alt="image" src="https://github.com/user-attachments/assets/25a41aa6-6a4d-45ca-9bd3-bcacdaf520d2" />

**Comment by fscarmen** [comment]
处理了，后续再更新一下

**Comment by damahouzicao** [comment]
> 处理了，后续再更新一下

已经好了 cool
