### ISSUE TITLE
warp e 没有找到适合的方案用于修改 warp 配置文件 warp.conf

### ISSUE THREAD

**Issue by funv5** [fscarmen/warp-sh#14]
warp e

 所有依赖已存在，不需要额外安装

 检查环境中……

==============================================================

 通过 Iptable + dnsmasq + ipset，最小化实现 chatGPT，Netflix 等媒体解锁，WARP IPv4 只接管流媒体流量，改编自 [Anemone] 的成熟作品，地址[https://github.com/acacia233/Project-WARP-Unlock]，请熟知

==============================================================

 1. 安装脚本
 0. 退出脚本

 请选择: 1

 请选择 wireguard 方式:
 1. wireguard 内核 (默认)
 2. wireguard-go with reserved

 请选择: 1
 没有找到适合的方案用于修改 warp 配置文件 warp.conf，脚本中止。当你看到此信息，请把该 bug 反馈至:[https://github.com/fscarmen/warp-sh/issues]

**Comment by fscarmen** [comment]
你处理一下dns，再试多次看看。
![image](https://github.com/fscarmen/warp-sh/assets/62703343/679e40f7-6bdd-43c7-a444-343538d6c2d6)

**Comment by funv5** [comment]
重新执行脚本可以了，谢谢大佬
