### ISSUE TITLE
warp cf ip选择

### ISSUE THREAD

**Issue by damahouzicao** [fscarmen/warp-sh#140]
老哥 warp d 的ip 是优选的还是随机的？ 会定期自动切换ip吗？

**Comment by fscarmen** [comment]
> warp d 的ip 是优选的还是随机的
warp 随机分配的。只有 endpoint 能优选。

> 会定期自动切换ip吗？
会自动更换IP，但没有固定时间。

**Comment by damahouzicao** [comment]
ok
