### ISSUE TITLE
warp会自动断开，需要经常手动开启

### ISSUE THREAD

**Issue by Mr-aq** [fscarmen/warp-sh#15]
大佬，为啥这个warp会经常自己断开哇，每次需要用的时候都要自己手动再开一遍
![image](https://github.com/fscarmen/warp-sh/assets/80497037/030a78dd-664d-4651-820b-8759c216db54)

**Comment by fscarmen** [comment]
不知道是否网络不稳，在定时任务里每分钟运行一次`warp n`

**Comment by Andy963** [comment]
+1， 经常自己断开了，本来相关每天定时重启一次，发现仍然会自动断开
