### ISSUE TITLE
warp c 命令下，SOCK5创建失败（ubuntu18  vps）

### ISSUE THREAD

**Issue by biao169** [fscarmen/warp-sh#16]
进度 2/2: 设置 Client 模式 
 创建 Socks5 代理失败，问题反馈:[https://github.com/fscarmen/warp-sh/issues] 

请问大佬这个是什么问题，之前一种用着你的方案，这两天突然上不去ChatGPT，然后重装了这个warp就这样子了。

**Comment by fscarmen** [comment]
我忘记是否支持u18.04了，换20.04或22.04看看
