### ISSUE TITLE
更换支持Netflix的IP似乎不能更改地区

### ISSUE THREAD

**Issue by hkwwwxxx** [fscarmen/warp-sh#17]
### 日本oracle cloude上的ARM NAT小鸡，ubuntu20.04，一直不能获取到可以解锁的IPv6地址，于是用warp i换地区成hk，但地区似乎并没有切换，仍然是日本区刷IP。
![Snipaste_2023-12-23_14-54-41](https://github.com/fscarmen/warp-sh/assets/153110911/6308c30f-f30a-4c51-9f58-605c63f78a19)

**Comment by fscarmen** [comment]
是的，不能更换地区的，如果一直刷不了，那也是没有办法的。IPv6 已经好了，比较多的 IP 能换。

**Comment by hkwwwxxx** [comment]
不能换区的话还是建议去掉后面换区的话吧，不然后面还会有人误解。
我用新加坡Oracle的小机，IPv6也是刷了一天，密密麻麻的换了好多个IPv6程序显示都是不能解锁，然后我就停掉刷IP了，停掉刷IP的时候，第4项warp o那个变成了关闭状态，然后我又重新开启，得到新的IPv6，然后直接打开netflix，可以看到新加坡今日排行，可以看绝命毒师和其它非自制刷，字幕可以切换成简体中文。这算是解锁成功的？我又尝试回到刷IP的程序，提示还是不能解锁又是自动不停的刷，反复几次都是这种情况，搞不懂，这算解锁成功的吗？这样到底还要不要开自动刷IPv6了？
![Snipaste_2023-12-24_03-48-06](https://github.com/fscarmen/warp-sh/assets/153110911/bf19436f-686c-460f-989a-ce6c89e77270)
搜索得到“绝命毒师”
![Snipaste_2023-12-24_03-50-55](https://github.com/fscarmen/warp-sh/assets/153110911/c8cc08be-cc5a-4718-a020-cb546819f3df)
字幕可以切换到简体中文
![Snipaste_2023-12-24_03-52-33](https://github.com/fscarmen/warp-sh/assets/153110911/1503070f-5236-44a9-bd38-83ab18796ef9)

**Comment by fscarmen** [comment]
> 不能换区的话还是建议去掉后面换区的话吧，不然后面还会有人误解。

这个原来是没有的，只是判断 IP 归属那里，有时候出错，比如日本的IP被错判断为US,这时就要手动改回JP。

> 搞不懂，这算解锁成功的吗？这样到底还要不要开自动刷IPv6了？
如果能看就不用刷了，可能判断那里现在改了方法，我从来不看奈飞，所以也没有详细测试的了

**Comment by hkwwwxxx** [comment]
好的，有空的时候麻烦更新一下检测方法，不急！
感谢大佬！感谢贡献！恭喜发财，赚钱多多！

**Comment by fscarmen** [comment]
谢谢啊，平安夜快乐，感谢对本项目的支持。
下周我找个时间看看。我是以这个项目为基础来判断是否解锁的，你可以看看这个情况
https://github.com/lmc999/RegionRestrictionCheck
你用这个测一下

**Comment by hkwwwxxx** [comment]
> 谢谢啊，平安夜快乐，感谢对本项目的支持。 下周我找个时间看看。我是以这个项目为基础来判断是否解锁的，你可以看看这个情况 https://github.com/lmc999/RegionRestrictionCheck 你用这个测一下

这个脚本检测不出来，warp非全局分流netflix走warp ipv6的方式，ip a不显示真实的公网IPV6，不知道是不是LXC NAT机的原因，分流是成功的，只是这个检测脚本提示没有IPV6就跳过了。

谢谢大佬，没看到大佬有赞助码，建议弄一个，想表示谢意时没找不到

![Snipaste_2023-12-25_15-38-33](https://github.com/fscarmen/warp-sh/assets/153110911/b1bce06c-7f78-4f66-8925-543a9a36742d)
![Snipaste_2023-12-25_21-13-50](https://github.com/fscarmen/warp-sh/assets/153110911/2eaebb04-7f89-435b-8bb7-d1f9cdb321ab)

**Comment by hkwwwxxx** [comment]
暂时不折腾将就用了，坐等以后你们空了更新脚本投喂，谢谢！

**Comment by fscarmen** [comment]
赞助码没有的，支持本项目就可以了，谢谢！
