### ISSUE TITLE
是否可以添加一个参数，让用户刷新ip的时候自行选择需要的功能。

### ISSUE THREAD

**Issue by sampan79** [fscarmen/warp-sh#18]
刷新ip的功能好像只验证Netflix, 可是我更关心的是disney+ 
是否可以添加一个参数，让用户自行选择呢？

**Comment by fscarmen** [comment]
https://github.com/fscarmen/unlock_warp

这个项目帮到你。

**Comment by sampan79** [comment]
可以用了，感谢
