### ISSUE TITLE
没有加载Tun模块

### ISSUE THREAD

**Issue by learningdog1** [fscarmen/warp-sh#21]
使用一键脚本解锁奈飞：bash <(curl -sSL https://gitlab.com/fscarmen/warp_unlock/-/raw/main/unlock.sh)

日志：
root@vps71533473:~# bash <(curl -sSL https://gitlab.com/fscarmen/warp_unlock/-/raw/main/unlock.sh)

 Language:
 1.English (default) 
 2.简体中文 

 Choose: 2

 WARP 网络接口和 Socks5 都没有安装，请选择安装脚本:
 1. fscarmen's warp (默认)
 2. fscarmen's warp-go
 3. P3terx
 4. Misaka
 5. ygkkk
 0. 退出 

 请选择: 1
--2024-01-05 02:50:46--  https://gitlab.com/fscarmen/warp/-/raw/main/menu.sh
Resolving gitlab.com (gitlab.com)... 2606:4700:90:0:f22e:fbec:5bed:a9b9, 172.65.251.78
Connecting to gitlab.com (gitlab.com)|2606:4700:90:0:f22e:fbec:5bed:a9b9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 161322 (158K) [text/plain]
Saving to: 'menu.sh'

menu.sh                                                           100%[===========================================================================================================================================================>] 157.54K  --.-KB/s    in 0.002s  

Last-modified header missing -- time-stamps turned off.
2024-01-05 02:50:47 (80.6 MB/s) - 'menu.sh' saved [161322/161322]

 
 Language:
 1. English (default) 
 2. 简体中文
 
 Choose: 2

 所有依赖已存在，不需要额外安装 

 检查环境中…… 
 本项目专为 VPS 添加 warp 网络接口，详细说明: [https://github.com/fscarmen/warp-sh]
 脚本特点:
         • 支持 WARP+ 账户，附带第三方刷 WARP+ 流量和升级内核 BBR 脚本
         • 普通用户友好的菜单，进阶者通过后缀选项快速搭建
         • 智能判断操作系统: Ubuntu 、Debian 、CentOS、 Alpine 和 Arch Linux，请务必选择 LTS 系统
         • 支持硬件结构类型: AMD、 ARM 和 s390x
         • 结合 Linux 版本和虚拟化方式，自动优选4个 WireGuard 方案。网络性能方面: 内核集成 WireGuard > 安装内核模块 > wireguard-go
         • 支持 WARP Linux Socks5 Client
         • 输出执行结果，提示是否使用 WARP IP ，IP 归属地和线路提供商
 
======================================================================================================================

 脚本版本:3.01
 功能新增:增加是否允许 udp 的检测，如果 WARP 的所有 endpoint 均不能连通，脚本将中止
 系统信息:
         当前操作系统:Debian GNU/Linux 11 (bullseye)
         内核:4.19.0
         处理器架构:amd64
         虚拟化:openvz 
         IPv4: 205.*** 美国  Hosteons Pte. Ltd 
         IPv6: 2402:*** 美国  Hosteons 
         WARP 网络接口未开启 
         Client 未安装 
         WireProxy 未安装 

======================================================================================================================

 1.  为 原生双栈 添加 WARP IPv4 网络接口 (bash menu.sh 4) 
 2.  为 原生双栈 添加 WARP IPv6 网络接口 (bash menu.sh 6) 
 3.  为 原生双栈 添加 WARP 双栈网络接口 (bash menu.sh d) 
 4.  打开 WARP (warp o) 
 5.  安装 CloudFlare Client 并设置为 Proxy 模式 (bash menu.sh c) 
 6.  更换支持 Netflix 的 IP (warp i) 
 7.  永久关闭 WARP 网络接口，并删除 WARP、 Linux Client 和 WireProxy (warp u) 
 8.  刷 WARP+ 流量 (warp p) 
 9.  升级内核、安装BBR、DD脚本 (warp b) 
 10. 同步最新版本 (warp v) 
 11. WARP 解锁 Netflix 等流媒体专业一键(支持多平台、多方式和 TG 通知) 
 12. 安装 iptable + dnsmasq + ipset，让 WARP IPv4 only 接管流媒体流量 (不适用于 IPv6 only VPS) (bash menu.sh e) 
 13. 安装 wireproxy，让 WARP 在本地创建一个 socks5 代理 (bash menu.sh w) 
 14. 安装 CloudFlare Client 并设置为 WARP 模式 (bash menu.sh l) 
 0.  退出脚本 

 请选择: 2
 没有加载 TUN 模块，请在管理后台开启或联系供应商了解如何开启，问题反馈:[https://github.com/fscarmen/warp-sh/issues] 
root@vps71533473:~# bash <(curl -sSL https://gitlab.com/fscarmen/warp_unlock/-/raw/main/unlock.sh)

 Language:
 1.English (default) 
 2.简体中文 

 Choose: 2

 WARP 网络接口和 Socks5 都没有安装，请选择安装脚本:
 1. fscarmen's warp (默认)
 2. fscarmen's warp-go
 3. P3terx
 4. Misaka
 5. ygkkk
 0. 退出 

 请选择: 1
--2024-01-05 02:50:46--  https://gitlab.com/fscarmen/warp/-/raw/main/menu.sh
Resolving gitlab.com (gitlab.com)... 2606:4700:90:0:f22e:fbec:5bed:a9b9, 172.65.251.78
Connecting to gitlab.com (gitlab.com)|2606:4700:90:0:f22e:fbec:5bed:a9b9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 161322 (158K) [text/plain]
Saving to: 'menu.sh'

menu.sh                                                           100%[===========================================================================================================================================================>] 157.54K  --.-KB/s    in 0.002s  

Last-modified header missing -- time-stamps turned off.
2024-01-05 02:50:47 (80.6 MB/s) - 'menu.sh' saved [161322/161322]

 
 Language:
 1. English (default) 
 2. 简体中文
 
 Choose: 2

 所有依赖已存在，不需要额外安装 

 检查环境中…… 
 本项目专为 VPS 添加 warp 网络接口，详细说明: [https://github.com/fscarmen/warp-sh]
 脚本特点:
         • 支持 WARP+ 账户，附带第三方刷 WARP+ 流量和升级内核 BBR 脚本
         • 普通用户友好的菜单，进阶者通过后缀选项快速搭建
         • 智能判断操作系统: Ubuntu 、Debian 、CentOS、 Alpine 和 Arch Linux，请务必选择 LTS 系统
         • 支持硬件结构类型: AMD、 ARM 和 s390x
         • 结合 Linux 版本和虚拟化方式，自动优选4个 WireGuard 方案。网络性能方面: 内核集成 WireGuard > 安装内核模块 > wireguard-go
         • 支持 WARP Linux Socks5 Client
         • 输出执行结果，提示是否使用 WARP IP ，IP 归属地和线路提供商
 
======================================================================================================================

 脚本版本:3.01
 功能新增:增加是否允许 udp 的检测，如果 WARP 的所有 endpoint 均不能连通，脚本将中止
 系统信息:
         当前操作系统:Debian GNU/Linux 11 (bullseye)
         内核:4.19.0
         处理器架构:amd64
         虚拟化:openvz 
         IPv4: 205.*** 美国  Hosteons Pte. Ltd 
         IPv6: 2402:*** 美国  Hosteons 
         WARP 网络接口未开启 
         Client 未安装 
         WireProxy 未安装 

======================================================================================================================

 1.  为 原生双栈 添加 WARP IPv4 网络接口 (bash menu.sh 4) 
 2.  为 原生双栈 添加 WARP IPv6 网络接口 (bash menu.sh 6) 
 3.  为 原生双栈 添加 WARP 双栈网络接口 (bash menu.sh d) 
 4.  打开 WARP (warp o) 
 5.  安装 CloudFlare Client 并设置为 Proxy 模式 (bash menu.sh c) 
 6.  更换支持 Netflix 的 IP (warp i) 
 7.  永久关闭 WARP 网络接口，并删除 WARP、 Linux Client 和 WireProxy (warp u) 
 8.  刷 WARP+ 流量 (warp p) 
 9.  升级内核、安装BBR、DD脚本 (warp b) 
 10. 同步最新版本 (warp v) 
 11. WARP 解锁 Netflix 等流媒体专业一键(支持多平台、多方式和 TG 通知) 
 12. 安装 iptable + dnsmasq + ipset，让 WARP IPv4 only 接管流媒体流量 (不适用于 IPv6 only VPS) (bash menu.sh e) 
 13. 安装 wireproxy，让 WARP 在本地创建一个 socks5 代理 (bash menu.sh w) 
 14. 安装 CloudFlare Client 并设置为 WARP 模式 (bash menu.sh l) 
 0.  退出脚本 

 请选择: 2
 没有加载 TUN 模块，请在管理后台开启或联系供应商了解如何开启，问题反馈:[https://github.com/fscarmen/warp-sh/issues] 

已经确保在管理面板打开 Tun ：
root@vps71533473:~# lsmod | grep tun
tun                     4242  -2
vznetstat               4242  -2 tun,ip_vznetstat,ip6_vznetstat
<img width="563" alt="864fb878e8bfe05a074e887afa3d1c30" src="https://github.com/fscarmen/warp-sh/assets/110441496/998beb49-f289-4f54-8d49-08c1174f5530">

**Comment by fscarmen** [comment]
强行把TUN那个报错退出去掉试试
```
wget -N https://gitlab.com/fscarmen/warp/-/raw/main/menu.sh; sed -i "s#WIREGUARD_GO_ENABLE=0#WIREGUARD_GO_ENABLE=1#g" menu.sh; bash menu.sh
```

**Comment by learningdog1** [comment]
> 强行把TUN那个报错退出去掉试试
> 
> ```
> wget -N https://gitlab.com/fscarmen/warp/-/raw/main/menu.sh; sed -i "s#WIREGUARD_GO_ENABLE=0#WIREGUARD_GO_ENABLE=1#g" menu.sh; bash menu.sh
> ```

你好，没有起作用，一样的报错方式。

**Comment by learningdog1** [comment]
> 强行把TUN那个报错退出去掉试试
> 
> ```
> wget -N https://gitlab.com/fscarmen/warp/-/raw/main/menu.sh; sed -i "s#WIREGUARD_GO_ENABLE=0#WIREGUARD_GO_ENABLE=1#g" menu.sh; bash menu.sh
> ```

有效，感谢。

**Comment by fscarmen** [comment]
`wg-quick up warp` 看看有没有报错，没有的话，` ip a` 看看 warp 的网络接口，再是有的话，`wg` 看看数据流量

**Comment by learningdog1** [comment]
> `wg-quick up warp` 看看有没有报错，没有的话，`ip a` 看看 warp 的网络接口，再是有的话，`wg` 看看数据流量

wg-quick up warp，输出信息： 
root@vps71533473:~# wg-quick up warp
Warning: `/etc/wireguard/warp.conf' is world accessible
┌──────────────────────────────────────────────────────┐
│                                                      │
│   Running wireguard-go is not required because this  │
│   kernel has first class support for WireGuard. For  │
│   information on installing the kernel module,       │
│   please visit:                                      │
│         https://www.wireguard.com/install/           │
│                                                      │
└──────────────────────────────────────────────────────┘
ERROR: (warp) 2024/01/16 05:23:08 Failed to create TUN device: operation not permitted
Unable to access interface: Protocol not supported
[#] ip link delete dev warp
Cannot find device "warp"

ip a ，输出信息没有显示名为 warp 的 WireGuard 接口。

**Comment by fscarmen** [comment]
这个情况，要去小鸡的后台看如何开 TUN，又或者发个 ticket.
