### ISSUE TITLE
运行脚本会卡在 ‘/usr/bin/wireguard-go’ saved

### ISSUE THREAD

**Issue by diaodiaosvip** [fscarmen/warp-sh#24]
请选择: 1

 只能使用 wireguard-go with reserved 运行

 工作模式:
 1. 全局 (默认)
 2. 非全局

 请选择:

 如有 WARP+ 或 Teams 账户请选择
 1. 使用免费账户 (默认)
 2. WARP+
 3. Teams

 请选择: 1

 请选择优先级别:
 1. IPv4
 2. IPv6
 3. 使用 VPS 初始设置 (默认)

 请选择: 1

 进度 1/3: 安装系统依赖……
Exiting on user cancel.
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.sfo12.us.leaseweb.net
 * centos-sclo-rh: mirrors.raystedman.org
 * centos-sclo-sclo: mirror.keystealth.org
 * centos-virt-xen-epel: mirror.tornadovps.com
 * epel: mirror.tornadovps.com
 * extras: mirrors.vcea.wsu.edu
 * updates: mirrors.sonic.net
https://pkg.cloudflareclient.com/dists/8/main/binary-x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

^CPackage net-tools-2.0-0.25.20131004git.el7.x86_64 already installed and latest version
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.sfo12.us.leaseweb.net
 * centos-sclo-rh: mirrors.raystedman.org
 * centos-sclo-sclo: mirror.keystealth.org
 * centos-virt-xen-epel: mirror.tornadovps.com
 * epel: mirror.tornadovps.com
 * extras: mirrors.vcea.wsu.edu
 * updates: mirrors.sonic.net
https://pkg.cloudflareclient.com/dists/8/main/binary-x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

Package wireguard-tools-1.0.20210914-1.el7.x86_64 already installed and latest version
Nothing to do
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.sfo12.us.leaseweb.net
 * centos-sclo-rh: mirrors.raystedman.org
 * centos-sclo-sclo: mirror.keystealth.org
 * centos-virt-xen-epel: mirror.tornadovps.com
 * epel: mirror.tornadovps.com
 * extras: mirrors.vcea.wsu.edu
 * updates: mirrors.sonic.net
https://pkg.cloudflareclient.com/dists/8/main/binary-x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

No packages marked for update
--2024-01-16 23:56:59--  https://cdn4.cloudflare.now.cc/proxy/https://gitlab.com/fscarmen/warp/-/raw/main/wireguard-go/wireguard-go-linux-amd64-20230223
Resolving cdn4.cloudflare.now.cc (cdn4.cloudflare.now.cc)... 104.21.48.202, 172.67.156.44
Connecting to cdn4.cloudflare.now.cc (cdn4.cloudflare.now.cc)|104.21.48.202|:443... connected.
HTTP request sent, awaiting response... 200 OK
Cookie coming from cdn4.cloudflare.now.cc attempted to set domain to cdn4.cloudflare.now.cc
Length: 2691072 (2.6M) [application/octet-stream]
Saving to: ‘/usr/bin/wireguard-go’

100%[===============================================================================================================================================>] 2,691,072   --.-K/s   in 0.06s

2024-01-16 23:56:59 (42.8 MB/s) - ‘/usr/bin/wireguard-go’ saved [2691072/2691072]

【一直卡在这里，cpu占用也很高，top看是bash进程占用cpu】
【运行bash -x menu.sh 结果如下】

Package wireguard-tools-1.0.20210914-1.el7.x86_64 already installed and latest version
Nothing to do
+ yum -y update
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.sfo12.us.leaseweb.net
 * centos-sclo-rh: mirrors.raystedman.org
 * centos-sclo-sclo: mirror.keystealth.org
 * centos-virt-xen-epel: mirror.tornadovps.com
 * epel: mirror.tornadovps.com
 * extras: mirrors.vcea.wsu.edu
 * updates: mirrors.sonic.net
https://pkg.cloudflareclient.com/dists/8/main/binary-x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

No packages marked for update
+ '[' amd64 = s390x ']'
+ [[ CentOS = CentOS ]]
++ expr 'CentOS Linux 7 (Core)' : '.*\s\([0-9]\{1,\}\)\.*'
+ [[ 7 = 9 ]]
+ '[' '' '!=' 1 ']'
+ '[' 1 = 1 ']'
++ sed 's#.* v1\.0\.\([0-9]\+\) .*#\1#g'
++ wg --version
+ local WIREGUARD_TOOLS_VERSION=20210914
+ [[ 20210914 -lt 20210223 ]]
+ local WIREGUARD_GO_VERSION=20230223
+ wget --no-check-certificate -4 -O /usr/bin/wireguard-go https://cdn2.cloudflare.now.cc/https://gitlab.com/fscarmen/warp/-/raw/main/wireguard-go/wireguard-go-linux-amd64-20230223
--2024-01-16 23:17:46--  https://cdn2.cloudflare.now.cc/https://gitlab.com/fscarmen/warp/-/raw/main/wireguard-go/wireguard-go-linux-amd64-20230223
Resolving cdn2.cloudflare.now.cc (cdn2.cloudflare.now.cc)... 172.67.156.44, 104.21.48.202
Connecting to cdn2.cloudflare.now.cc (cdn2.cloudflare.now.cc)|172.67.156.44|:443... connected.
HTTP request sent, awaiting response... 200 OK
Cookie coming from cdn2.cloudflare.now.cc attempted to set domain to cdn2.cloudflare.now.cc
Length: 2691072 (2.6M) [application/octet-stream]
Saving to: ‘/usr/bin/wireguard-go’

100%[==============================================================================================================================================>] 2,691,072   --.-K/s   in 0.04s

2024-01-16 23:17:46 (65.3 MB/s) - ‘/usr/bin/wireguard-go’ saved [2691072/2691072]

+ chmod +x /usr/bin/wireguard-go
+ '[' 0 = 1 ']'
+ grep -q '^#[[:space:]]*add_if' /usr/bin/wg-quick
+ wait

**Comment by diaodiaosvip** [comment]
@fscarmen 老哥能不能看一下
![00B59BD2](https://github.com/fscarmen/warp-sh/assets/35662637/67fbee67-4fd1-4ad4-925a-272ef7ef957a)

**Comment by fscarmen** [comment]
可以的话，你换个系统看看
