### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by bian2022** [fscarmen/warp-sh#25]
我用的是lxc虚拟化的服务器，母鸡ipv4地址是warp的（ipv6不是），然后我运行脚本就认为我开启warp ipv4了，但实际上我机子没有安装warp

**Comment by fscarmen** [comment]
嗯，现在的判断是存在这样的问题，既然母鸡有了 IPv4 ，那各小鸡共享可以啦，没有必要另外使用用户态的 wireguard-go 了，浪费资源。

**Comment by bian2022** [comment]
> 嗯，现在的判断是存在这样的问题，既然母鸡有了 IPv4 ，那各小鸡共享可以啦，没有必要另外使用用户态的 wireguard-go 了，浪费资源。
> 
> 同时这些情况太特殊了，暂时不作处理了。

主要是他提供的warp IPv4速度太慢了，所以才想再开一个
另外，感谢作者回复，祝大佬新年快乐

**Comment by fscarmen** [comment]
新春快乐呢。
应该会存在这样的问题，所有小鸡都挤在唯一的 warp IPv4 出口的时候就慢了。
