### ISSUE TITLE
Twitch出现网络错误。请重试。（错误 #2000）

### ISSUE THREAD

**Issue by remember5xiaoxi** [fscarmen/warp-sh#28]
您好，ipv6 only安装脚本“1.为ipv6 only 添加ipv4网络接口”这个选项后，看Twitch“出现网络错误。请重试。（错误 #2000）”，不安装则不会出现此问题，请解决这个问题，谢谢

**Comment by fscarmen** [comment]
这属个性化需求，请自行解决。要么用warp非全局，让有需求的分流过去。又或者全局的话，让twitch的域名和ip-cidr分流到原网络接口。

**Comment by fscarmen** [comment]
"geosite:twitch" 分流到原来的网络接口即可

https://github.com/v2ray/domain-list-community/blob/master/data/twitch

**Comment by remember5xiaoxi** [comment]
"geosite:twitch" 分流到原来的网络接口即可

https://github.com/v2ray/domain-list-community/blob/master/data/twitch

在相应模块加入, 以vps原生的网络接口名为 eth0 为例，通过 ip link show 查看

{
          "outbounds":  [
                    {
                              "tag":  "eth0",
                              "protocol":  "freedom",
                              "streamSettings":  {
                                        "sockopt":  {
                                                  "interface":  "eth0",
                                                  "tcpFastOpen":  true
                                        }
                              }
                    }
          ],
          "routing":  {
                    "rules":  [
                              {
                                        "type":  "field",
                                        "domain":  [
                                                  "geosite:twitch"
                                        ],
                                        "outboundTag":  "eth0"
                              }
                    ]
          }
}
填在哪里

**Comment by fscarmen** [comment]
你这个是配置在服务端的，在服务端处做了分流，默认所有流量走 warp ，指定的 twitch 流量走原来的网络接口，这样就行啦。你客户端不用改。

**Comment by remember5xiaoxi** [comment]
您好，我该如何“在相应模块加入, 以vps原生的网络接口名为 eth0 为例”，
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq state UP mode DEFAULT group default qlen 1000
    link/ether 00:16:3e:38:19:9a brd ff:ff:ff:ff:ff:ff
    altname enp0s18
    altname ens18
3: warp: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1400 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/none 
望告知，谢谢

**Comment by fscarmen** [comment]
> "geosite:twitch" 分流到原来的网络接口即可
> 
> https://github.com/v2ray/domain-list-community/blob/master/data/twitch
> 
> 在相应模块加入, 以vps原生的网络接口名为 eth0 为例，通过 `ip link show` 查看
> 
> ```
> {
>     "outbounds": [
>         {
>             "tag": "eth0",
>             "protocol": "freedom",
>             "streamSettings": {
>                 "sockopt": {
>                     "interface": "eth0",
>                     "tcpFastOpen": true
>                 }
>             }
>         }
>     ],
>     "routing": {
>         "rules": [
>             {
>                 "type": "field",
>                 "domain": [
>                     "geosite:twitch"
>                 ],
>                 "outboundTag": "eth0"
>             }
>         ]
>     }
> }
> ```

你不是给你了吗？你在服务端的xray配置文件里看位置加入上面的就行了。
