### ISSUE TITLE
安装时选 Teams 账户，使用 token，输入token后脚本卡住，求老大哥看看

### ISSUE THREAD

**Issue by sw586** [fscarmen/warp-sh#29]
![image](https://github.com/fscarmen/warp-sh/assets/24788222/325020f1-f9ef-43fb-9432-1ebba1eeda00)

![image](https://github.com/fscarmen/warp-sh/assets/24788222/ddf60527-b4b7-48ce-956e-56584ebe72ff)

**Comment by fscarmen** [comment]
这个我要试试，建议用普通免费账户即可，速度一样的。

**Comment by zjwangmin** [comment]
一样的问题，输入token后就卡住。

**Comment by fscarmen** [comment]
这个有时间再试试，可能不会那么快了。

**Comment by fscarmen** [comment]
https://github.com/fscarmen/warp-sh/issues/84#issuecomment-2211555827

我试了没有卡住啊，大家能不能复现一下？

**Comment by fscarmen** [comment]
已经升级 teams 的方法，可以再试试。

**Comment by zjwangmin** [comment]
已经可以了，谢谢！

**Comment by fscarmen** [comment]
> 已经可以了，谢谢！

用最新的脚本了吗？已经不要求输入 token了，改为输入组织名和邮箱，给验证码即可。在脚本里完成，不用到另外的网获取了。
