### ISSUE TITLE
Warp获取IP失败五次

### ISSUE THREAD

**Issue by MS666666** [fscarmen/warp-sh#30]
![image](https://github.com/fscarmen/warp-sh/assets/44149537/882786f0-0151-40c0-b651-6d1f039e2daf)
![image](https://github.com/fscarmen/warp-sh/assets/44149537/d1593455-6bd7-4ac0-8ad3-d6a8f72e2207)
请问这个是啥原因？VPS是hostEONS

**Comment by fscarmen** [comment]
手动运行 `wg-quick up warp` 看看

**Comment by MS666666** [comment]
@fscarmen 
![image](https://github.com/fscarmen/warp-sh/assets/44149537/90e8eecf-0003-45dc-bbe5-32e6bd8e64a8)

**Comment by fscarmen** [comment]
应是少了依赖，你谷歌或gpt问下如何安装，安装了再 `warp o` 试下

**Comment by MS666666** [comment]
> 应是少了依赖，你谷歌或gpt问下如何安装，安装了再 `warp o` 试下

![image](https://github.com/fscarmen/warp-sh/assets/44149537/91346a9c-4a35-4c1b-a657-5f21a3f476c1)
成功了谢谢！我这里是少安装了一个叫resolvconf 工具，用于管理 DNS 解析器配置的

**Comment by fscarmen** [comment]
你如何安装的？我懒得查了，我把该依赖的检测加上。不过说真的，还第一次看到机器没有这个的。

**Comment by MS666666** [comment]
> 你如何安装的？我懒得查了，我把该依赖的检测加上。不过说真的，还第一次看到机器没有这个的，怀疑是你卸载其他的时候把这个错删了？

1、我这先是加了一些apt的软件源，在这个文件下添加/etc/apt/sources.list,（我这里不加的话会报错）
软件源分享网站https://packages.debian.org/sid/all/resolvconf/download
我用的软件源如下：
deb http://ftp.de.debian.org/debian sid main
deb http://ftp.tw.debian.org/debian/ jessie main contrib non-free
deb http://ftp.tw.debian.org/debian/ jessie-updates main contrib non-free
deb http://ftp.tw.debian.org/debian/ jessie-backports main contrib non-free
deb http://security.debian.org/ jessie/updates main contrib non-free
deb http://ftp.yzu.edu.tw/Linux/debian-multimedia/ jessie main non-free
2、在执行**sudo apt update**命令更新一下软件源
3、然后执行安装命令**sudo apt install resolvconf**
4、确认安装是否成功执行命令**resolvconf --version**

**Comment by fscarmen** [comment]
👍🏻
