### ISSUE TITLE
脚本不支持amazonlinux2023啊，这个应该是基于·fedora和红帽的，求支持

### ISSUE THREAD

**Issue by qcwcwc** [fscarmen/warp-sh#32]
脚本不支持amazonlinux2023啊，这个应该是基于·fedora和红帽的，求支持

**Comment by fscarmen** [comment]
好的，这几天处理一下。

**Comment by fscarmen** [comment]
> 脚本不支持amazonlinux2023啊，这个应该是基于·fedora和红帽的，求支持

处理了，下次你试试。

**Comment by qcwcwc** [comment]
多谢大佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月21日(周四) 中午1:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [fscarmen/warp-sh] 脚本不支持amazonlinux2023啊，这个应该是基于·fedora和红帽的，求支持 (Issue #32)




  
脚本不支持amazonlinux2023啊，这个应该是基于·fedora和红帽的，求支持
  
处理了，下次你试试。
