### ISSUE TITLE
报错：没有安装 WireGuard tools 或者找不到配置文件 wgcf.conf，请重新安装。

### ISSUE THREAD

**Issue by loohalh** [fscarmen/warp-sh#34]
RT
当前操作系统：Debian GNU/Linux 10 (buster)
        内核：6.5.11-4-pve
        处理器架构：amd64
        虚拟化：lxc 
        IPv4：     
        IPv6：     
        WARP 网络接口未开启 
        Client 未安装 
        WireProxy 未安装

**Comment by loohalh** [comment]
用pro版本解决了

**Comment by fscarmen** [comment]
可以是网络不行

**Comment by qinghuannn** [comment]
> 按我理解是与账号类型无关的。

应该是和账号无关。我是之前bash menu.sh 13发现加了ipv4，然后就bash menu.sh 7 关闭并卸载所有内容，再bash menu.sh 6就报错：没有安装 WireGuard tools 或者找不到配置文件 wgcf.conf，请重新安装

**Comment by fscarmen** [comment]
13是什么选项？

**Comment by qinghuannn** [comment]
> 13是什么选项？

：安装 wireproxy，让 WARP 在本地创建一个 socks5 代理 (bash menu.sh w)

**Comment by fscarmen** [comment]
这个不会导致获取不了配置，重启再安看看？

**Comment by qinghuannn** [comment]
> 这个不会导致获取不了配置，重启再安看看？

我刚刚用另一个脚本试了下，发现正常安装后，就没管了：bash <(curl -fsSL git.io/warp.sh) menu

**Comment by fscarmen** [comment]
> RT 当前操作系统：Debian GNU/Linux 10 (buster) 内核：6.5.11-4-pve 处理器架构：amd64 虚拟化：lxc IPv4： IPv6： WARP 网络接口未开启 Client 未安装 WireProxy 未安装

已处理，是 www.who.int 的 IPv6 那里有问题，已经用 www.cloudflare.com 替换了。
