### ISSUE TITLE
切换内核的bug

### ISSUE THREAD

**Issue by 5t-RawBeRry** [fscarmen/warp-sh#35]
第一次选内核选的是 wireguard-go with reserved 
之前不太清楚可以通过 warp k 来切换  wireguard-go with reserved  或者wireguard kernel ，所以直接使用 warp u 卸载之后重装。
但是在安装过程中发现无法选择内核 提示 只能使用 wireguard-go with reserved 运行。
只用warp k 切换 也是 提示 只能使用 wireguard-go with reserved 运行。

有两台机器不太方便重装，请问有什么解决方案
（如果是一开始使用 warp k 切换内核之后再卸载则不会出现这种情况）

**Comment by fscarmen** [comment]
你查下你的系统如何检测和打开wireguard内核

**Comment by 5t-RawBeRry** [comment]
> 你查下你的系统如何检测和打开wireguard内核

这个如何查

**Comment by fscarmen** [comment]
谷歌，chatGPT,gemini
比如debian 12如何检测是否有wireguard内核，根据反馈再继续问如何打开

**Comment by 5t-RawBeRry** [comment]
> 谷歌，chatGPT,gemini 比如debian 12如何检测是否有wireguard内核，根据反馈再继续问如何打开

我一直有在使用过wireguard组网的，内核也是自己编译的，确实勾选了wireguard

我以为是您的脚本有啥特殊设置什么的……

**Comment by fscarmen** [comment]
判断那个是这样逻辑的，你逐步排查一下看看。
``` 
 # 判断是否有加载 wireguard 内核，如没有先尝试是否可以加载，再重新判断一次
  if [ ! -e /sys/module/wireguard ]; then
    [ -s /lib/modules/$(uname -r)/kernel/drivers/net/wireguard/wireguard.ko ] && [ $(type -p lsmod) ] && ! lsmod | grep -q wireguard && [ $(type -p modprobe) ] && modprobe wireguard
    [ -e /sys/module/wireguard ] && KERNEL_ENABLE=1 || KERNEL_ENABLE=0
  else
    KERNEL_ENABLE=1
  fi
```

**Comment by 5t-RawBeRry** [comment]
看了这个逻辑感觉应该是 KERNEL_ENABLE=1
因为第一个条件 [! -e /sys/module/wireguard]   
/sys/module/wireguard 这个目录是存在的

**Comment by 5t-RawBeRry** [comment]
问题似乎存在这里 [ -s /lib/modules/$(uname -r)/kernel/drivers/net/wireguard/wireguard.ko ]
改为 [ -s /lib/modules/$(uname -r)/kernel/drivers/net/wireguard/wireguard.ko* ] 问题解决
因为我的WireGuard内核模块文件叫这个 wireguard.ko.xz

**Comment by fscarmen** [comment]
> 内核也是自己编译的

可能是因为这个原因，非常规文件后缀导致，你改一下脚本的判断

**Comment by fscarmen** [comment]
厉害！！
