### ISSUE TITLE
WARP Linux Client 免费账户无法连接，也无法变更 WARP+

### ISSUE THREAD

**Issue by iuiicc** [fscarmen/warp-sh#36]
免费账户不管怎么 warp r 都始终处于断开状态。变更账户不管怎么输入WARP+ License Key都提示非 key

![image](https://github.com/fscarmen/warp-sh/assets/90581328/35e70877-4e48-4597-8c88-e131c522f3d8)

**Comment by fscarmen** [comment]
> 免费账户不管怎么 warp r 都始终处于断开状态
我这里正常

> 变更账户不管怎么输入WARP+ License Key都提示非 key
上个版本优化代码时弄出bug，已修复

```
root@test:~# warp a N8670ljg-sS9jD314-5o*****F

 所有依赖已存在，不需要额外安装 

 检查环境中…… 
 1. WARP 账户
 2. WARP Linux Client 账户 
 请选择: 1
 请自定义 WARP+ 设备名 (默认为 test): aa

 升级 WARP+ 账户中…… 


 已变更为 WARP+ 账户 

 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
 已成功获取 WARP+ 网络, 工作模式: 全局 
 IPv4:35.26.42.122 美国 Google LLC
 IPv6:2a09:bac5:7523:1cd2::2df:a 美国 Cloudflare Warp 
 设备名: aa
 剩余流量: 24.59 PB 
 已变更为 WARP+ 账户 

root@test:~# warp a

 所有依赖已存在，不需要额外安装 

 检查环境中…… 
 1. WARP 账户
 2. WARP Linux Client 账户 
 请选择: 1

 当前账户类型是: WARP +
 
 剩余流量: 24.59 PB
 1. 变更为 free 账户
 2. 变更为另一个 WARP+ 账户
 3. 变更为 Teams 账户 
 0. 退出脚本 

 请选择: 1

 已变更为 WARP Free 账户 

 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
 已成功获取 WARP Free 网络, 工作模式: 全局 
 IPv4:35.26.42.122 美国 Google LLC
 IPv6:2a09:bac5:7524:8c::e:2bd 美国 Cloudflare Warp 
 已变更为 WARP Free 账户 

root@test:~# warp r
 已断开 Client，再次连接可以用 warp r 

root@test:~# warp r
 Client 已连接
 本地 Socks5: 127.0.0.1:40000
 WARP Free IPv4: 104.28.215.219 美国 Cloudflare, Inc.
 WARP Free IPv6:    
root@test:~# 
```

**Comment by iuiicc** [comment]
> > 免费账户不管怎么 warp r 都始终处于断开状态
> 
> 我这里正常
> 
> 
> 
> > 变更账户不管怎么输入WARP+ License Key都提示非 key
> 
> 上个版本优化代码时弄出bug，已修复
> 
> 
> 
> ```
> 
> root@test:~# warp a N8670ljg-sS9jD314-5o*****F
> 
> 
> 
>  所有依赖已存在，不需要额外安装 
> 
> 
> 
>  检查环境中…… 
> 
>  1. WARP 账户
> 
>  2. WARP Linux Client 账户 
> 
>  请选择: 1
> 
>  请自定义 WARP+ 设备名 (默认为 test): aa
> 
> 
> 
>  升级 WARP+ 账户中…… 
> 
> 
> 
> 
> 
>  已变更为 WARP+ 账户 
> 
> 
> 
>  后台获取 WARP IP 中,最大尝试5次……
> 
>  第1次尝试 
> 
>  已成功获取 WARP+ 网络, 工作模式: 全局 
> 
>  IPv4:35.26.42.122 美国 Google LLC
> 
>  IPv6:2a09:bac5:7523:1cd2::2df:a 美国 Cloudflare Warp 
> 
>  设备名: aa
> 
>  剩余流量: 24.59 PB 
> 
>  已变更为 WARP+ 账户 
> 
> 
> 
> root@test:~# warp a
> 
> 
> 
>  所有依赖已存在，不需要额外安装 
> 
> 
> 
>  检查环境中…… 
> 
>  1. WARP 账户
> 
>  2. WARP Linux Client 账户 
> 
>  请选择: 1
> 
> 
> 
>  当前账户类型是: WARP +
> 
>  
> 
>  剩余流量: 24.59 PB
> 
>  1. 变更为 free 账户
> 
>  2. 变更为另一个 WARP+ 账户
> 
>  3. 变更为 Teams 账户 
> 
>  0. 退出脚本 
> 
> 
> 
>  请选择: 1
> 
> 
> 
>  已变更为 WARP Free 账户 
> 
> 
> 
>  后台获取 WARP IP 中,最大尝试5次……
> 
>  第1次尝试 
> 
>  已成功获取 WARP Free 网络, 工作模式: 全局 
> 
>  IPv4:35.26.42.122 美国 Google LLC
> 
>  IPv6:2a09:bac5:7524:8c::e:2bd 美国 Cloudflare Warp 
> 
>  已变更为 WARP Free 账户 
> 
> 
> 
> root@test:~# warp r
> 
>  已断开 Client，再次连接可以用 warp r 
> 
> 
> 
> root@test:~# warp r
> 
>  Client 已连接
> 
>  本地 Socks5: 127.0.0.1:40000
> 
>  WARP Free IPv4: 104.28.215.219 美国 Cloudflare, Inc.
> 
>  WARP Free IPv6:    
> 
> root@test:~# 
> 
> ```

emmmm warp跟warp client 同一个key  warp可以正常连接 client 更换失败，切换到免费账户也没有 ip![image](https://github.com/fscarmen/warp-sh/assets/90581328/b1a82004-9257-4d3d-a5af-4025856a676c)
![image](https://github.com/fscarmen/warp-sh/assets/90581328/750515dd-ba7a-4a9a-bd8a-46949ad61a2e)
![image](https://github.com/fscarmen/warp-sh/assets/90581328/ae5d7597-bdf7-48fb-91c0-5fe55b97cff8)

**Comment by iuiicc** [comment]
Debian 11

**Comment by fscarmen** [comment]
我用了台新的 Debian 11 是正常的， 先安装也普通账户的 warp 和 client ，各自升级成功，再用 warp o / warp r 关闭重启都是成功的。具体什么问题不清楚了，如果你普通账户是正常的就用普通可以了，一样的。

![image](https://github.com/fscarmen/warp-sh/assets/62703343/65045471-2c14-4e95-8d50-c58dde5c9146)
<img width="508" alt="image" src="https://github.com/fscarmen/warp-sh/assets/62703343/ccf1315f-0a26-4ed9-9c5e-5339646637ca">
<img width="476" alt="image" src="https://github.com/fscarmen/warp-sh/assets/62703343/68e58dce-cf1b-4fac-b6e5-8f56c39c83bb">
<img width="503" alt="image" src="https://github.com/fscarmen/warp-sh/assets/62703343/e82d94df-fef9-4e38-95db-5ff7b73fcf74">
<img width="283" alt="image" src="https://github.com/fscarmen/warp-sh/assets/62703343/819da126-72b1-43bd-8ea9-584cd5f68e2d">

**Comment by kentuscn** [comment]
剩余流量，现在都显示0 ，换了很多key都显示 0 ，请问大佬这是什么原因？

**Comment by fscarmen** [comment]
> 剩余流量，现在都显示0 ，换了很多key都显示 0 ，请问大佬这是什么原因？

<img width="734" alt="Image" src="https://github.com/user-attachments/assets/ae504bf4-bf59-4138-949e-cdf7ef13e8af" />
