### ISSUE TITLE
德鸡warp提示No suitable solution was found

### ISSUE THREAD

**Issue by sanshuitmac** [fscarmen/warp-sh#37]
![warp1](https://github.com/fscarmen/warp-sh/assets/142789051/177794d5-3f46-4103-870e-ebcdf014b2d7)
如上图，请问是什么原因呢？ 德鸡是ubantu20的，本地ssh能连上，运行脚本命令就显示上图没办法选择了

**Comment by sanshuitmac** [comment]
是给ipv6的德鸡 warpipv4，用的这个脚本wget -N https://gitlab.com/fscarmen/warp/-/raw/main/menu.sh && bash menu.sh [option] [lisence/url/token]

**Comment by 54meets** [comment]
我也出现了这个问题

**Comment by yshui1988** [comment]
我这边出现同样问题了，不知道咋回事

**Comment by fscarmen** [comment]
判断用到的 https://www.who.int 的 IPv6 出问题了，用这个方式处理，今天我更新一下脚本

```
wget -N https://gitlab.com/fscarmen/warp/-/raw/main/menu.sh
sed -i 's/www.who.int/www.cloudflare.com/' menu.sh
bash menu.sh
```

<img width="880" alt="image" src="https://github.com/fscarmen/warp-sh/assets/62703343/a1abce63-9473-4c8f-a26a-049c7b785603">

**Comment by sanshuitmac** [comment]
> bash menu.sh

不太行，后面出不来v4 和v6的ip。。。麻烦作者加油改下~
![image](https://github.com/fscarmen/warp-sh/assets/142789051/9264d1d5-4b16-4048-aa7e-92429e6ad45a)

**Comment by fscarmen** [comment]
更新了，再试试，先 bash menu.sh u 卸载，再下载新的安装。

**Comment by fscarmen** [comment]
<img width="766" alt="image" src="https://github.com/fscarmen/warp-sh/assets/62703343/9dcc497c-41a5-4692-befb-951a99425873">
