### ISSUE TITLE
考虑支持armbian吗？

### ISSUE THREAD

**Issue by mengniu8** [fscarmen/warp-sh#38]
armbian以后会考虑加入支持吗？

**Comment by fscarmen** [comment]
没有这样的版子，暂时没有计划。

**Comment by mengniu8** [comment]
好的。 如果您以后准备加入armbian的支持了，我可以把我的一个armbian小主机的ssh给您测试用。随时可以联系我。

**Comment by darkrain88** [comment]
怪不得 我的树莓派安装不了(꒦_꒦)
