### ISSUE TITLE
优选endponit ip问题

### ISSUE THREAD

**Issue by PhilCity** [fscarmen/warp-sh#4]
甲骨文韩国首尔，ipv4的endpoint ip绕日本，最近延时很高，ipv6的endpoint ip就在韩国，延时只有2ms。能否手动优选ip？

**Comment by PhilCity** [comment]
[![pipapXd.jpg](https://z1.ax1x.com/2023/10/13/pipapXd.jpg)](https://imgse.com/i/pipapXd)
[![pipakAP.jpg](https://z1.ax1x.com/2023/10/13/pipakAP.jpg)](https://imgse.com/i/pipakAP)

**Comment by fscarmen** [comment]
现在v4和双栈使用 IPv4 的 endpoint ，v6 only 的才使用 IPv6 的endpoint
https://gitlab.com/fscarmen/warp/-/blob/main/menu.sh?ref_type=heads#L1836
把 `[ "$IPV4$IPV6" = 01 ]` 改为 ` [ "IPV6" = 1 ]` 这样在IPv6 only 或者 双栈机器就会用 ipv6 endpoint
