### ISSUE TITLE
无法获取ipv6

### ISSUE THREAD

**Issue by AbianTang** [fscarmen/warp-sh#42]
<img width="597" alt="截屏2024-04-04 下午10 45 06" src="https://github.com/fscarmen/warp-sh/assets/60424384/32685630-898e-4c40-a36f-76e2c8933b55">

**Comment by fscarmen** [comment]
`wg-quick up warp` 看看

**Comment by AbianTang** [comment]
> `wg-quick up warp`看看

]# wg-quick up warp
wg-quick: `warp' already exists

**Comment by fscarmen** [comment]
wg-quick down warp
wg-quck up warp
