### ISSUE TITLE
debian系统使用sid分支无法使用脚本

### ISSUE THREAD

**Issue by laomu61996** [fscarmen/warp-sh#43]
Language:
 1. English (default) 
 2. 简体中文
 
 Choose: 2
 当前操作是 Debian GNU/Linux trixie/sid
 不支持 CentOS 9 及 Debian 9 以下系统,问题反馈:[https://github.com/fscarmen/warp-sh/issues]

**Comment by fscarmen** [comment]
473行
EXCLUDE=("---")

改为

EXCLUDE=("sid")
