### ISSUE TITLE
无法获取ip

### ISSUE THREAD

**Issue by flowiceeos** [fscarmen/warp-sh#44]
失败超过5次。
用wg-quick up warp出现如下错误：

Warning: `/etc/wireguard/warp.conf' is world accessible
[#] ip link add warp type wireguard
[#] wg setconf warp /dev/fd/63
[#] ip -4 address add 172.16.0.2/32 dev warp
[#] ip -6 address add 2606:4700:110:840c:354e:a4ab:38d6:4e93/128 dev warp
[#] ip link set mtu 1420 up dev warp
[#] resolvconf -a warp -m 0 -x
[#] wg set warp fwmark 51820
[#] ip -6 route add ::/0 dev warp table 51820
[#] ip -6 rule add not fwmark 51820 table 51820
[#] ip -6 rule add table main suppress_prefixlength 0
[#] ip6tables-restore -n
modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/5.4.0-172-generic
ip6tables-restore v1.8.4 (legacy): ip6tables-restore: unable to initialize table 'raw'

Error occurred at line: 1
Try `ip6tables-restore -h' or 'ip6tables-restore --help' for more information.
[#] resolvconf -d warp -f
[#] ip -6 rule delete table 51820
[#] ip -6 rule delete table main suppress_prefixlength 0
[#] ip link delete dev warp

**Comment by fscarmen** [comment]
gpt下看看如何处理ip6tables

**Comment by fscarmen** [comment]
Linux 版本过旧 5.4，试试升级一下

**Comment by flowiceeos** [comment]
按ai提示一顿折腾，没成功，这是台小小鸡，估计上位鸡不支持，不折腾了，感谢大佬及时回复。
