### ISSUE TITLE
warp n获取ip失败 美国的vps

### ISSUE THREAD

**Issue by hanselhu** [fscarmen/warp-sh#48]
后台获取 WARP IP 中,最大尝试5次……
 第1次尝试
 第2次尝试
 第3次尝试
 第4次尝试
 第5次尝试
 ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
 当前操作系统: CentOS Linux 7 (Core)

 内核:4.14.129-bbrplus

 (text 40):

 ┌──────────────────────────────────────────────────────┐
│                                                      │
│   Running wireguard-go is not required because this  │
│   kernel has first class support for WireGuard. For  │
│   information on installing the kernel module,       │
│   please visit:                                      │
│         https://www.wireguard.com/install/           │
│                                                      │
└──────────────────────────────────────────────────────┘
[#] wg setconf warp /dev/fd/63
[#] ip -4 address add 172.16.0.2/32 dev warp
[#] ip -6 address add 2606:4700:110:88bd:3fee:4fa6:449d:47fe/128 dev warp
[#] ip link set mtu 1420 up dev warp
[#] mount `8.8.8.8 8.8.4.4 1.1.1.1 2001:4860:4860::8888 2001:4860:4860::8844 2606:4700:4700::1111' /etc/resolv.conf
[#] wg set warp fwmark 51820
[#] ip -6 route add ::/0 dev warp table 51820
[#] ip -6 rule add not fwmark 51820 table 51820
[#] ip -6 rule add table main suppress_prefixlength 0
[#] ip6tables-restore -n
[#] ip -4 rule add from 104.*.*.* lookup main
 ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
 失败已超过5次，脚本中止，附上以上错误提示，问题反馈:[https://github.com/fscarmen/warp-sh/issues]

**Comment by fscarmen** [comment]
升级一下内核

**Comment by hanselhu** [comment]
> 升级一下4.14.129-bbrplus内核

要升级到多少？
[root@bwg ~]# uname -r
4.14.129-bbrplus

**Comment by fscarmen** [comment]
最新的

**Comment by hanselhu** [comment]
> 最新的

最新的就是这个版本吧

**Comment by fscarmen** [comment]
不是的，有5.X或者6.X了，在 menu.sh 里有个选项是更新内核的，如果仍然更新不了，建议换一个内核。

**Comment by fscarmen** [comment]
我没有 agent 脚本，本项目是部署服务端的。 至于为什么工作不了，你应该找该文章的作者。

**Comment by fscarmen** [comment]
用这里进去升级 bbrplus 内核，获取的UJX6N的bbrplus-6.x_stable版本号为:6.7.9-bbrplus
```
wget -N https://gitlab.com/fscarmen/warp/-/raw/main/menu.sh; bash menu.sh b
```

<img width="785" alt="image" src="https://github.com/fscarmen/warp-sh/assets/62703343/d438face-5d40-4087-afb9-e4bdf1d85d7c">
