### ISSUE TITLE
warp-go:  检测不到任何 IPv4 或 IPv6。脚本中止

### ISSUE THREAD

**Issue by nanqic** [fscarmen/warp-sh#50]
运行环境：Ubuntu 22 LTS

复现过程：安装的v4非全局，warp-go o 开关，显示获取了ip，运行warp-go

warp-go -e查看到配置：
``` json
"listen": "127.0.0.1",
"listen_port": 2000,
"udp_timeout": 300,
"type": "socks"
```
但是2000端口没在监听，自然也不能用代理。求大佬看一下问题出在哪里。感谢~
需求：warp-go非全局代理，socks/http均可。warp 脚本经常出现获取不到ip，warp-go获取到了非全局不能用，所以想请大佬解决一下warp-go非全局代理的问题

**Comment by fscarmen** [comment]
warp-go 脚本只能用 interface 来，如果你要 socks5，就用 menu.sh 脚本，菜单 13 wireproxy 方案

<img width="1131" alt="image" src="https://github.com/fscarmen/warp-sh/assets/62703343/506fb904-686b-4440-8475-dc823cb35dcf">

**Comment by nanqic** [comment]
非常感谢❤️

**Comment by nanqic** [comment]
> warp-go 脚本只能用 interface 来，如果你要 socks5，就用 menu.sh 脚本，菜单 13 wireproxy 方案
> 
> <img alt="image" width="1131" src="https://private-user-images.githubusercontent.com/62703343/325161878-506fb904-686b-4440-8475-dc823cb35dcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NjQyOTIsIm5iZiI6MTcxMzk2Mzk5MiwicGF0aCI6Ii82MjcwMzM0My8zMjUxNjE4NzgtNTA2ZmI5MDQtNjg2Yi00NDQwLTg0NzUtZGM4MjNjYjM1ZGNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDEzMDYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNTk4OTVlOWQ3NjA0N2NkZmFmYjhhZTI3MzRhOTE2MjI2NjJlZmY0N2EzZGYzMmNiNTIxNDMyZTk3NWE2NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IQgsdGtIUUArpekSoytklywzoqPF9Gj0TsycbGsWuTw">

请问有办法修改配置，更改socks5代理为http代理吗

**Comment by fscarmen** [comment]
去/etc/wireguard/proxy.conf文件里看，有说明
