### ISSUE TITLE
【bug】warp脚本获取ip卡住，导致服务器宕机

### ISSUE THREAD

**Issue by nanqic** [fscarmen/warp-sh#51]
复现：Ubuntu 22 
root 运行warp脚本，
选13安装，
然后warp n获取ip，服务器宕机，ping不通，只能物理重启，重复3次都是这样。

**Comment by fscarmen** [comment]
wireproxy，不是用 `warp n` ，而是用 `warp y` 来开关

<img width="510" alt="image" src="https://github.com/fscarmen/warp-sh/assets/62703343/c0fff251-dfe5-423d-8c14-4b3c861662c5">

**Comment by nanqic** [comment]
感谢回复，如果不清楚命令输入了warp n，导致服务器宕机，是不是bug呢？希望其他人不要跟我同样输错

**Comment by fscarmen** [comment]
<img width="975" alt="image" src="https://github.com/fscarmen/warp-sh/assets/62703343/00c71982-cda1-41ba-94b5-137ae7c98043">
