### ISSUE TITLE
Endpoint issue

### ISSUE THREAD

**Issue by LawVPN** [fscarmen/warp-sh#52]
Im getting error installing menu.sh after step 3/3, is this because of kernel? Im using 5.4.0 ubuntu 20.04 Indonesian server, ipv6 only
![image](https://github.com/fscarmen/warp-sh/assets/129483274/3f817aa4-fd41-4d0f-9a1d-65e888561b62)

**Comment by fscarmen** [comment]
Maybe your vps provider restricts the use of udp. you run it `echo -ne '\x00\x01\x00\x00\x21\x12\xA4\x42\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' | nc -u -w1 stun.cloudflare.com 3478 | xxd -p` and see if there's a display, if there isn't it means it's restricted.

**Comment by fscarmen** [comment]
It looks like udp is working, don't quite understand why it's failing as above.
