### ISSUE TITLE
你好。脚本作者，我问下关于warp-go 运行脚本的问题

### ISSUE THREAD

**Issue by flight025** [fscarmen/warp-sh#53]
第一次运行脚本套warp的ipv6成功了，成功解锁流媒体。然后自己又选择添加ipv4网络接口。再次安装提示：检测不到任何 IPv4 或 IPv6。脚本中止。这种情况该怎么解决？有什么办法吗
![捕获14](https://github.com/fscarmen/warp-sh/assets/65944944/e5d47cec-dde9-4664-b84b-7ef3bc6e8eef)

**Comment by fscarmen** [comment]
bash -x warp-go.sh
看看

**Comment by flight025** [comment]
![image](https://github.com/fscarmen/warp-sh/assets/65944944/588e4b97-7294-45eb-abee-6f0846de7fa3)
还是这种提示

**Comment by fscarmen** [comment]
检测不到，要不你卸载重装看看，不行就安装 menu.sh 试试

**Comment by fscarmen** [comment]
有个专门解锁 nf 和 ds+ 的项目的，你可以使用那个。
