### ISSUE TITLE
这个怎么讲解

### ISSUE THREAD

**Issue by workmengxue** [fscarmen/warp-sh#54]
root@v1:~# ./menu.sh 4
 
 Language:
 1. English (default) 
 2. 简体中文
 
 Choose: 2 

 所有依赖已存在，不需要额外安装 

 检查环境中…… 

 只能使用 wireguard-go with reserved 运行 

 工作模式:
 1. 全局 (默认)
 2. 非全局 

 请选择: 1

 如有 WARP+ 或 Teams 账户请选择
 1. 使用免费账户 (默认)
 2. WARP+
 3. Teams 

 请选择: 1

 请选择优先级别:
 1. IPv4
 2. IPv6
 3. 使用 VPS 初始设置 (默认) 

 请选择: 1

 进度 1/3: 安装系统依赖…… 

Ign:1 http://archive.debian.org/debian stretch InRelease
Hit:2 http://archive.debian.org/debian stretch Release       
Get:3 http://deb.debian.org/debian unstable InRelease [198 kB]                         
Err:3 http://deb.debian.org/debian unstable InRelease                                  
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
Reading package lists... Done
W: GPG error: http://deb.debian.org/debian unstable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
E: The repository 'http://deb.debian.org/debian unstable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
dnsutils is already the newest version (1:9.10.3.dfsg.P4-12.3+deb9u6).
iptables is already the newest version (1.6.0+snapshot20161117-6).
net-tools is already the newest version (1.60+git20161116.90da8a0-1).
openresolv is already the newest version (3.8.0-1).
0 upgraded, 0 newly installed, 0 to remove and 93 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package wireguard-tools
./menu.sh: line 2120: wg: command not found
--2024-04-29 03:42:40--  https://gitlab.com/fscarmen/warp/-/raw/main/wireguard-go/wireguard-go-linux-amd64-20201118
Resolving gitlab.com (gitlab.com)... 172.65.251.78
Connecting to gitlab.com (gitlab.com)|172.65.251.78|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2523136 (2.4M) [application/octet-stream]
Saving to: ‘/usr/bin/wireguard-go’

/usr/bin/wireguard-go           100%[=======================================================>]   2.41M  10.5MB/s    in 0.2s    

2024-04-29 03:42:41 (10.5 MB/s) - ‘/usr/bin/wireguard-go’ saved [2523136/2523136]

grep: /usr/bin/wg-quick: No such file or directory
sed: can't read /usr/bin/wg-quick: No such file or directory

**Comment by fscarmen** [comment]
你的系统安装不了 wireguard-tools ，你可以手动安装 `apt update; apt -y install wireguard-tools`，看报错什么，根据自己系统的情况，找找gpt处理一下。如果是debian 10的，建议升到11或者12

**Comment by fscarmen** [comment]
如果 Debian 10 的话，已经更新脚本了。
