### ISSUE TITLE
i have some errors its could very helpful if you help me

### ISSUE THREAD

**Issue by Brilliancoder** [fscarmen/warp-sh#56]
Maximum 5 attempts to get WARP IP...
 Try 1 
 Try 2 
 Try 3 
 Try 4 
 Try 5 
 ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
 Operating System: Debian GNU/Linux 11 (bullseye)

 Kernel:4.19.0 

 Menu choose:  

 Warning: `/etc/wireguard/warp.conf' is world accessible
┌──────────────────────────────────────────────────────┐
│                                                      │
│   Running wireguard-go is not required because this  │
│   kernel has first class support for WireGuard. For  │
│   information on installing the kernel module,       │
│   please visit:                                      │
│         https://www.wireguard.com/install/           │
│                                                      │
└──────────────────────────────────────────────────────┘
ERROR: (warp) 2024/05/03 14:19:57 Failed to create TUN device: operation not permitted
Unable to access interface: Protocol not supported
[#] ip link delete dev warp
Cannot find device "warp"
 ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑ 
 There have been more than 5 failures. The script is aborted. Attach the above error message. Feedback: [https://github.com/fscarmen/warp-sh/issues]

**Comment by fscarmen** [comment]
Update your Linux kernel and try again.

**Comment by Brilliancoder** [comment]
is there any other way? im using hax.co.id they use openvz for the vms i cant update their kernel

**Comment by fscarmen** [comment]
open tun at the dashboard

**Comment by Brilliancoder** [comment]
![image](https://github.com/fscarmen/warp-sh/assets/140956295/927c56b7-4d1a-454b-87a5-ef950b244e91)

**Comment by Brilliancoder** [comment]
when im using it for first time its works but after a reboot its error

**Comment by fscarmen** [comment]
I can't find the problem at the moment.

**Comment by Brilliancoder** [comment]
i hope you can find any solution for me since i need it
