### ISSUE TITLE
当前操作是 Alpine Linux edge 不支持，这个能调下不？

### ISSUE THREAD

**Issue by sos801107** [fscarmen/warp-sh#58]
Choose: 2
 当前操作是 Alpine Linux edge
 不支持 CentOS 9 及 Alpine 3 以下系统,问题反馈:[https://github.com/fscarmen/warp-sh/issues]

**Comment by fscarmen** [comment]
已经更新并测试了

<img width="882" alt="image" src="https://github.com/fscarmen/warp-sh/assets/62703343/f35c285d-0dde-4163-bd9c-ef67dd7ec9ba">
<img width="683" alt="image" src="https://github.com/fscarmen/warp-sh/assets/62703343/4ba559a5-3642-43bc-a6a0-001f3d4d6be6">

**Comment by sos801107** [comment]
谢谢~！可以了
