### ISSUE TITLE
在只有ipv6的服务器上无法开启warp

### ISSUE THREAD

**Issue by jinde98** [fscarmen/warp-sh#59]
最近发现在只有ipv6的服务器上无法开启warp了，以前一直运行好好的，不知道是情况。大佬能给分析可能的原因吗？

![image](https://github.com/fscarmen/warp-sh/assets/127750182/3415df8c-3978-4699-876c-9ded19e450ca)

**Comment by fscarmen** [comment]
`warp v` 更新脚本，再运行 `warp o` 看看，
不行就重装试试。

**Comment by jinde98** [comment]
> `warp v` 更新脚本，再运行 `warp o` 看看， 不行就重装试试。

感谢答复，我重装后，还是不行，但有出错提示如下：

![Uploading image.png…]()

**Comment by fscarmen** [comment]
`ERROR: (warp)2024/05/13 06:33:11 Failed to create TUN device:operation not permitted`

是不是要在机器的面板把 tun 功能打开啊，我这里的  hax ipv6 没有问题哦

<img width="456" alt="image" src="https://github.com/fscarmen/warp-sh/assets/62703343/23e08a09-3120-4068-a0fd-9c77c97abd3c">

**Comment by jinde98** [comment]
可能地区不一样，我德国的这里的没有tun这个选项。我看了这个issue
 #56 和这个问题一模一样，也是之前正常运行，重启后就不行了。
 再次，感谢大佬的回复！！！


![image](https://github.com/fscarmen/warp-sh/assets/127750182/7e34ecb9-f068-42bc-b7d3-80e3cb6105af)

**Comment by fscarmen** [comment]
可能厂家在这个地区做了限制，我 us 地区没有问题。

**Comment by fscarmen** [comment]
对了，你可以试试甬哥的脚本，解压后运行  `bash decode-CFwarp.sh`
[warp.zip](https://github.com/fscarmen/warp-sh/files/15289718/warp.zip)

**Comment by jinde98** [comment]
试过了，勇哥的脚本也不行，估计是TUN没开启造成的，VPS可能对这个有限制。

![image](https://github.com/fscarmen/warp-sh/assets/127750182/8b8c222f-cca5-4bb3-86c2-ec97f74a3b0b)
![image](https://github.com/fscarmen/warp-sh/assets/127750182/12200288-da98-47ed-9cd0-3b04201e5bc1)

**Comment by fscarmen** [comment]
`cat /dev/net/tun` 看看反馈什么？

**Comment by jinde98** [comment]
> cat /dev/net/tun

也不行，不支持

![image](https://github.com/fscarmen/warp-sh/assets/127750182/b720726d-abee-4947-bb66-78a6c3eb1f5c)

**Comment by fscarmen** [comment]
看这个状态，应该是可以的哦，我的一台和另一位网友的一台都可以，不过都是us的，或许你换台机器

<img width="673" alt="image" src="https://github.com/fscarmen/warp-sh/assets/62703343/8fcf727c-2d10-4529-9227-5e3c78dd50f9">
