### ISSUE TITLE
无论使用哪个VPS都是获取IP失败

### ISSUE THREAD

**Issue by mogan1999** [fscarmen/warp-sh#6]
1.  为 IPv4 only 添加 WARP IPv4 网络接口 (bash menu.sh 4) 
 2.  为 IPv4 only 添加 WARP IPv6 网络接口 (bash menu.sh 6) 
 3.  为 IPv4 only 添加 WARP 双栈网络接口 (bash menu.sh d) 
 4.  打开 WARP (warp o) 
 5.  安装 CloudFlare Client 并设置为 Proxy 模式 (bash menu.sh c) 
 6.  更换支持 Netflix 的 IP (warp i) 
 7.  永久关闭 WARP 网络接口，并删除 WARP、 Linux Client 和 WireProxy (warp u) 
 8.  刷 WARP+ 流量 (warp p) 
 9.  升级内核、安装BBR、DD脚本 (warp b) 
 10. 同步最新版本 (warp v) 
 11. WARP 解锁 Netflix 等流媒体专业一键(支持多平台、多方式和 TG 通知) 
 12. 安装 iptable + dnsmasq + ipset，让 WARP IPv4 only 接管流媒体流量 (不适用于 IPv6 only VPS) (bash menu.sh e) 
 13. 安装 wireproxy，让 WARP 在本地创建一个 socks5 代理 (bash menu.sh w) 
 14. 安装 CloudFlare Client 并设置为 WARP 模式 (bash menu.sh l) 
 0.  退出脚本 

 请选择: 3

 只能使用 wireguard-go with reserved 运行 

 工作模式:
 1. 全局 (默认)
 2. 非全局 

 请选择: 

 如有 WARP+ 或 Teams 账户请选择
 1. 使用免费账户 (默认)
 2. WARP+
 3. Teams 

 请选择: 

 请选择优先级别:
 1. IPv4
 2. IPv6
 3. 使用 VPS 初始设置 (默认) 

 请选择: 

 进度 1/3: 安装系统依赖…… 

Hit:1 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://azure.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://azure.archive.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists... 35%
 进度 2/3: 已安装 WARP 

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
7 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
net-tools is already the newest version (1.60+git20181103.0eebece-1ubuntu5).
iptables is already the newest version (1.8.7-1ubuntu5.1).
dnsutils is already the newest version (1:9.18.18-0ubuntu0.22.04.1).
The following NEW packages will be installed:
  openresolv
0 upgraded, 1 newly installed, 0 to remove and 7 not upgraded.
Need to get 25.6 kB of archives.
After this operation, 105 kB of additional disk space will be used.
Get:1 http://azure.archive.ubuntu.com/ubuntu jammy/universe amd64 openresolv all 3.12.0-2 [25.6 kB]
Fetched 25.6 kB in 0s (992 kB/s)
Selecting previously unselected package openresolv.
(Reading database ... 61677 files and directories currently installed.)
Preparing to unpack .../openresolv_3.12.0-2_all.deb ...
Unpacking openresolv (3.12.0-2) ...
Setting up openresolv (3.12.0-2) ...
Processing triggers for man-db (2.10.2-1) ...
NEEDRESTART-VER: 3.5
NEEDRESTART-KCUR: 6.2.0-1016-azure
NEEDRESTART-KEXP: 6.2.0-1016-azure
NEEDRESTART-KSTA: 1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  wireguard-tools
0 upgraded, 1 newly installed, 0 to remove and 7 not upgraded.
Need to get 86.9 kB of archives.
After this operation, 328 kB of additional disk space will be used.
Get:1 http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 wireguard-tools amd64 1.0.20210914-1ubuntu2 [86.9 kB]
Fetched 86.9 kB in 0s (3170 kB/s)    
Selecting previously unselected package wireguard-tools.
(Reading database ... 61695 files and directories currently installed.)
Preparing to unpack .../wireguard-tools_1.0.20210914-1ubuntu2_amd64.deb ...
Unpacking wireguard-tools (1.0.20210914-1ubuntu2) ...
Setting up wireguard-tools (1.0.20210914-1ubuntu2) ...
wg-quick.target is a disabled or a static unit not running, not starting it.
Processing triggers for man-db (2.10.2-1) ...
NEEDRESTART-VER: 3.5
NEEDRESTART-KCUR: 6.2.0-1016-azure
NEEDRESTART-KEXP: 6.2.0-1016-azure
NEEDRESTART-KSTA: 1
--2023-11-11 07:30:04--  https://cdn2.cloudflare.now.cc/https://gitlab.com/fscarmen/warp/-/raw/main/wireguard-go/wireguard-go-linux-amd64-20230223
Resolving cdn2.cloudflare.now.cc (cdn2.cloudflare.now.cc)... 104.21.48.202, 172.67.156.44
Connecting to cdn2.cloudflare.now.cc (cdn2.cloudflare.now.cc)|104.21.48.202|:443... connected.
HTTP request sent, awaiting response... 200 OK
Cookie coming from cdn2.cloudflare.now.cc attempted to set domain to gitlab.com
Length: 2691072 (2.6M) [application/octet-stream]
Saving to: ‘/usr/bin/wireguard-go’

/usr/bin/wireguard-go            100%[=========================================================>]   2.57M  6.82MB/s    in 0.4s    

2023-11-11 07:30:05 (6.82 MB/s) - ‘/usr/bin/wireguard-go’ saved [2691072/2691072]

 进度 3/3: 寻找 MTU 最优值和优选 endpoint 地址已完成 

 创建快捷 warp 指令成功 
 运行 WARP 
 后台获取 WARP IP 中,最大尝试3次……
 第1次尝试 
 第2次尝试 
 第3次尝试 
 失败已超过3次，脚本中止，问题反馈:[https://github.com/fscarmen/warp-sh/issues] 
root@ex-uk-vm:~# warp o
 后台获取 WARP IP 中,最大尝试3次……
 第1次尝试 
 第2次尝试 
curl: (28) Resolving timed out after 8000 milliseconds
 第3次尝试 
 失败已超过3次，脚本中止，问题反馈:[https://github.com/fscarmen/warp-sh/issues] 
root@ex-uk-vm:~#

**Comment by mogan1999** [comment]
有一个奇怪的点是，在“后台获取 WARP IP 中,最大尝试3次……”这个过程中如果使用VPS作为代理访问ip.gs是可以查询到已经获取到了IP的，此时若Crtl+C强行终止脚本便可以保留获取到的IP。但是如果放任脚本不管，3次失败后就会关闭WARP，变回原来的IP。

**Comment by fscarmen** [comment]
> 有一个奇怪的点是，在“后台获取 WARP IP 中,最大尝试3次……”这个过程中如果使用VPS作为代理访问ip.gs是可以查询到已经获取到了IP的，此时若Crtl+C强行终止脚本便可以保留获取到的IP。但是如果放任脚本不管，3次失败后就会关闭WARP，变回原来的IP。

你手动试试 `wg-quick up warp`，之后 `curl ip.gs` 看看是否有 warp IP呢

**Comment by mogan1999** [comment]
这是测试结果
 进度 3/3: 寻找 MTU 最优值和优选 endpoint 地址已完成 

 创建快捷 warp 指令成功 
 运行 WARP 
 后台获取 WARP IP 中,最大尝试3次……
 第1次尝试 
curl: (28) Resolving timed out after 8000 milliseconds
curl: (28) Resolving timed out after 8000 milliseconds
 第2次尝试 
 第3次尝试 
 失败已超过3次，脚本中止，问题反馈:[https://github.com/fscarmen/warp-sh/issues] 
root@ld-ams1-vm:~# wg-quick up warp
[#] ip link add warp type wireguard
[#] wg setconf warp /dev/fd/63
[#] ip -4 address add 172.16.0.2/32 dev warp
[#] ip -6 address add 2606:4700:110:8645:606c:761:8675:2f69/128 dev warp
[#] ip link set mtu 1420 up dev warp
[#] resolvconf -a warp -m 0 -x
[#] wg set warp fwmark 51820
[#] ip -6 route add ::/0 dev warp table 51820
[#] ip -6 rule add not fwmark 51820 table 51820
[#] ip -6 rule add table main suppress_prefixlength 0
[#] nft -f /dev/fd/63
[#] ip -4 route add 0.0.0.0/0 dev warp table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
[#] nft -f /dev/fd/63
[#] ip -4 rule add from 10.0.0.4 lookup main
root@ld-ams1-vm:~# curl ip.gs
curl: (6) Could not resolve host: ip.gs

**Comment by fscarmen** [comment]
方便的话，把机器ssh信息发 fscarmen@gmail.com ，我排查一下，听说最近 warp 的 dns 1.1.1.1 出问题。

**Comment by mogan1999** [comment]
确实可能跟DNS有关系，刚刚用了另外一个脚本，它的WARP DNS是8.8.8.8等谷歌系的，很顺畅

**Comment by fscarmen** [comment]
你能做个测试吗？无论用哪个脚本，把 warp 配置文件 里的dns 在 8.8.8.8 和 1.1.1.1 这两个切换，看看是不是dns问题

**Comment by mogan1999** [comment]
使用您的脚本做了两次测试：
1.修改/etc/wireguard的warp.conf中的DNS项为
DNS = 1.1.1.1,2606:4700:4700::1111

脚本运行结果如下：
root@hk-t:~# warp o
 后台获取 WARP IP 中,最大尝试3次……
 第1次尝试 
 第2次尝试 
 第3次尝试 
 失败已超过3次，脚本中止，问题反馈:[https://github.com/fscarmen/warp-sh/issues] 

2.修改/etc/wireguard的warp.conf中的DNS项为
DNS = 8.8.8.8,8.8.4.4,2001:4860:4860::8888,2001:4860:4860::8844
脚本运行结果如下：
root@hk-t:~# warp o
 后台获取 WARP IP 中,最大尝试3次……
 第1次尝试 
 已成功获取 WARP Free 网络, 工作模式: 全局 
 IPv4:104.28.247.70 香港 Cloudflare, Inc.
 IPv6:2a09:bac5:3981:16c8::245:31 香港 Cloudflare Warp

**Comment by mogan1999** [comment]
另外一个脚本更改DNS后也出现curl超时的情况，但是若修改DNS后再选择获取IP的话，脚本会自动修改DNS为8.8.8.8

**Comment by fscarmen** [comment]
我把本脚本改为8.8.8.8，保证正常使用再说

**Comment by mogan1999** [comment]
好的，麻烦您了

**Comment by fscarmen** [comment]
我已经改了，你可以再试试。

**Comment by mogan1999** [comment]
如果是IPV6优先出站的话，IPV6 DNS也需要添加上去吧？这边看到您只保留了IPV4的8.8.8.8

**Comment by fscarmen** [comment]
是的，都换成谷歌的优先了，cf的不知道为什么不是一定不行的，之前我试了几台机器都可以，但像你和另外网友的就遇到问题。

**Comment by fscarmen** [comment]
你试试再安装本脚本，看看是否正常呢。

**Comment by mogan1999** [comment]
目前正常了

**Comment by mogan1999** [comment]
换了一台新加坡的微软云VPS，又出现了curl超时的问题，但是最终成功获取了

 进度 3/3: 寻找 MTU 最优值和优选 endpoint 地址已完成 

 创建快捷 warp 指令成功 
 运行 WARP 
 后台获取 WARP IP 中,最大尝试3次……
 第1次尝试 
curl: (28) Resolving timed out after 8000 milliseconds
curl: (28) Resolving timed out after 8000 milliseconds
 第2次尝试 
curl: (28) Resolving timed out after 8001 milliseconds
curl: (28) Resolving timed out after 8000 milliseconds
 第3次尝试 
curl: (28) Resolving timed out after 8000 milliseconds
curl: (28) Resolving timed out after 8000 milliseconds
 失败已超过3次，脚本中止，问题反馈:[https://github.com/fscarmen/warp-sh/issues] 
root@sg-vm:~# warp o
 后台获取 WARP IP 中,最大尝试3次……
 第1次尝试 
curl: (28) Resolving timed out after 8000 milliseconds
curl: (28) Resolving timed out after 8000 milliseconds
 第2次尝试 
 已成功获取 WARP Free 网络, 工作模式: 全局 
 IPv4:104.28.254.47 新加坡 Cloudflare, Inc.
 IPv6:2a09:bac5:55fa:15f::23:437 新加坡 Cloudflare Warp

**Comment by fscarmen** [comment]
ummm，重试次数脚本原来是5次的，后面改为3次，看看大家使用的情况。

**Comment by iislong** [comment]
我也遇到了同样的问题，teams账号获取ip不行，只能获取免费账号的ip

**Comment by fscarmen** [comment]
> 我也遇到了同样的问题，teams账号获取ip不行，只能获取免费账号的ip

teams账号有没有超过5台设备？

**Comment by iislong** [comment]
> > 我也遇到了同样的问题，teams账号获取ip不行，只能获取免费账号的ip
> 
> teams账号有没有超过5台设备？

没有超。
是通过在线获取teams配置使用

**Comment by iislong** [comment]
> > > > 我也遇到了同样的问题，teams账号获取ip不行，只能获取免费账号的ip
> > > 
> > > 
> > > teams账号有没有超过5台设备？
> > 
> > 
> > 没有超。 是通过在线获取teams配置使用
> 
> 我搞错了，teams账户是没有限制终端数的，你说的在线获取是通过 token 还是在线文件？
> 
> 如果是后者，会不会该账户被注销了？ 你的 teams 配置是不是有问题啊？你可以用我共享的先试试看。

用token没问题了，在线的配置可能过期了，去年用模拟器提取的

**Comment by fscarmen** [comment]
> 用token没问题了，在线的配置可能过期了，去年用模拟器提取的

我也有一样的问题，你看看提取的 ipv6 是不是 2606 开头的，以前旧的不是的，后面改了，你可以使用 api 查出他更改后的 ipv6 地址

**Comment by Jacken22** [comment]
不小心，选择7，“永久关闭 WARP 网络接口，并删除 WARP、 Linux Client 和 WireProxy (warp u)” 网络都连接不了，怎么办啊，有能恢复嘛

**Comment by fscarmen** [comment]
reboot能恢复吗？

**Comment by Michaol** [comment]
我今天也突然出现这个问题，WARP IP被重刷后再也获取不到，全部是超时，加上是全局，导致VPS完全不能用。只能强制卸载WARP。
curl: (28) Resolving timed out after 8000 milliseconds

刚才一直在尝试，终于在第三次尝试时重新获得IP。

**Comment by wrmfw666** [comment]
在warp获取ip时，ctrl+c强制退出后，重启VPS，一切都好了......

**Comment by wweggplant** [comment]
> 在warp获取ip时，ctrl+c强制退出后，重启VPS，一切都好了......

太感谢了, 用你的办法成功了

**Comment by zansbang** [comment]
> 在warp获取ip时，ctrl+c强制退出后，重启VPS，一切都好了......

离谱的方法竟然好了...
谢谢这离谱的方法哈哈

**Comment by yilang0001** [comment]
> > 在warp获取ip时，ctrl+c强制退出后，重启VPS，一切都好了......
> 
> 离谱的方法竟然好了... 谢谢这离谱的方法哈哈

时隔一年，这方法仍然有效。
