### ISSUE TITLE
不支持Amazon Linux 2023?

### ISSUE THREAD

**Issue by Xcvip06** [fscarmen/warp-sh#61]
当前操作是 Amazon Linux 2023
 不支持 CentOS 9 及 CentOS 7 以下系统,问题反馈:[https://github.com/fscarmen/warp-sh/issues]

**Comment by fscarmen** [comment]
https://gitlab.com/fscarmen/warp/-/blob/main/menu.sh?ref_type=heads#L479
EXCLUDE=("---")
改为 EXCLUDE=("Amazon") 试试

**Comment by fscarmen** [comment]
方便的话，把ssh发过来看看 fscarmen@gmail.com

**Comment by fscarmen** [comment]
更新了，你再试试。
