### ISSUE TITLE
bbrplus 内核版本 4.14.129 获取warp ip 失败 -【已处理：4.14.129 过旧，使用脚本菜单 9.升级内核、安装BBR、DD脚本---5. 安装 BBRplus新版内核，更新至 6.7.9+ 就可以了】

### ISSUE THREAD

**Issue by NE-hazel** [fscarmen/warp-sh#63]
之前系统获取ip卡死了，就把warp完全卸载了重新安装了一次，结果现在一直获取ip失败，没法打开warp
![屏幕截图(144)](https://github.com/fscarmen/warp-sh/assets/99709727/7dba81a0-5fed-457c-9e35-50b199560937)

**Comment by fscarmen** [comment]
升级bbrplus内核到最新版本。应该是6.x的

**Comment by fscarmen** [comment]
升级了可以了吗？

**Comment by fscarmen** [comment]
你是如何升级的，我记录一下

**Comment by fscarmen** [comment]
谢谢！以后有网友一样的问题，直接让他看这个贴子的处理方案好了。

**Comment by fscarmen** [comment]
我有点好像，没有官方会配 bbrplus ，大家又是从哪里安装这么旧的版本的？
