### ISSUE TITLE
当你看到此信息，请把该 bug 反馈至

### ISSUE THREAD

**Issue by MysteriousMoon** [fscarmen/warp-sh#67]
通过 Iptable + dnsmasq + ipset，最小化实现 chatGPT，Netflix 等媒体解锁，WARP IPv4 只接管流媒体流量，改编自 e 的成熟作品，地址[https://github.com/acacia233/Project-WARP-Unlock]，请熟知 

==============================================================

 1. 安装脚本 
 0. 退出脚本 

 请选择: 1

 只能使用 wireguard-go with reserved 运行 
 没有找到适合的方案用于修改 warp 配置文件 warp.conf，脚本中止。当你看到此信息，请把该 bug 反馈至:[https://github.com/fscarmen/warp-sh/issues]

**Comment by fscarmen** [comment]
你试试安装双栈模式看看，看报错是api申请注册的时候出问题了。

**Comment by Vardven** [comment]
服务器换了N个DNS，ping谷歌都ping的通，装warp装不上
提示：检测不到任何 IPv4 或 IPv6。脚本中止

**Comment by fscarmen** [comment]
方便你发个ssh到fscarmen@gmail.com看看

**Comment by iboytech** [comment]
> 服务器换了N个DNS，ping谷歌都ping的通，装warp装不上 提示：检测不到任何 IPv4 或 IPv6。脚本中止

一样的

**Comment by fscarmen** [comment]
> > 服务器换了N个DNS，ping谷歌都ping的通，装warp装不上 提示：检测不到任何 IPv4 或 IPv6。脚本中止
> 
> 一样的

发个ssh来看看什么情况，我这里复现不了。

**Comment by iboytech** [comment]
[root ~]# bash warp-go.sh
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.aktkn.sg
 * epel: mirrors.aliyun.com
 * extras: mirror.aktkn.sg
 * updates: mirror.aktkn.sg
Package 2:vim-common-7.4.629-8.el7_9.aarch64 already installed and latest version
Nothing to do
 检查环境中……

 检测不到任何 IPv4 或 IPv6。脚本中止，问题反馈:[https://github.com/fscarmen/warp-sh/issues]

**Comment by fscarmen** [comment]
> [root ~]# bash warp-go.sh Loaded plugins: fastestmirror Loading mirror speeds from cached hostfile
> 
> * base: mirror.aktkn.sg
> * epel: mirrors.aliyun.com
> * extras: mirror.aktkn.sg
> * updates: mirror.aktkn.sg
>   Package 2:vim-common-7.4.629-8.el7_9.aarch64 already installed and latest version
>   Nothing to do
>   检查环境中……
> 
> 检测不到任何 IPv4 或 IPv6。脚本中止，问题反馈:[https://github.com/fscarmen/warp-sh/issues]

`bash -x warp-go.sh` 看看

**Comment by iboytech** [comment]
这个错误影响我使用warp，实际上已经获取到了warp v4和v6的地址，可以正常使用

**Comment by fscarmen** [comment]
> 这个错误影响我使用warp，实际上已经获取到了warp v4和v6的地址，可以正常使用

那你卸载掉，用甬哥或者p3terx的脚本试试了。
