### ISSUE TITLE
可以与一键安装openvpn这种脚本共存吗

### ISSUE THREAD

**Issue by flowerseacar** [fscarmen/warp-sh#68]
可以与一键安装openvpn这种脚本共存吗

**Comment by fscarmen** [comment]
没用过openvpn脚本，你分开安装不行么？

**Comment by fscarmen** [comment]
sorry，我没有用过openvpn，也不清楚一并安装存在些什么问题，这些只能有需求的玩家自己研究了，看如何融合了。
