### ISSUE TITLE
无法获取warp ip已经很久这样了

### ISSUE THREAD

**Issue by Deepsea-CN** [fscarmen/warp-sh#69]
[#] wg setconf warp /dev/fd/63
[#] ip -4 address add 172.16.0.2/32 dev warp
[#] ip -6 address add 2606:4700:110:85f2:ea5f:da07:17a7:42a2/128 dev warp
[#] ip link set mtu 1420 up dev warp
[#] mount `8.8.8.8 8.8.4.4 1.1.1.1 2001:4860:4860::8888 2001:4860:4860::8844 2606:4700:4700::1111' /etc/resolv.conf
[#] wg set warp fwmark 51820
[#] ip -6 route add ::/0 dev warp table 51820
[#] ip -6 rule add not fwmark 51820 table 51820
[#] ip -6 rule add table main suppress_prefixlength 0
[#] nft -f /dev/fd/63
[#] ip -4 route add 0.0.0.0/0 dev warp table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
[#] nft -f /dev/fd/63
[#] ip -4 rule add from 192.***.***.211 lookup main
 ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑ 
 失败已超过5次，脚本中止，附上以上错误提示，问题反馈:[https://github.com/fscarmen/warp-sh/issues]

**Comment by fscarmen** [comment]
你没有截全，不知道什么系统，你换个debian 12 看看

**Comment by Deepsea-CN** [comment]
哦哦，不好意思！因为上面的那部分在我复制的时候已经被顶掉了，我的系统的almalinux8.9，内核是bbr/elrepo的6.9的新内核
实测我另外一台做博客的centos7，内核是bbr稳定内核，也是这样，以前都能正常使用，现在的话都是ipv4无法获取到，每次只能kill掉进程才能恢复正常网。机器一台是美国的一台是日本的
我看了很多iuuse的方案均为尝试成功，换内核，改dns，手动刷新....（debian的话没还试过，因为手上机器都是rh系的系统）

**Comment by fscarmen** [comment]
我在almalinux8.10，今天试过是可以的

https://github.com/fscarmen/warp-sh/issues/64#issuecomment-2141145618

**Comment by Deepsea-CN** [comment]
我试了一下，问题还是出在ipv4上，单刷ipv6可以刷的出来，但是双栈或者ipv4就不行，获取不到任何ipv4
ipv6成功起来之后确实有网了，再去刷ipv4就能看见他只有我的服务器ip根本没获取到warp的ip

 脚本版本:3.0.6
 功能新增:支持 Alpine edge 系统
 系统信息:
         当前操作系统:AlmaLinux 8.9 (Midnight Oncilla)
         内核:6.9.3-1.el8.elrepo.x86_64
         处理器架构:amd64
         虚拟化:kvm 
         IPv4: 192.210.136.211 美国  HostPapa 
         IPv6: 2a09:bac5:6212:1250::1d3:73 美国  Cloudflare Warp 
         WARP 网络接口已开启
         工作模式: 全局 
         Client 未安装 
         WireProxy 未安装 

======================================================================================================================

 1.  WARP 双栈 转为 WARP IPv4 (warp 4) 
 2.  WARP 双栈 转为 WARP IPv6 (warp 6) 
 3.  变更 WARP 账户 (warp a) 
 4.  暂时关闭 WARP (warp o) 
 5.  安装 CloudFlare Client 并设置为 Proxy 模式 (bash menu.sh c) 
 6.  更换支持 Netflix 的 IP (warp i) 
 7.  永久关闭 WARP 网络接口，并删除 WARP、 Linux Client 和 WireProxy (warp u) 
 8.  刷 WARP+ 流量 (warp p) 
 9.  升级内核、安装BBR、DD脚本 (warp b) 
 10. 同步最新版本 (warp v) 
 11. WARP 解锁 Netflix 等流媒体专业一键(支持多平台、多方式和 TG 通知) 
 12. 安装 iptable + dnsmasq + ipset，让 WARP IPv4 only 接管流媒体流量 (不适用于 IPv6 only VPS) (bash menu.sh e) 
 13. 安装 wireproxy，让 WARP 在本地创建一个 socks5 代理 (bash menu.sh w) 
 14. 安装 CloudFlare Client 并设置为 WARP 模式 (bash menu.sh l) 
 0.  退出脚本 

 请选择: 6

 1. 刷 WARP IPv4 (默认)
 2. 刷 WARP IPv6 

 请选择: 1
 当前 Netflix 地区是:US，需要解锁当前地区请按 [y], 如需其他地址请输入两位地区简写 (如 hk ,sg，默认:US): 
 2024-05-31 17:17:30 尝试第1次，解锁失败，IPv4: 192.***.***.211 美国 HostPapa，10秒后重新测试，刷 IP 运行时长: 0 天 0 时 0 分 4 秒 
 2024-05-31 17:21:02 尝试第2次，解锁失败，IPv4: 192.***.***.211 美国 HostPapa，10秒后重新测试，刷 IP 运行时长: 0 天 0 时 0 分 17 秒

**Comment by fscarmen** [comment]
> 我的系统的almalinux8.9

刚刚更新了，对 CentOS 9 全部支持了，我测试 AlmaLinux 8.10 也是可以的，不太清楚你那里为什么不行了。
