### ISSUE TITLE
看了文档好像没有定时更换WARP.IP选项

### ISSUE THREAD

**Issue by yqk100** [fscarmen/warp-sh#71]
比如：
每隔30分钟更后台自动换一次WARP.IP；
单纯更换IP，不是为了刷流媒体/解锁(warp i)。

这个要求可能很奇葩，有些VPS上游(NETLAB)防火墙规则就是一坨屎，长时间连接一个IP走流量会被限制。。。。

**Comment by fscarmen** [comment]
是的，你提到的需求很个性化了，实现起来也不是一两条命令能处理完的。
