### ISSUE TITLE
[BUG] Ubuntu 24.04 LTS  加载[5] 安装Client  报错: [```.....] 原因已知

### ISSUE THREAD

**Issue by 254c** [fscarmen/warp-sh#75]
脚本版本:3.0.7
 功能新增:支持 CentOS 9 / Alma Linux 9 / Rocky Linux 9 系统
 系统信息:
         当前操作系统:Ubuntu 24.04 LTS
         内核:6.8.0-1008-gcp
         处理器架构:amd64
         虚拟化:google 
         IPv4: 104.*.*.105 日本  Cloudflare, Inc. 
         IPv6: 2a09:*:*:*::*:213 日本  Cloudflare Warp 
         WARP 网络接口已开启
         工作模式: 全局 
         Client 未安装 
         WireProxy 未安装 

======================================================================================================================

 1.  WARP 双栈 转为 WARP IPv4 (warp 4) 
 2.  WARP 双栈 转为 WARP IPv6 (warp 6) 
 3.  变更 WARP 账户 (warp a) 
 4.  暂时关闭 WARP (warp o) 
 5.  安装 CloudFlare Client 并设置为 Proxy 模式 (bash menu.sh c) 
 6.  更换支持 Netflix 的 IP (warp i) 
 7.  永久关闭 WARP 网络接口，并删除 WARP、 Linux Client 和 WireProxy (warp u) 
 8.  刷 WARP+ 流量 (warp p) 
 9.  升级内核、安装BBR、DD脚本 (warp b) 
 10. 同步最新版本 (warp v) 
 11. WARP 解锁 Netflix 等流媒体专业一键(支持多平台、多方式和 TG 通知) 
 12. 安装 iptable + dnsmasq + ipset，让 WARP IPv4 only 接管流媒体流量 (不适用于 IPv6 only VPS) (bash menu.sh e) 
 13. 安装 wireproxy，让 WARP 在本地创建一个 socks5 代理 (bash menu.sh w) 
 14. 安装 CloudFlare Client 并设置为 WARP 模式 (bash menu.sh l) 
 0.  退出脚本 

 请选择: 5
 如有 WARP+ License 请输入，没有可回车继续: 
 请自定义 Client 端口号 (1000-65535，如果不输入，会默认40000): 51482
 进度 1/2: 安装 Client…… 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1688  100  1688    0     0   4007      0 --:--:-- --:--:-- --:--:--  4000
deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ noble main
Hit:1 http://asia-northeast1.gce.archive.ubuntu.com/ubuntu noble InRelease
Hit:2 http://asia-northeast1.gce.archive.ubuntu.com/ubuntu noble-updates InRelease              
Hit:3 http://asia-northeast1.gce.archive.ubuntu.com/ubuntu noble-backports InRelease            
Hit:4 http://security.ubuntu.com/ubuntu noble-security InRelease                                
Ign:5 https://pkg.cloudflareclient.com noble InRelease                                          
Err:6 https://pkg.cloudflareclient.com noble Release                      
  404  Not Found [IP: 104.16.80.230 443]
Hit:7 https://download.docker.com/linux/ubuntu noble InRelease
Reading package lists... Done
E: The repository 'https://pkg.cloudflareclient.com noble Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package cloudflare-warp
Failed to start warp-svc.service: Unit warp-svc.service not found.
 进度 2/2: 设置 Client 模式 
menu.sh: line 2357: warp-cli: command not found
 创建 Socks5 代理失败，问题反馈:[https://github.com/fscarmen/warp-sh/issues] 
操作完成
按任意键继续...

**Comment by 254c** [comment]
E: Unable to locate package cloudflare-warp
Failed to start warp-svc.service: Unit warp-svc.service not found.
==================================================================
URL 没有资源--->下载不了Client包--->Failed to start [Warp-svc.service]

**Comment by fscarmen** [comment]
已更新，你再安装看看。
