### ISSUE TITLE
Problem getting IP

### ISSUE THREAD

**Issue by jffluis** [fscarmen/warp-sh#76]
Using on Raspberry Pi 4 with Debian

 Choose: 1

 Is there a WARP+ or Teams account?
 1. WARP+
 2. Teams
 3. Use free account (default)

 Choose: 3

**gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now**

 Step 3/3: Best MTU and Endpoint found.

 Maximum 5 attempts to register WARP free account...
 Try 1

 Step 2/3: Install warp-go...

 Step 1/3: Install dependencies...

 Maximum 5 attempts to get WARP IP...
 Try 1
 Try 2
 Try 3
 Try 4
 Try 5
 Failed more than 5 times, script aborted. Feedback: [https://github.com/fscarmen/warp-sh/issues]

**Comment by fscarmen** [comment]
Use menu.sh instead.
