### ISSUE TITLE
CloudFlare Client 模式下不能安装ipv6 warp

### ISSUE THREAD

**Issue by tox20** [fscarmen/warp-sh#78]
CloudFlare Client模式下，安装ipv6 warp失败，试过多次均一样。
1. 走WARP网络接口，据说容易掉线； 2.wireproxy找IP时很随机大概率会与服务器距离较远，影响速度； 3.综合考虑不易掉线和依服务器近距离找IP，才选择CloudFlare Client。可配置是总是调不出ipv6，哪个大神知道怎么回事儿，多谢

![2024-06-15_52](https://github.com/fscarmen/warp-sh/assets/172121105/8606d51f-0bdf-4680-9421-6e8f52e30025)
![2024-06-15_10](https://github.com/fscarmen/warp-sh/assets/172121105/c8720548-1dcf-4c63-8c3b-d4008a33189e)

**Comment by fscarmen** [comment]
`bash -x menu.sh` 看看

**Comment by tox20** [comment]
> `bash -x menu.sh d` 看看

![2024-06-15_38](https://github.com/fscarmen/warp-sh/assets/172121105/b147b43a-b995-46eb-af2e-8624801fef65)

请问下一步该怎么操作，多谢

**Comment by fscarmen** [comment]
你要先wget 下载该 menu.sh 文件啊。

**Comment by tox20** [comment]
> bash -x menu.sh d
1. wget -N https://gitlab.com/fscarmen/warp/-/raw/main/menu.sh && bash menu.sh [option] [lisence/url/token]
2. bash -x menu.sh d
3. 显示图片的内容，请问怎么选择，按默认无效
![2024-06-15_40](https://github.com/fscarmen/warp-sh/assets/172121105/351b319b-558d-47f9-a684-e03d8b654e35)

**Comment by fscarmen** [comment]
运行下去，看哪里报错

**Comment by fscarmen** [comment]
上两个版本已更新，支持双栈。
