### ISSUE TITLE
wireguard-tools 安装失败

### ISSUE THREAD

**Issue by a1497014378** [fscarmen/warp-sh#80]
所有依赖已存在，不需要额外安装 

 检查环境中…… 
 本项目专为 VPS 添加 warp 网络接口，详细说明: [https://github.com/fscarmen/warp-sh]
 脚本特点:
         • 支持 WARP+ 账户，附带第三方刷 WARP+ 流量和升级内核 BBR 脚本
         • 普通用户友好的菜单，进阶者通过后缀选项快速搭建
         • 智能判断操作系统: Ubuntu 、Debian 、CentOS、 Alpine 和 Arch Linux，请务必选择 LTS 系统
         • 支持硬件结构类型: AMD、 ARM 和 s390x
         • 结合 Linux 版本和虚拟化方式，自动优选4个 WireGuard 方案。网络性能方面: 内核集成 WireGuard > 安 装内核模块 > wireguard-go
         • 支持 WARP Linux Socks5 Client
         • 输出执行结果，提示是否使用 WARP IP ，IP 归属地和线路提供商
 
======================================================================================================================

 脚本版本:3.0.7
 功能新增:支持 CentOS 9 / Alma Linux 9 / Rocky Linux 9 系统
 系统信息:
         当前操作系统:Debian GNU/Linux 11 (bullseye)
         内核:5.10.0-28-amd64
         处理器架构:amd64
         虚拟化:lxc 
         IPv4: 93.185.159.92 俄罗斯  International Hosting Company 
         IPv6: 2a0f:cdc6:50:228::1 俄罗斯  International Hosting Company 
         WARP 网络接口未开启 
         Client 未安装 
         WireProxy 未安装 

======================================================================================================================

 1.  WARP IPv4 转为 WARP IPv6 (warp 6) 
 2.  WARP IPv4 转为 WARP 双栈 (warp d) 
 3.  变更 WARP 账户 (warp a) 
 4.  打开 WARP (warp o) 
 5.  安装 CloudFlare Client 并设置为 Proxy 模式 (bash menu.sh c) 
 6.  更换支持 Netflix 的 IP (warp i) 
 7.  永久关闭 WARP 网络接口，并删除 WARP、 Linux Client 和 WireProxy (warp u) 
 8.  刷 WARP+ 流量 (warp p) 
 9.  升级内核、安装BBR、DD脚本 (warp b) 
 10. 同步最新版本 (warp v) 
 11. WARP 解锁 Netflix 等流媒体专业一键(支持多平台、多方式和 TG 通知) 
 12. 安装 iptable + dnsmasq + ipset，让 WARP IPv4 only 接管流媒体流量 (不适用于 IPv6 only VPS) (bash menu.sh e) 
 13. 安装 wireproxy，让 WARP 在本地创建一个 socks5 代理 (bash menu.sh w) 
 14. 安装 CloudFlare Client 并设置为 WARP 模式 (bash menu.sh l) 
 0.  退出脚本 

 请选择: 2
Failed to restart wg-quick@warp.service: Unit wg-quick@warp.service not found.
 wireguard-tools 安装失败，脚本中止，问题反馈:[https://github.com/fscarmen/warp-sh/issues] 
root@ser195890407321:~#

**Comment by fscarmen** [comment]
```
apt-get update; apt-get install -y wireguard-tools
```

看看报错什么，喂给 GPT 或者 google 看如何安装成功。
