### ISSUE TITLE
失败已超过5次，脚本中止，附上以上错误提示，问题反馈

### ISSUE THREAD

**Issue by shiqu36** [fscarmen/warp-sh#81]
root@ipv6xpd4ky:~# warp a

 所有依赖已存在，不需要额外安装

 检查环境中……

 当前账户类型是: WARP Free

 1. 继续使用 free 账户，不变更
 2. 变更为 WARP+ 账户
 3. 变更为 Teams 账户
 0. 退出脚本

 请选择: 2
 请输入WARP+ License: pB69d8N2-8m92q5rN-37zAhZ68
 请自定义 WARP+ 设备名 (默认为 ipv6xpd4ky):

 升级 WARP+ 账户中……

 已变更为 WARP+ 账户

 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试
 第2次尝试
 第3次尝试
 第4次尝试
 第5次尝试
 ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
 当前操作系统: Ubuntu 22.04 LTS

 内核:5.15.0-30-generic

 菜单选项: 0.  退出脚本

 Warning: `/etc/wireguard/warp.conf' is world accessible
[#] ip link add warp type wireguard
[#] wg setconf warp /dev/fd/63
[#] ip -4 address add 172.16.0.2/32 dev warp
[#] ip -6 address add 2606:4700:110:82fc:2553:7788:68bb:15fd/128 dev warp
[#] ip link set mtu 1400 up dev warp
[#] resolvconf -a warp -m 0 -x
[#] wg set warp fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev warp table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
[#] nft -f /dev/fd/63
[#] ip -6 rule add from 2408:871a:b000:2::ae8 lookup main
 ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
 失败已超过5次，脚本中止，附上以上错误提示，问题反馈:[https://github.com/fscarmen/warp-sh/issues]

warp安装第一次启动后可获取到ipv4地址，过两小时后就不能获取了，切换了warp+账号也无法获取

**Comment by fscarmen** [comment]
warp o 开关看看

**Comment by shiqu36** [comment]
> warp o 开关看看

======================================================================================================================

 1.  WARP IPv4 转为 WARP IPv6 (warp 6) 
 2.  WARP IPv4 转为 WARP 双栈 (warp d) 
 3.  变更 WARP 账户 (warp a) 
 4.  打开 WARP (warp o) 
 5.  安装 CloudFlare Client 并设置为 Proxy 模式 (bash menu.sh c) 
 6.  更换支持 Netflix 的 IP (warp i) 
 7.  永久关闭 WARP 网络接口，并删除 WARP、 Linux Client 和 WireProxy (warp u) 
 8.  刷 WARP+ 流量 (warp p) 
 9.  升级内核、安装BBR、DD脚本 (warp b) 
 10. 同步最新版本 (warp v) 
 11. WARP 解锁 Netflix 等流媒体专业一键(支持多平台、多方式和 TG 通知) 
 12. 安装 iptable + dnsmasq + ipset，让 WARP IPv4 only 接管流媒体流量 (不适用于 IPv6 only VPS) (bash menu.sh e) 
 13. 安装 wireproxy，让 WARP 在本地创建一个 socks5 代理 (bash menu.sh w) 
 14. 安装 CloudFlare Client 并设置为 WARP 模式 (bash menu.sh l) 
 0.  退出脚本 

 请选择: 4
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
 第2次尝试 
 第3次尝试 
 第4次尝试 
 第5次尝试 
 ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
 当前操作系统: Ubuntu 22.04 LTS

 内核:5.15.0-30-generic 

 菜单选项: 4.  打开 WARP (warp o) 

 Warning: `/etc/wireguard/warp.conf' is world accessible
[#] ip link add warp type wireguard
[#] wg setconf warp /dev/fd/63
[#] ip -4 address add 172.16.0.2/32 dev warp
[#] ip -6 address add 2606:4700:110:82fc:2553:7788:68bb:15fd/128 dev warp
[#] ip link set mtu 1400 up dev warp
[#] resolvconf -a warp -m 0 -x
[#] wg set warp fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev warp table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
[#] nft -f /dev/fd/63
[#] ip -6 rule add from 2408:871a:b000:2::ae8 lookup main
 ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑ 
 失败已超过5次，脚本中止，附上以上错误提示，问题反馈:[https://github.com/fscarmen/warp-sh/issues] 
root@ipv6xpd4ky:~# warp o
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
 第2次尝试 
 第3次尝试 
 第4次尝试 
 第5次尝试 
 ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
 当前操作系统: Ubuntu 22.04 LTS

 内核:5.15.0-30-generic 

 菜单选项:  

 Warning: `/etc/wireguard/warp.conf' is world accessible
[#] ip link add warp type wireguard
[#] wg setconf warp /dev/fd/63
[#] ip -4 address add 172.16.0.2/32 dev warp
[#] ip -6 address add 2606:4700:110:82fc:2553:7788:68bb:15fd/128 dev warp
[#] ip link set mtu 1400 up dev warp
[#] resolvconf -a warp -m 0 -x
[#] wg set warp fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev warp table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
[#] nft -f /dev/fd/63
[#] ip -6 rule add from 2408:871a:b000:2::ae8 lookup main
 ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑ 
 失败已超过5次，脚本中止，附上以上错误提示，问题反馈:[https://github.com/fscarmen/warp-sh/issues] 
root@ipv6xpd4ky:~# 


重启两遍了还是不行

**Comment by fscarmen** [comment]
看不出问题哦，运行正常的呢

**Comment by susendev** [comment]
同样的问题

$ warp o
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 
 第2次尝试 
 第3次尝试 
 第4次尝试 
 第5次尝试 
 ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
 当前操作系统: Ubuntu 20.04.6 LTS

 内核:6.7.9-bbrplus 

 菜单选项:  

 Warning: `/etc/wireguard/warp.conf' is world accessible
[#] ip link add warp type wireguard
[#] wg setconf warp /dev/fd/63
[#] ip -4 address add 172.16.0.2/32 dev warp
[#] ip -6 address add 2606:4700:110:8234:a52f:a093:5a65:dbda/128 dev warp
[#] ip link set mtu 1420 up dev warp
[#] resolvconf -a warp -m 0 -x
[#] wg set warp fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev warp table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
[#] iptables-restore -n
[#] ip -4 rule add from 10.0.0.100 lookup main
 ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑ 
 失败已超过5次，脚本中止，附上以上错误提示，问题反馈:[https://github.com/fscarmen/warp-sh/issues]

**Comment by fscarmen** [comment]
可以的话，换个非bbrplus内核看看

**Comment by susendev** [comment]
> 可以的话，换个非bbrplus内核看看

可能是机器问题，新开一台机器没事了
