### ISSUE TITLE
我煞笔了，误删root和etc文件夹下的warp.conf文件，导致现在卡在这一步没法卸载或重装warp，见正文所粘贴内容

### ISSUE THREAD

**Issue by git72138847** [fscarmen/warp-sh#82]
1.  WARP 双栈 转为 WARP IPv4 (warp 4) 
 2.  WARP 双栈 转为 WARP IPv6 (warp 6) 
 3.  变更 WARP 账户 (warp a) 
 4.  打开 WARP (warp o) 
 5.  (!!! 只支持 AMD64，请勿选择)安装 CloudFlare Client 并设置为 Proxy 模式 (bash menu.sh c) 
 6.  更换支持 Netflix 的 IP (warp i) 
 7.  永久关闭 WARP 网络接口，并删除 WARP、 Linux Client 和 WireProxy (warp u) 
 8.  刷 WARP+ 流量 (warp p) 
 9.  升级内核、安装BBR、DD脚本 (warp b) 
 10. 同步最新版本 (warp v) 
 11. WARP 解锁 Netflix 等流媒体专业一键(支持多平台、多方式和 TG 通知) 
 12. 安装 iptable + dnsmasq + ipset，让 WARP IPv4 only 接管流媒体流量 (不适用于 IPv6 only VPS) (bash menu.sh e) 
 13. 安装 wireproxy，让 WARP 在本地创建一个 socks5 代理 (bash menu.sh w) 
 14. (!!! 只支持 AMD64，请勿选择)安装 CloudFlare Client 并设置为 WARP 模式 (bash menu.sh l) 
 0.  退出脚本 

 请选择: 2
sed: can't read /etc/wireguard/warp.conf: No such file or directory
Failed to restart wg-quick@warp.service: Unit wg-quick@warp.service not found.
 wireguard-tools 安装失败，脚本中止，问题反馈:[https://github.com/fscarmen/warp-sh/issues] 
操作完成
按任意键继续...

**Comment by git72138847** [comment]
不知咋找回vps上已经删除的这个warp.conf文件。
然后我自己在另一个安装了warp的vps上拷贝warp.conf到这台机器上，还是报错 - - ！  小白请大佬指点下，真不想删机重开了

**Comment by fscarmen** [comment]
`warp u` 卸载后重装不行吗？肯定不需要删机重开的。
