### ISSUE TITLE
选择Teams账号后，输入token后，卡住了，断开VPS后，再次无法进入安装选项界面

### ISSUE THREAD

**Issue by engama** [fscarmen/warp-sh#84]
大佬，我遇到的问题，看见已经有人提了issue，但是他们可能后续还可以继续使用脚本，我则是不能进入选项界面，即使想把安装的卸载掉都没机会。我前面安装也是卡在了token这块，不动了，于是我就主动退出连接，reboot了VPS。当我再次使用安装连接的时候，选择语言后就提示”不能切换为当前一样的形态“；于是我就没办法进行到下一步了。
![1720110649(1)](https://github.com/fscarmen/warp-sh/assets/62509677/196990fd-3e1f-4a9b-840d-206d524a7e5f)
![微信图片_20240705003114](https://github.com/fscarmen/warp-sh/assets/62509677/898d3f8a-6142-4d6a-801e-8b5ee71ae24c)

**Comment by engama** [comment]
后续解决的方法已经找到了，我又找了其它人的安装脚本，应该和选择fscarman大大的早期版本，因此可以通过找到的这个脚本进行warp的卸载，然后再进行安装；同时安装的时候第一次若选teams千万别用token，后面可以装好了再升级。

**Comment by engama** [comment]
忘记贴后来找到的链接了。
wget -N https://gitlab.com/fscarmen/warp/-/raw/main/menu.sh && bash menu.sh [option] [lisence/url/token]

**Comment by fscarmen** [comment]
我试过是可以的，上年8月份的时候已经换成
```
wget -N https://gitlab.com/fscarmen/warp/-/raw/main/menu.sh
```
<img width="1397" alt="image" src="https://github.com/fscarmen/warp-sh/assets/62703343/35f00364-a865-456f-9b9a-e981c6e52205">

**Comment by fscarmen** [comment]
> 是他们可能后续还可以继续使用脚本，我则是不能进入选项界面，即使想把安装的卸载掉都没机会。我前面安装也是卡在了token这块，不动了，于是我就主动退出连接，reboot了VPS。当我再次使用安装连接的时候，选择语言后就提示”不能切换为当前一样的形态“；于是我就没办法进行到下一步了。

卸载用 `bash menu.sh u`
