### ISSUE TITLE
debain9报错

### ISSUE THREAD

**Issue by hzhig** [fscarmen/warp-sh#86]
Ign:1 http://archive.debian.org/debian stretch InRelease                            
Hit:2 http://archive.debian.org/debian stretch Release                              
Ign:3 http://deb.debian.org/debian stretch-backports InRelease
Get:4 http://deb.debian.org/debian unstable InRelease [198 kB]
Err:5 http://deb.debian.org/debian stretch-backports Release 
  404  Not Found [IP: 2a04:4e42:9::644 80]
Err:4 http://deb.debian.org/debian unstable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
Reading package lists... Done
E: The repository 'http://deb.debian.org/debian stretch-backports Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://deb.debian.org/debian unstable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
E: The repository 'http://deb.debian.org/debian unstable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
dnsutils is already the newest version (1:9.10.3.dfsg.P4-12.3+deb9u6).
iptables is already the newest version (1.6.0+snapshot20161117-6).
net-tools is already the newest version (1.60+git20161116.90da8a0-1).
openresolv is already the newest version (3.8.0-1).
0 upgraded, 0 newly installed, 0 to remove and 92 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 wireguard-tools : Depends: libc6 (>= 2.38) but 2.24-11+deb9u4 is to be installed
E: Unable to correct problems, you have held broken packages.
menu.sh: line 2137: wg: command not found
grep: /usr/bin/wg-quick: No such file or directory
sed: can't read /usr/bin/wg-quick: No such file or directory

**Comment by fscarmen** [comment]
把日志喂给gpt处理，看是wireguard-tools没安装成功

**Comment by fscarmen** [comment]
你遇到的错误表明你当前使用的 Debian 存储库不再支持你正在使用的版本，或者某些包的公钥缺失导致无法安装。要解决这些问题，可以按照以下步骤进行操作：

1. **更新存储库源列表**：
    确保你的 `/etc/apt/sources.list` 文件包含正确的存储库链接。因为 Debian Stretch 已经过期，可以使用存档存储库。

    ```sh
    sudo nano /etc/apt/sources.list
    ```

    替换内容如下：

    ```plaintext
    deb http://archive.debian.org/debian stretch main
    deb-src http://archive.debian.org/debian stretch main

    deb http://deb.debian.org/debian stretch-backports main
    deb-src http://deb.debian.org/debian stretch-backports main

    deb http://deb.debian.org/debian unstable main
    deb-src http://deb.debian.org/debian unstable main
    ```

2. **添加存档存储库的密钥**：
    运行以下命令来获取所需的公钥。

    ```sh
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0E98404D386FA1D9
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6ED0E7B82643E131
    ```

3. **更新包列表**：
    运行以下命令更新包列表。

    ```sh
    sudo apt-get update
    ```

4. **安装所需的包**：
    安装所需的软件包。如果某些软件包仍然无法安装，尝试升级 `libc6`。

    ```sh
    sudo apt-get install libc6
    sudo apt-get install wireguard-tools
    ```

5. **禁用过期的存储库**：
    如果你不再需要 `stretch-backports` 或 `unstable` 存储库，可以将它们注释掉。

    ```sh
    sudo nano /etc/apt/sources.list
    ```

    将 `stretch-backports` 和 `unstable` 的条目前加上 `#`：

    ```plaintext
    # deb http://deb.debian.org/debian stretch-backports main
    # deb-src http://deb.debian.org/debian stretch-backports main

    # deb http://deb.debian.org/debian unstable main
    # deb-src http://deb.debian.org/debian unstable main
    ```

    保存并退出编辑器，然后再次运行 `sudo apt-get update`。

以上步骤应该可以帮助你解决依赖问题和公钥错误。如果问题依然存在，可能需要考虑升级到较新的 Debian 版本。
