### ISSUE TITLE
udp被限制

### ISSUE THREAD

**Issue by wcwq98** [fscarmen/warp-sh#87]
报错：WARP 的所有的 endpoint 均不能连通 但问了服务商也没见说被限制 重装系统也不见得
![1912671d3f05659f7e43341b3616dfdf](https://github.com/user-attachments/assets/298247cf-3143-4443-919c-765be08a9edb)

**Comment by fscarmen** [comment]
看看
```
wget --no-check-certificate -O /dev/null https://gitlab.com/fscarmen/warp/-/raw/main/wireguard-go/wireguard-go-linux-amd64-20230223
```

**Comment by wcwq98** [comment]
还是不行

**Comment by fscarmen** [comment]
> 还是不行

是不是 IPv6 only的机器？如果是看看是不是这个问题 https://github.com/fscarmen/warp-sh/issues/85

**Comment by wcwq98** [comment]
很奇怪 我刚刚重装了下系统，第一次直接运行不行 第二次运行你给的命令又能获取到ip了

**Comment by wcwq98** [comment]
是仅ipv6的机器  那获取不到ip是什么原因呢

**Comment by fscarmen** [comment]
应该是dns64 的问题，访问的 github 站点不支持 IPv6

**Comment by wcwq98** [comment]
那有办法解决吗 现在又自动掉IP了 还连接不上

**Comment by fscarmen** [comment]
看这个，是没有错误的哦，看不出问题

**Comment by wcwq98** [comment]
这是udp被限制的输出吗
root@ECS1280:~/QChatGPT# head -n 10 /tmp/endpoint_result
IP:PORT, LOSS, DELAY
162.159.192.55:4233,0.00%,timeout ms
162.159.192.0:4233,0.00%,timeout ms
162.159.192.0:8742,0.00%,timeout ms
162.159.192.1:4233,0.00%,timeout ms
162.159.192.1:8742,0.00%,timeout ms
162.159.192.2:4233,0.00%,timeout ms
162.159.192.2:8742,0.00%,timeout ms
162.159.192.3:4233,0.00%,timeout ms
162.159.192.3:8742,0.00%,timeout ms

**Comment by fscarmen** [comment]
是的，全部 timeout 了，即是全部 endpoint 都不通。

**Comment by wcwq98** [comment]
但是我提交了工单服务商说并没有禁用udp端口
创建时间：2024-07-21 18:38

工单部门：技术部门
产品：IPV6云2H2G3M型
用户
黄庆珍
2024-07-21 18:38:05
检测udp端口的运行日志：

2024/07/21 18:34:25 测试端点162.159.195.252:8854时出错：连接162.159.195.252:8854时出错：dial udp 162.159.195.252:8854: connect: network is unreachable

2024/07/21 18:34:25 测试端点162.159.195.253:943时出错：连接162.159.195.253:943时出错：dial udp 162.159.195.253:943: connect: network is unreachable

2024/07/21 18:34:25 测试端点162.159.195.252:943时出错：连接162.159.195.252:943时出错：dial udp 162.159.195.252:943: connect: network is unreachable

2024/07/21 18:34:25 测试端点162.159.195.253:8854时出错：连接162.159.195.253:8854时出错：dial udp 162.159.195.253:8854: connect: network is unreachable

2024/07/21 18:34:25 测试端点162.159.195.254:8854时出错：连接162.159.195.254:8854时出错：dial udp 162.159.195.254:8854: connect: network is unreachable

2024/07/21 18:34:25 测试端点162.159.195.254:943时出错：连接162.159.195.254:943时出错：dial udp 162.159.195.254:943: connect: network is unreachable

测试结果已经写入/tmp/endpoint_result

root@ECS1280:~/QChatGPT# head -n 10 /tmp/endpoint_result

IP:PORT, LOSS, DELAY

162.159.192.0:3138,0.00%,timeout ms

162.159.192.13:3138,0.00%,timeout ms

162.159.192.0:500,0.00%,timeout ms

162.159.192.1:3138,0.00%,timeout ms

162.159.192.13:500,0.00%,timeout ms

162.159.192.14:3138,0.00%,timeout ms

162.159.192.14:500,0.00%,timeout ms

162.159.192.15:3138,0.00%,timeout ms

162.159.192.15:500,0.00%,timeout ms

管理员
管理员
2024-07-21 18:38:17
您的问题已收到，我们将会尽快处理您的问题，请耐心等待，感谢您的支持理解。 为了更快的解决您的问题，请先阅读一下帮助文档https://www.8465.cn/helpcontent/45.html
管理员
管理员
2024-07-21 18:39:07
您好UDP我们并没有限制，请检查目标是否支持IPV6

**Comment by wcwq98** [comment]
想问问有办法检测仅ipv6机器的udp端口吗

**Comment by fscarmen** [comment]
哦，如果你是IPv6的机器，应该用 IPv6 的 IP来测啊
```
wget -O /tmp/endpoint https://gitlab.com/fscarmen/warp/-/raw/main/endpoint/warp-linux-amd64 && chmod +x /tmp/endpoint

wget -O /tmp/ip https://gitlab.com/fscarmen/warp/-/raw/main/endpoint/ipv6

/tmp/endpoint -file /tmp/ip -output /tmp/endpoint_result

head -10 /tmp/endpoint_result
```

**Comment by fscarmen** [comment]
```
echo -ne '\x00\x01\x00\x00\x21\x12\xA4\x42\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' | nc -u -w1 stun.cloudflare.com 3478 | xxd -p
```

**Comment by wcwq98** [comment]
用了第一段命令返回了这个想
2024/07/21 19:49:25 [2606:4700:d0::a29f:c1fb]:3581 数据包丢失
2024/07/21 19:49:25 [2606:4700:d0::a29f:c1fc]:7281 数据包丢失
2024/07/21 19:49:25 [2606:4700:d0::a29f:c1ff]:7281 数据包丢失
2024/07/21 19:49:25 [2606:4700:d0::a29f:c1ff]:3581 数据包丢失
2024/07/21 19:49:25 [2606:4700:d0::a29f:c1fe]:3581 数据包丢失
2024/07/21 19:49:25 [2606:4700:d0::a29f:c1fd]:3581 数据包丢失
2024/07/21 19:49:25 [2606:4700:d0::a29f:c1fd]:7281 数据包丢失
2024/07/21 19:49:25 [2606:4700:d0::a29f:c1fe]:7281 数据包丢失
测试结果已经写入/tmp/endpoint_result
root@ECS1280:~# 
root@ECS1280:~# head -10 /tmp/endpoint_result
IP:PORT, LOSS, DELAY
[2606:4700:100::a29f:c112]:880,100.00%,1000 ms
[2606:4700:100::a29f:c193]:4198,100.00%,1000 ms
[2606:4700:100::a29f:c102]:4198,100.00%,1000 ms
[2606:4700:100::a29f:c118]:4198,100.00%,1000 ms
[2606:4700:100::a29f:c170]:4198,100.00%,1000 ms
[2606:4700:100::a29f:c1e3]:4198,100.00%,1000 ms
[2606:4700:100::a29f:c168]:4198,100.00%,1000 ms
[2606:4700:100::a29f:c1fa]:880,100.00%,1000 ms
[2606:4700:100::a29f:c1ef]:880,100.00%,1000 ms
root@ECS1280:~#

**Comment by wcwq98** [comment]
第二个命令没有返回信息

**Comment by fscarmen** [comment]
你可以安装一些 udp 的协议 , Hysteria 1 / Hysteria 2 / Tuic V5，看看节点通不通就知道了。

**Comment by wcwq98** [comment]
好我试试

**Comment by wcwq98** [comment]
大佬我搞不定要不还是你来吧（目前应该是搭好hysteria但ping不通）

**Comment by fscarmen** [comment]
> 大佬我搞不定要不还是你来吧（目前应该是搭好hysteria但ping不通）

其实不用多试的，就是你的 vps 限制了 udp ，所以基于 udp 的协议都不通。重置系统，再不行仍然发 ticket

**Comment by wcwq98** [comment]
重置系统没多久又会掉IP  现在已经提交工单给服务商了 但服务商一直说他们没限制udp服务
