### ISSUE TITLE
安装过程报错

### ISSUE THREAD

**Issue by HenryYuen-ai** [fscarmen/warp-sh#88]
没有找到适合的方案用于修改 warp 配置文件 warp.conf，脚本中止。当你看到此信息，请把该 bug 反馈至:[https://github.com/fscarmen/warp-sh/issues]

**Comment by fscarmen** [comment]
运行 `bash -x menu.sh` 看看日志，有可能是 ping `2606:4700:d0::a29f:c001`和 `162.159.193.10` 都不通。

**Comment by kufei326** [comment]
![IMG_5048](https://github.com/user-attachments/assets/136d4c7a-7a53-4690-93fb-8e89e3aa87eb)

**Comment by fscarmen** [comment]
是大陆的vps吗？

**Comment by kufei326** [comment]
> 是大陆的vps吗？

家里的宽带

**Comment by fscarmen** [comment]
应该是连不上 github 或者 被限制了不能使用 udp ，又或者限制了不让连 warp endpoint 所致的。
