### ISSUE TITLE
检测不到任何 IPv4 或 IPv6。脚本中止，问题反馈:[https://github.com/fscarmen/warp-sh/issues] 

### ISSUE THREAD

**Issue by xinghanxu666** [fscarmen/warp-sh#89]
检测不到任何 IPv4 或 IPv6。脚本中止，问题反馈:[https://github.com/fscarmen/warp-sh/issues] 
实际使用命令查IP时，可以查到IP

**Comment by fscarmen** [comment]
https://github.com/fscarmen/warp-sh/issues/85

如果是 IPv6 的机器，看看是不是这个问题
