### ISSUE TITLE
纯ipv6机器，在执行脚本后，dns第一个会变成1.1.1.1，导致curl超时

### ISSUE THREAD

**Issue by OuOumm** [fscarmen/warp-sh#9]
纯ipv6机器（有ipv4落地），在执行脚本后，dns第一个会变成1.1.1.1，导致curl超时

修改成8.8.8.8之后一切正常，但是脚本每次运行都会自动改成1.1.1.1

有没有啥办法解决吗？

**Comment by OuOumm** [comment]
我把脚本内跟warp.conf文件内的1.1.1.1全删了之后好了，umm不知道是不是解决方法，改成了谷歌的dns，还是谷歌稳定。

**Comment by fscarmen** [comment]
> 我把脚本内跟warp.conf文件内的1.1.1.1全删了之后好了，umm不知道是不是解决方法，改成

现在有个问题好头痛，上两周开始， dns 为 1.1.1.1  不稳，有的机器获取不了 ip，上周改为8.8.8.8后就OK了，但另一个问题又来了，有网友反馈延时变高了，改回1.1.1.1就好了。

因为脚本考虑通用的问题，肯定用8.8.8.8以保证稳定的。所以我的建议是会玩的用户，可以`warp o` 停了，暂时手动改配置文件 `/etc/wireguard/warp.conf` 里的 dns ，把 1.1.1.1 放到最前，再 `warp o` 开启，如果能正常获取 IP 就好了，如果不能，换回 8.8.8.8

**Comment by okaygh** [comment]
原来是DNS的问题吗,这2天我的JPV6死活装不上,一直报错获取不了conf,之前一直倒是一直正常

**Comment by kkbeta** [comment]
我也是只能获取到ipv4，ipv6获取不了。用官方推荐的安装方式来安装就可以，但那样子没法搞非全局。
