### ISSUE TITLE
 wireguard-tools 安装失败，脚本中止，问题反馈:[https://github.com/fscarmen/warp-sh/issues] 

### ISSUE THREAD

**Issue by Hot-baby** [fscarmen/warp-sh#90]
wireguard-tools 安装失败，脚本中止，问题反馈:[https://github.com/fscarmen/warp-sh/issues]

**Comment by fscarmen** [comment]
手动安装一下看看，有什么报错喂给 gpt 看看

**Comment by danbao** [comment]
## 错误报告

**系统信息:**
- 当前操作系统: Alpine Linux v3.20
- 内核: 6.6.41-0-virt
- 处理器架构: amd64
- 虚拟化: kvm
- IPv4: xxx.xxx.xxx.xxx
- IPv6:
- WARP 网络接口已开启
- 工作模式:
  - Client 未安装
  - WireProxy 未安装

**错误描述:**
在尝试安装 
```wget -N https://gitlab.com/fscarmen/warp/-/raw/main/menu.sh && bash menu.sh 6```
时，脚本报错并中止，错误信息如下：
```
sed: /etc/wireguard/warp.conf: No such file or directory
wireguard-tools 安装失败，脚本中止，问题反馈: [https://github.com/fscarmen/warp-sh/issues]
```

**手动安装尝试:**
在手动执行 `apk add wireguard-tools` 后，错误信息如下：
```
sed: /etc/wireguard/warp.conf: No such file or directory
找不到配置文件 warp.conf，脚本中止，问题反馈: [https://github.com/fscarmen/warp-sh/issues]
```

**Comment by danbao** [comment]
手动安装 wireguard-tools 成功的，那个是安装成功后再次执行的报错

**Comment by fscarmen** [comment]
你再更新一下脚本安装多次，还是不行。方便的话，把 ssh 发到 fscarmen@gmail.com 我看看

**Comment by danbao** [comment]
给了 ssh 也连不了，我是在内网的软路由pve里面安装的alpine 3.20，本来想弄个 ipv6 来着😂

**Comment by fscarmen** [comment]
如果 wireguard-tools 你安装成功，试试 `curl -sL "https://warp.cloudflare.now.cc/?run=register"` ，如果可以的话，再运行 
`curl -sL "https://warp.cloudflare.now.cc/?run=register" > /etc/wireguard/warp.conf`

**Comment by danbao** [comment]
@fscarmen 我知道原因了，我在路由器开了 openclash，然后已经有 ipv4 的 cloudflare 的 ip ，所以 menu.sh 以为我已经有 warp ipv4 了
