### ISSUE TITLE
国外原生双栈无法获取warp ip

### ISSUE THREAD

**Issue by bupt2017** [fscarmen/warp-sh#93]
### 错误提示 
菜单选项: 3.  为 原生双栈 添加 WARP 双栈网络接口 (bash menu.sh d) 

 Warning: `/etc/wireguard/warp.conf' is world accessible
[#] ip link add warp type wireguard
[#] wg setconf warp /dev/fd/63
Line unrecognized: `PrivateKey='
Configuration parsing error
[#] ip link delete dev warp
 ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑ 
 失败已超过5次，脚本中止，附上以上错误提示，问题反馈:[https://github.com/fscarmen/warp-sh/issues] 

### 尝试
1、获取单独的warp ipv4失败
2、获取单独的warp ipv6失败
3、添加cloudflare dns64之后再次尝试还是失败

**Comment by sopr6b67** [comment]
遇到了同样的问题
![image](https://github.com/user-attachments/assets/75d85ea3-3754-430c-932d-246f1f2a6c81)

**Comment by bupt2017** [comment]
> 遇到了同样的问题 ![image](https://private-user-images.githubusercontent.com/176758495/352792019-75d85ea3-3754-430c-932d-246f1f2a6c81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNDcwMjgsIm5iZiI6MTcyMjE0NjcyOCwicGF0aCI6Ii8xNzY3NTg0OTUvMzUyNzkyMDE5LTc1ZDg1ZWEzLTM3NTQtNDMwYy05MzJkLTI0NmYxZjJhNmM4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQwNjA1MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjdkNGU3ZWFiNDU1Y2NjZjkyOGI5YzJiNTU5MDIxOTQxMWM3NGUwZDhhZDM3ODBjYWIwYzI0YzU3YTQxZTVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MmeLpcy54PQFL-qxUwkMQ5zK8gKMVcTqcf2jWKajO44)

我有个机器是纯ipv6的原来可以通过warp获取到warp ipv4。但是DD之后就无法获取了。然后就用双栈小鸡试一下，结果还是不行

**Comment by bupt2017** [comment]
> 遇到了同样的问题 ![image](https://private-user-images.githubusercontent.com/176758495/352792019-75d85ea3-3754-430c-932d-246f1f2a6c81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNDcwMjgsIm5iZiI6MTcyMjE0NjcyOCwicGF0aCI6Ii8xNzY3NTg0OTUvMzUyNzkyMDE5LTc1ZDg1ZWEzLTM3NTQtNDMwYy05MzJkLTI0NmYxZjJhNmM4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQwNjA1MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjdkNGU3ZWFiNDU1Y2NjZjkyOGI5YzJiNTU5MDIxOTQxMWM3NGUwZDhhZDM3ODBjYWIwYzI0YzU3YTQxZTVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MmeLpcy54PQFL-qxUwkMQ5zK8gKMVcTqcf2jWKajO44)

我有个机器是纯ipv6的原来可以通过warp获取到warp ipv4。但是DD之后就无法获取了。然后就用双栈小鸡试一下，结果还是不行

**Comment by city10666** [comment]
一样，我有个纯IPV6小鸡突然就崩了，断网，我还以为被墙，重置后，装warp才发现无法获取IP了，就单单获取IPV4都不行，双栈单栈都获取失败

**Comment by bupt2017** [comment]
又分别尝试了。纯ipv4获取ipv6、纯ipv6获取ipv4、原生双栈获取ipv6都好了。
好奇怪！忽然又自己好了

**Comment by city10666** [comment]
> 又分别尝试了。纯ipv4获取ipv6、纯ipv6获取ipv4、原生双栈获取ipv6都好了。 好奇怪！忽然又自己好了

嗯，刚刚恢复，不排除是CF的问题，之前少数地区正常，

**Comment by fscarmen** [comment]
我自建的 cf api 不知道为什么领了 1101 了，不知道明天能不能恢复正常，已更换了域名处理

<img width="1187" alt="image" src="https://github.com/user-attachments/assets/357440fb-1279-40ec-81a5-a438a354203e">

**Comment by GreatMichaelLee** [comment]
一摸一样的问题，还没修好吗

**Comment by fscarmen** [comment]
已经改了，如果是生成 plus 的 `https://warp.forvps.eu.org/?run=pluskey&num=1`
现在估计是同一时间申请证书数量过多了，通过 cf 在 Let's Encrypt 申请的。

**Comment by GreatMichaelLee** [comment]
这是什么错误啊
![image](https://github.com/user-attachments/assets/ac50e663-8637-4125-bc65-3a2eb29a922f)

**Comment by fscarmen** [comment]
我刚才给另一位网友安装的可以哦。
![image](https://github.com/user-attachments/assets/ee15b436-7fcc-441b-ad6e-eb447f6fbdce)

**Comment by GreatMichaelLee** [comment]
> > 这是什么错误啊 ![image](https://private-user-images.githubusercontent.com/20067401/353134207-ac50e663-8637-4125-bc65-3a2eb29a922f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNjcyODUsIm5iZiI6MTcyMjI2Njk4NSwicGF0aCI6Ii8yMDA2NzQwMS8zNTMxMzQyMDctYWM1MGU2NjMtODYzNy00MTI1LWJjNjUtM2EyZWIyOWE5MjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE1Mjk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MTQ1MGE5MDFmM2MzMzJmYmFmZDk3YjMxMmViNDU1YWQ5YzRjMzVhMTc5ODg1NDdmYmE1MGU4MGZiNDA0NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c-4tjsVgrH3s_FOCn8ksA7OOg8jXYv8xEZ6nq4BNiNM)
> 
> 之前是报PrivateKey不认识，删掉这个warp.conf里空的PrivateKey之后就报上面这个错误。感觉连生成的配置文件都不对啊

大佬能不能修一下，不能用有点烦

**Comment by fscarmen** [comment]
> > > 这是什么错误啊 ![image](https://private-user-images.githubusercontent.com/20067401/353134207-ac50e663-8637-4125-bc65-3a2eb29a922f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNjcyODUsIm5iZiI6MTcyMjI2Njk4NSwicGF0aCI6Ii8yMDA2NzQwMS8zNTMxMzQyMDctYWM1MGU2NjMtODYzNy00MTI1LWJjNjUtM2EyZWIyOWE5MjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE1Mjk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MTQ1MGE5MDFmM2MzMzJmYmFmZDk3YjMxMmViNDU1YWQ5YzRjMzVhMTc5ODg1NDdmYmE1MGU4MGZiNDA0NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c-4tjsVgrH3s_FOCn8ksA7OOg8jXYv8xEZ6nq4BNiNM)
> > 
> > 
> > 之前是报PrivateKey不认识，删掉这个warp.conf里空的PrivateKey之后就报上面这个错误。感觉连生成的配置文件都不对啊
> 
> 大佬能不能修一下，不能用有点烦

已经修了啦，你卸载重新下载安装，再不行发个ssh 过来邮箱看看fscarmen@gmail.com

**Comment by GreatMichaelLee** [comment]
> > > > 这是什么错误啊 ![image](https://private-user-images.githubusercontent.com/20067401/353134207-ac50e663-8637-4125-bc65-3a2eb29a922f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNjcyODUsIm5iZiI6MTcyMjI2Njk4NSwicGF0aCI6Ii8yMDA2NzQwMS8zNTMxMzQyMDctYWM1MGU2NjMtODYzNy00MTI1LWJjNjUtM2EyZWIyOWE5MjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE1Mjk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MTQ1MGE5MDFmM2MzMzJmYmFmZDk3YjMxMmViNDU1YWQ5YzRjMzVhMTc5ODg1NDdmYmE1MGU4MGZiNDA0NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c-4tjsVgrH3s_FOCn8ksA7OOg8jXYv8xEZ6nq4BNiNM)
> > > 
> > > 
> > > 之前是报PrivateKey不认识，删掉这个warp.conf里空的PrivateKey之后就报上面这个错误。感觉连生成的配置文件都不对啊
> > 
> > 
> > 大佬能不能修一下，不能用有点烦
> 
> 已经修了啦，你卸载重新下载安装，再不行发个ssh 过来邮箱看看[fscarmen@gmail.com](mailto:fscarmen@gmail.com)

还是一样



No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.

 进度 3/3: 寻找 MTU 最优值和优选 endpoint 地址已完成

 创建快捷 warp 指令成功
 运行 WARP
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试
 第2次尝试
 第3次尝试
 第4次尝试
 第5次尝试
 ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
 当前操作系统: Ubuntu 24.04 LTS

 内核:6.9.12-x64v2-xanmod1

 菜单选项: 2.  为 IPv4 only 添加 WARP IPv6 网络接口 (bash menu.sh 6)

 Warning: `/etc/wireguard/warp.conf' is world accessible
[#] ip link add warp type wireguard
[#] wg setconf warp /dev/fd/63
Line unrecognized: `PrivateKey='
Configuration parsing error
[#] ip link delete dev warp
 ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
 失败已超过5次，脚本中止，附上以上错误提示，问题反馈:[https://github.com/fscarmen/warp-sh/issues]

**Comment by fscarmen** [comment]
> > > > > 这是什么错误啊 ![image](https://private-user-images.githubusercontent.com/20067401/353134207-ac50e663-8637-4125-bc65-3a2eb29a922f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNjcyODUsIm5iZiI6MTcyMjI2Njk4NSwicGF0aCI6Ii8yMDA2NzQwMS8zNTMxMzQyMDctYWM1MGU2NjMtODYzNy00MTI1LWJjNjUtM2EyZWIyOWE5MjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE1Mjk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MTQ1MGE5MDFmM2MzMzJmYmFmZDk3YjMxMmViNDU1YWQ5YzRjMzVhMTc5ODg1NDdmYmE1MGU4MGZiNDA0NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c-4tjsVgrH3s_FOCn8ksA7OOg8jXYv8xEZ6nq4BNiNM)
> > > > 
> > > > 
> > > > 之前是报PrivateKey不认识，删掉这个warp.conf里空的PrivateKey之后就报上面这个错误。感觉连生成的配置文件都不对啊
> > > 
> > > 
> > > 大佬能不能修一下，不能用有点烦
> > 
> > 
> > 已经修了啦，你卸载重新下载安装，再不行发个ssh 过来邮箱看看[fscarmen@gmail.com](mailto:fscarmen@gmail.com)
> 
> 还是一样
> 
> No services need to be restarted.
> 
> No containers need to be restarted.
> 
> No user sessions are running outdated binaries.
> 
> No VM guests are running outdated hypervisor (qemu) binaries on this host.
> 
> 进度 3/3: 寻找 MTU 最优值和优选 endpoint 地址已完成
> 
> 创建快捷 warp 指令成功 运行 WARP 后台获取 WARP IP 中,最大尝试5次…… 第1次尝试 第2次尝试 第3次尝试 第4次尝试 第5次尝试 ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ 当前操作系统: Ubuntu 24.04 LTS
> 
> 内核:6.9.12-x64v2-xanmod1
> 
> 菜单选项: 2. 为 IPv4 only 添加 WARP IPv6 网络接口 (bash menu.sh 6)
> 
> Warning: `/etc/wireguard/warp.conf' is world accessible [#] ip link add warp type wireguard [#] wg setconf warp /dev/fd/63 Line unrecognized: `PrivateKey=' Configuration parsing error [#] ip link delete dev warp ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑ 失败已超过5次，脚本中止，附上以上错误提示，问题反馈:[https://github.com/fscarmen/warp-sh/issues]

复现不了，我又安装了两台都是成功的
<img width="676" alt="image" src="https://github.com/user-attachments/assets/f828b730-cb8b-473c-aa7f-4b9f48062c84">

**Comment by GreatMichaelLee** [comment]
> > > > > > 这是什么错误啊 ![image](https://private-user-images.githubusercontent.com/20067401/353134207-ac50e663-8637-4125-bc65-3a2eb29a922f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNjcyODUsIm5iZiI6MTcyMjI2Njk4NSwicGF0aCI6Ii8yMDA2NzQwMS8zNTMxMzQyMDctYWM1MGU2NjMtODYzNy00MTI1LWJjNjUtM2EyZWIyOWE5MjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE1Mjk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MTQ1MGE5MDFmM2MzMzJmYmFmZDk3YjMxMmViNDU1YWQ5YzRjMzVhMTc5ODg1NDdmYmE1MGU4MGZiNDA0NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c-4tjsVgrH3s_FOCn8ksA7OOg8jXYv8xEZ6nq4BNiNM)
> > > > > 
> > > > > 
> > > > > 之前是报PrivateKey不认识，删掉这个warp.conf里空的PrivateKey之后就报上面这个错误。感觉连生成的配置文件都不对啊
> > > > 
> > > > 
> > > > 大佬能不能修一下，不能用有点烦
> > > 
> > > 
> > > 已经修了啦，你卸载重新下载安装，再不行发个ssh 过来邮箱看看[fscarmen@gmail.com](mailto:fscarmen@gmail.com)
> > 
> > 
> > 还是一样
> > No services need to be restarted.
> > No containers need to be restarted.
> > No user sessions are running outdated binaries.
> > No VM guests are running outdated hypervisor (qemu) binaries on this host.
> > 进度 3/3: 寻找 MTU 最优值和优选 endpoint 地址已完成
> > 创建快捷 warp 指令成功 运行 WARP 后台获取 WARP IP 中,最大尝试5次…… 第1次尝试 第2次尝试 第3次尝试 第4次尝试 第5次尝试 ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ 当前操作系统: Ubuntu 24.04 LTS
> > 内核:6.9.12-x64v2-xanmod1
> > 菜单选项: 2. 为 IPv4 only 添加 WARP IPv6 网络接口 (bash menu.sh 6)
> > Warning: `/etc/wireguard/warp.conf' is world accessible [#] ip link add warp type wireguard [#] wg setconf warp /dev/fd/63 Line unrecognized: `PrivateKey=' Configuration parsing error [#] ip link delete dev warp ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑ 失败已超过5次，脚本中止，附上以上错误提示，问题反馈:[https://github.com/fscarmen/warp-sh/issues]
> 
> 复现不了，我又安装了两台都是成功的 <img alt="image" width="676" src="https://private-user-images.githubusercontent.com/92626977/353491820-f828b730-cb8b-473c-aa7f-4b9f48062c84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNTEwMDksIm5iZiI6MTcyMjM1MDcwOSwicGF0aCI6Ii85MjYyNjk3Ny8zNTM0OTE4MjAtZjgyOGI3MzAtY2I4Yi00NzNjLWFhN2YtNGI5ZjQ4MDYyYzg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDE0NDUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMjFhYzRlYjdhNDExZTk3YTcxMTE3MzVhYzliNmI1ZmNjNTFjNTE2ZDQwODg0ZjM4NWUxNDY2ZGVmNzYyYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zuo1rGis6mntwcQMWSMcLkx79CKMiSIsdlzYefTX8UA">

目前版本是多少？3.1.1？另外我看你的OS版本是debian11?我的是Ubuntu 24.04的，看能否找个24.04的机子试试？另外我没法给ssh你测试啊，因为这个是ssh 密钥登陆的。

**Comment by fscarmen** [comment]
Ubuntu 24.04 ，仍然无法复现你的故障。

<img width="670" alt="image" src="https://github.com/user-attachments/assets/60629146-fd3b-4bd4-80c7-aa4028e6cda5">

**Comment by fscarmen** [comment]
你运行一个这个看看
```
awk '/PrivateKey/{print $NF}' /etc/wireguard/warp.conf
```

**Comment by GreatMichaelLee** [comment]
> 你运行一个这个看看
> 
> ```
> awk '/PrivateKey/{print $NF}' /etc/wireguard/warp.conf
> ```

![image](https://github.com/user-attachments/assets/cda1c1ff-7942-40c9-9d3a-92c45db8b48e)

**Comment by fscarmen** [comment]
```
cat /etc/wireguard/warp.conf
```

**Comment by GreatMichaelLee** [comment]
> ```
> cat /etc/wireguard/warp.conf
> ```

都说了这个文件有问题，一个是PrivateKey缺失，第二个Address=/128有误，我也不知道原因是什么，重装了，还是一样。
[Interface]
PrivateKey =
Address = 172.16.0.2/32
Address = /128
DNS = 1.1.1.1,8.8.8.8,8.8.4.4,2606:4700:4700::1111,2001:4860:4860::8888,2001:4860:4860::8844
MTU = 1420
PostUp = ip -4 rule add from /*马赛克*/ lookup main
PostDown = ip -4 rule delete from /*马赛克*/ lookup main

#Reserved =
#Table = off
#PostUp = /etc/wireguard/NonGlobalUp.sh
#PostDown = /etc/wireguard/NonGlobalDown.sh

[Peer]
PublicKey = /*马赛克*/
#AllowedIPs = 0.0.0.0/0
AllowedIPs = ::/0
Endpoint = 162.159.195.200:1070
PersistentKeepalive = 30

**Comment by fscarmen** [comment]
奇怪，没有了，privateKey
```
cat /etc/wireguard/warp-account.conf 
```

**Comment by GreatMichaelLee** [comment]
> cat /etc/wireguard/warp-account.conf

咋搞？

**Comment by fscarmen** [comment]
看看那文件

**Comment by GreatMichaelLee** [comment]
> cat /etc/wireguard/warp-account.conf

<!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>
<title>Worker threw exception | warp.cloudflare.now.cc | Cloudflare</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />

<style>body{margin:0;padding:0}</style>



<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>



</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1>
          <span class="cf-error-type" data-translate="error">Error</span>
          <span class="cf-error-code">1101</span>
          <small class="heading-ray-id">Ray ID: 8ab672d09b712362 &bull; 2024-07-30 15:40:40 UTC</small>
        </h1>
        <h2 class="cf-subheadline" data-translate="error_desc">Worker threw exception</h2>
      </div>

      <section></section>

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="what_happened">What happened?</h2>
            <p>You've requested a page on a website (warp.cloudflare.now.cc) that is on the <a href="https://www.cloudflare.com/5xx-error-landing/" target="_blank">Cloudflare</a> network. An unknown error occurred while rendering the page.</p>
          </div>


          <div class="cf-column">
            <h2 data-translate="what_can_i_do">What can I do?</h2>
            <p><strong>If you are the owner of this website:</strong><br />you should <a href="https://www.cloudflare.com/login?utm_source=error_100x" target="_blank">login to Cloudflare</a> and check the error logs for warp.cloudflare.now.cc.</p>
          </div>

        </div>
      </div>

      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">8ab672d09b712362</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
      <span class="hidden" id="cf-footer-ip">/*马赛克*/</span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>

  </p>
  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div>


    </div>
  </div>

  <script>
  window._cf_translation = {};


</script>

</body>
</html>

**Comment by fscarmen** [comment]
你用 warp u 卸载，再安装就行了，这个文件出问题了

**Comment by GreatMichaelLee** [comment]
> 你用 `warp u` 卸载，再安装就行了，这个文件出问题了

搞定了，可以关了

**Comment by fscarmen** [comment]
> 已经修了啦，你卸载重新下载安装，再不行发个ssh 过来邮箱看看[fscarmen@gmail.com](mailto:fscarmen@gmail.com)

https://github.com/fscarmen/warp-sh/issues/93#issuecomment-2258163788

一早都让你卸载重新安装啦

**Comment by GreatMichaelLee** [comment]
> > 已经修了啦，你卸载重新下载安装，再不行发个ssh 过来邮箱看看[fscarmen@gmail.com](mailto:fscarmen@gmail.com)
> 
> [#93 (comment)](https://github.com/fscarmen/warp-sh/issues/93#issuecomment-2258163788)
> 
> 一早都让你卸载重新安装啦

之前协助过一次，不成功，第一次用的菜单里面选项7卸载的，没起作用，重装问题依旧，后来第二次按你说的用的warp u卸载掉的，重装好了, 这两个调的不是同一套动作？如果不是，建议加个选项，卸载脚本及所有组件。

**Comment by city10666** [comment]
> > > 已经修了啦，你卸载重新下载安装，再不行发个ssh 过来邮箱看看[fscarmen@gmail.com](mailto:fscarmen@gmail.com)
> > 
> > 
> > [#93 (comment)](https://github.com/fscarmen/warp-sh/issues/93#issuecomment-2258163788)
> > 一早都让你卸载重新安装啦
> 
> 之前卸载过一次，不成功，用的是菜单里面选项7卸载的，没起作用，重装问题依旧，后来第二次按你说的用的warp u卸载掉的，重装好了, 这两个调的不是同一套动作？如果不是，建议加个选项，卸载脚本及所有组件。

脚本删掉，重来，删不干净就重置系统

**Comment by fscarmen** [comment]
> > > 已经修了啦，你卸载重新下载安装，再不行发个ssh 过来邮箱看看[fscarmen@gmail.com](mailto:fscarmen@gmail.com)
> > 
> > 
> > [#93 (comment)](https://github.com/fscarmen/warp-sh/issues/93#issuecomment-2258163788)
> > 一早都让你卸载重新安装啦
> 
> 之前卸载过一次，不成功，用的是菜单里面选项7卸载的，没起作用，重装问题依旧，后来第二次按你说的用的warp u卸载掉的，重装好了, 这两个调的不是同一套动作？如果不是，建议加个选项，卸载脚本及所有组件。

完全一样的。

**Comment by bestZwei** [comment]
还是出现这个问题
