### ISSUE TITLE
WARP 的所有的 endpoint 均不能连通，有可能 UDP 被限制了，可联系供应商了解如何开启

### ISSUE THREAD

**Issue by IGNiT3-R** [fscarmen/warp-sh#94]
机器为国内ipv6 only服务器，系统Ubuntu22.04
bash menu.sh运行脚本后，报错：WARP 的所有的 endpoint 均不能连通，有可能 UDP 被限制了，可联系供应商了解如何开启，问题反馈:[https://github.com/fscarmen/warp-sh/issues] 

但是同一台机器，最开始我装的系统是Centos7，安装完美开启，后来是因为获取不到ip，我才换了Ubuntu。

我查看了其他Issues，尝试执行了
```wget --no-check-certificate -O /dev/null https://gitlab.com/fscarmen/warp/-/raw/main/wireguard-go/wireguard-go-linux-amd64-20230223```
成功之后重新获取还是失败。
因为我是ipv6 only机器，所以尝试执行
wget -O /tmp/endpoint https://gitlab.com/fscarmen/warp/-/raw/main/endpoint/warp-linux-amd64 && chmod +x /tmp/endpoint

wget -O /tmp/ip https://gitlab.com/fscarmen/warp/-/raw/main/endpoint/ipv6

/tmp/endpoint -file /tmp/ip -output /tmp/endpoint_result

head -10 /tmp/endpoint_result

得到如下结果
2024/07/29 08:48:39 [2606:4700:d0::a29f:c1fb]:5956 数据包丢失
2024/07/29 08:48:39 [2606:4700:d0::a29f:c1fb]:1018 数据包丢失
2024/07/29 08:48:39 [2606:4700:d0::a29f:c1fc]:5956 数据包丢失
2024/07/29 08:48:39 [2606:4700:d0::a29f:c1fc]:1018 数据包丢失
2024/07/29 08:48:39 [2606:4700:d0::a29f:c1fd]:5956 数据包丢失
2024/07/29 08:48:39 [2606:4700:d0::a29f:c1fe]:5956 数据包丢失
2024/07/29 08:48:39 [2606:4700:d0::a29f:c1fe]:1018 数据包丢失
2024/07/29 08:48:39 [2606:4700:d0::a29f:c1fd]:1018 数据包丢失
2024/07/29 08:48:39 [2606:4700:d0::a29f:c1ff]:5956 数据包丢失
2024/07/29 08:48:40 [2606:4700:d0::a29f:c1ff]:1018 数据包丢失
测试结果已经写入/tmp/endpoint_result
root@ipv60oi3h4:~# head -10 /tmp/endpoint_result
IP:PORT, LOSS, DELAY
[2606:4700:100::a29f:c120]:5956,100.00%,1000 ms
[2606:4700:100::a29f:c1ce]:5956,100.00%,1000 ms
[2606:4700:100::a29f:c11a]:908,100.00%,1000 ms
[2606:4700:100::a29f:c156]:5956,100.00%,1000 ms
[2606:4700:100::a29f:c1a5]:908,100.00%,1000 ms
[2606:4700:100::a29f:c135]:908,100.00%,1000 ms
[2606:4700:100::a29f:c170]:908,100.00%,1000 ms
[2606:4700:100::a29f:c1c0]:5956,100.00%,1000 ms
[2606:4700:100::a29f:c11c]:908,100.00%,1000 ms

但执行echo -ne '\x00\x01\x00\x00\x21\x12\xA4\x42\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' | nc -u -w1 stun.cloudflare.com 3478 | xxd -p有回显
010100182112a442000000000000000000000000002000140002afd1051a
2358b00000025edd56fffe000126
执行curl -6 --retry 2 -ksm5 https://www.cloudflare.com/cdn-cgi/trace有回显
修改了DNS，添加了
nameserver 2606:4700:4700::64
nameserver 2606:4700:4700::6400

目前还是失败的状态，策略开放了所有UDP端口的出入站规则

但是我很奇怪的一点是，我之前Centos7，安装完美开启，现在换了Ubuntu，安装都装不上了，麻烦大佬解惑

**Comment by fscarmen** [comment]
> 机器为国内ipv6 only服务器，

估计运营商或者厂家限制了所有的 warp endpoint，你提到之前在 centos 7 可以，我觉得可能是时间差的问题，之前还没有补限制，现在即使你换回 c7，也一样不行的。你单独运行那个测endpoint 的，是连接 Endpoint ip-cidr 的，不要经过域名解释的。

> 执行curl -6 --retry 2 -ksm5 [https://www.cloudflare.com/cdn-cgi/trace有回显](https://www.cloudflare.com/cdn-cgi/trace%E6%9C%89%E5%9B%9E%E6%98%BE)
修改了DNS，添加了
nameserver 2606:4700:4700::64
nameserver 2606:4700:4700::6400

这个是因为你访问的是域名，而域名通过 dns64 的处理，所以可以。


> 但执行echo -ne '\x00\x01\x00\x00\x21\x12\xA4\x42\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' | nc -u -w1 stun.cloudflare.com 3478 | xxd -p有回显

说明厂家的udp是通的，这时你可以用 hysteria2 、tuic5等基于 udp 的协议，但依然是那个问题，warp 的 所有 endpoint 被限制了。

**Comment by IGNiT3-R** [comment]
> > 机器为国内ipv6 only服务器，
> 
> 估计运营商或者厂家限制了所有的 warp endpoint，你提到之前在 centos 7 可以，我觉得可能是时间差的问题，之前还没有补限制，现在即使你换回 c7，也一样不行的。你单独运行那个测endpoint 的，是连接 Endpoint ip-cidr 的，不要经过域名解释的。
> 
> > 执行curl -6 --retry 2 -ksm5 [https://www.cloudflare.com/cdn-cgi/trace有回显](https://www.cloudflare.com/cdn-cgi/trace%E6%9C%89%E5%9B%9E%E6%98%BE)
> > 修改了DNS，添加了
> > nameserver 2606:4700:4700::64
> > nameserver 2606:4700:4700::6400
> 
> 这个是因为你访问的是域名，而域名通过 dns64 的处理，所以可以。
> 
> > 但执行echo -ne '\x00\x01\x00\x00\x21\x12\xA4\x42\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' | nc -u -w1 stun.cloudflare.com 3478 | xxd -p有回显
> 
> 说明厂家的udp是通的，这时你可以用 hysteria2 、tuic5等基于 udp 的协议，但依然是那个问题，warp 的 所有 endpoint 被限制了。

问了厂家说是没有限制warp endpoint

**Comment by fscarmen** [comment]
> 问了厂家说是没有限制warp endpoint

那可能是他的网络商封了，因为是大陆的。

**Comment by IGNiT3-R** [comment]
> warp endpoint

有可能，谢谢大佬

**Comment by Kratos28** [comment]
遇到相同 有办法解决吗?

**Comment by IGNiT3-R** [comment]
> 遇到相同 有办法解决吗?

没有办法，我现在整了个双栈服务器，顺便给v6服务器挖了个洞

**Comment by fscarmen** [comment]
> 遇到相同 有办法解决吗?

试试单独运行，如果掉包率都是100%，那是没有办法了

```
wget -O /tmp/endpoint https://gitlab.com/fscarmen/warp/-/raw/main/endpoint/warp-linux-amd64 && chmod +x /tmp/endpoint

wget -O /tmp/ip https://gitlab.com/fscarmen/warp/-/raw/main/endpoint/ipv6

/tmp/endpoint -file /tmp/ip -output /tmp/endpoint_result

head -10 /tmp/endpoint_result
```

**Comment by zhanhangY** [comment]
> > 遇到相同有解决办法吗？
> 
> 尝试单独运行，如果掉包率都是100%，那是没有办法了
> 
> ```
> wget -O /tmp/endpoint https://gitlab.com/fscarmen/warp/-/raw/main/endpoint/warp-linux-amd64 && chmod +x /tmp/endpoint
> 
> wget -O /tmp/ip https://gitlab.com/fscarmen/warp/-/raw/main/endpoint/ipv6
> 
> /tmp/endpoint -file /tmp/ip -output /tmp/endpoint_result
> 
> head -10 /tmp/endpoint_result
> ```

我的并不是100%丢包但仍然出现了这样的问题

**Comment by fscarmen** [comment]
> > > 遇到相同有解决办法吗？
> > 
> > 
> > 尝试单独运行，如果掉包率都是100%，那是没有办法了
> > ```
> > wget -O /tmp/endpoint https://gitlab.com/fscarmen/warp/-/raw/main/endpoint/warp-linux-amd64 && chmod +x /tmp/endpoint
> > 
> > wget -O /tmp/ip https://gitlab.com/fscarmen/warp/-/raw/main/endpoint/ipv6
> > 
> > /tmp/endpoint -file /tmp/ip -output /tmp/endpoint_result
> > 
> > head -10 /tmp/endpoint_result
> > ```
> 
> 我的并不是100%丢包但仍然出现了这样的问题 使用US 仅ipv6机器almalinux8 [2606:4700:d0::a29f:c0a8]:890,0.00%,92 ms [2606:4700:d0::a29f:c0cf]:1387,0.00%,92 ms [2606:4700:d0::a29f:c0d0]:1387,0.00%,92 ms [2606:4700:d0::a29f:c1ae]:894,0.00%,93 ms [2606:4700:d0::a29f:c19c]:891,0.00%,93 ms [2606:4700:d0::a29f:c155]:943,0.00%,94 ms [2606:4700:d0::a29f:c1ad]:894,0.00%,94 ms [2606:4700:d0::a29f:c0a6]:890,0.00%,94 ms [2606:4700:d0::a29f:c145]:891,0.00%,94 ms [2606:4700:d0::a29f:c0a7]:890,0.00%,95 ms [2606:4700:d0::a29f:c0ae]:890,0.00%,95 ms [2606:4700:d0::a29f:c0d1]:890,0.00%,95 ms [2606:4700:d0::a29f:c0e2]:1387,0.00%,95 ms [2606:4700:d0::a29f:c0fa]:890,0.00%,95 ms [2606:4700:d0::a29f:c1a3]:891,0.00%,96 ms [2606:4700:d0::a29f:c19f]:891,0.00%,96 ms [2606:4700:d0::a29f:c1a3]:943,0.00%,96 ms [2606:4700:d0::a29f:c109]:890,0.00%,97 ms [2606:4700:d0::a29f:c1a1]:891,0.00%,97 ms [2606:4700:d0::a29f:c0d0]:890,0.00%,97 ms [2606:4700:d0::a29f:c0a4]:1387,0.00%,97 ms [2606:4700:d0::a29f:c1ab]:894,0.00%,97 ms [2606:4700:d0::a29f:c1aa]:934,0.00%,97 ms [2606:4700:d0::a29f:c0b0]:1387,0.00%,97 ms [2606:4700:d0::a29f:c0f1]:1387,0.00%,97 ms [2606:4700:d0::a29f:c0a4]:890,0.00%,97 ms [2606:4700:d0::a29f:c109]:1387,0.00%,97 ms [2606:4700:d0::a29f:c0a3]:890,0.00%,97 ms [2606:4700:d0::a29f:c0b4]:1387,0.00%,97 ms [2606:4700:d0::a29f:c1aa]:894,0.00%,97 ms [2606:4700:d0::a29f:c1a0]:943,0.00%,98 ms [2606:4700:d0::a29f:c0cf]:890,0.00%,98 ms [2606:4700:d0::a29f:c0ac]:1387,0.00%,98 ms [2606:4700:d0::a29f:c0ac]:890,0.00%,98 ms [2606:4700:d0::a29f:c0c7]:1387,0.00%,98 ms [2606:4700:d0::a29f:c0ab]:1387,0.00%,98 ms 这是部分的截取

你的也是提示 所有的 endpoint 均不能连通 吗？

**Comment by zhanhangY** [comment]
> > > > 遇到相同有解决办法吗？
> > > 
> > > 
> > > 尝试单独运行，如果掉包率都是100%，那是没有办法了
> > > ```
> > > wget -O /tmp/endpoint https://gitlab.com/fscarmen/warp/-/raw/main/endpoint/warp-linux-amd64 && chmod +x /tmp/endpoint
> > > 
> > > wget -O /tmp/ip https://gitlab.com/fscarmen/warp/-/raw/main/endpoint/ipv6
> > > 
> > > /tmp/endpoint -file /tmp/ip -output /tmp/endpoint_result
> > > 
> > > head -10 /tmp/endpoint_result
> > > ```
> > 
> > 
> > 我的并不是100%丢包但仍然出现了这样的问题 使用US 仅ipv6机器almalinux8 [2606:4700:d0::a29f:c0a8]:890,0.00%,92 ms [2606:4700:d0::a29f:c0cf]:1387,0.00%,92 ms [2606:4700:d0::a29f:c0d0]:1387,0.00%,92 ms [2606:4700:d0::a29f:c1ae]:894,0.00%,93 ms [2606:4700:d0::a29f:c19c]:891,0.00%,93 ms [2606:4700:d0::a29f:c155]:943,0.00%,94 ms [2606:4700:d0::a29f:c1ad]:894,0.00%,94 ms [2606:4700:d0::a29f:c0a6]:890,0.00%,94 ms [2606:4700:d0::a29f:c145]:891,0.00%,94 ms [2606:4700:d0::a29f:c0a7]:890,0.00%,95 ms [2606:4700:d0::a29f:c0ae]:890,0.00%,95 ms [2606:4700:d0::a29f:c0d1]:890,0.00%,95 ms [2606:4700:d0::a29f:c0e2]:1387,0.00%,95 ms [2606:4700:d0::a29f:c0fa]:890,0.00%,95 ms [2606:4700:d0::a29f:c1a3]:891,0.00%,96 ms [2606:4700:d0::a29f:c19f]:891,0.00%,96 ms [2606:4700:d0::a29f:c1a3]:943,0.00%,96 ms [2606:4700:d0::a29f:c109]:890,0.00%,97 ms [2606:4700:d0::a29f:c1a1]:891,0.00%,97 ms [2606:4700:d0::a29f:c0d0]:890,0.00%,97 ms [2606:4700:d0::a29f:c0a4]:1387,0.00%,97 ms [2606:4700:d0::a29f:c1ab]:894,0.00%,97 ms [2606:4700:d0::a29f:c1aa]:934,0.00%,97 ms [2606:4700:d0::a29f:c0b0]:1387,0.00%,97 ms [2606:4700:d0::a29f:c0f1]:1387,0.00%,97 ms [2606:4700:d0::a29f:c0a4]:890,0.00%,97 ms [2606:4700:d0::a29f:c109]:1387,0.00%,97 ms [2606:4700:d0::a29f:c0a3]:890,0.00%,97 ms [2606:4700:d0::a29f:c0b4]:1387,0.00%,97 ms [2606:4700:d0::a29f:c1aa]:894,0.00%,97 ms [2606:4700:d0::a29f:c1a0]:943,0.00%,98 ms [2606:4700:d0::a29f:c0cf]:890,0.00%,98 ms [2606:4700:d0::a29f:c0ac]:1387,0.00%,98 ms [2606:4700:d0::a29f:c0ac]:890,0.00%,98 ms [2606:4700:d0::a29f:c0c7]:1387,0.00%,98 ms [2606:4700:d0::a29f:c0ab]:1387,0.00%,98 ms 这是部分的截取
> 
> 你的也是提示 所有的 endpoint 均不能连通 吗？

是的

**Comment by fscarmen** [comment]
那搞不懂为什么报错了。
