### ISSUE TITLE
plus api+ 不能生成key了吗

### ISSUE THREAD

**Issue by GreatMichaelLee** [fscarmen/warp-sh#95]
直接回车报错，没有生成key，说要输入26位字符？
![image](https://github.com/user-attachments/assets/3e72ddd7-c886-4e7e-b21d-8a197b99e281)

**Comment by fscarmen** [comment]
应该是用于克隆的母license黑了，等下回去换下

**Comment by fscarmen** [comment]
可以了，有时候不行的话，只能用免费的=

**Comment by GreatMichaelLee** [comment]
> 可以了，有时候不行的话，只能用免费的

不行啊，感觉回车秒报错，根本都没等待，似乎是在校验我回车是个非法操作一样

**Comment by fscarmen** [comment]
已处理，再试试
<img width="887" alt="image" src="https://github.com/user-attachments/assets/7cefafcb-f948-402a-ab79-0ae321d7b2d8">

**Comment by fscarmen** [comment]
你拿这3个去用吧
{
  "accountType": "limited",
  "quota": 1923837100000000000,
  "licenseCode": "o4me87v2-83iI0Yu6-6m53J0cp"
}
{
  "accountType": "limited",
  "quota": 1923837100000000000,
  "licenseCode": "8zQB3c24-8wxqC610-65zaY0P4"
}
{
  "keys": [
    {
      "accountType": "limited",
      "quota": "1.92 EiB",
      "licenseCode": "3cM907bv-O812B7NT-kX1a52m9"
    }

**Comment by GreatMichaelLee** [comment]
> 8zQB3c24-8wxqC610-65zaY0P4

可以了，感觉这玩意儿太容易失效了

**Comment by fscarmen** [comment]
> > 8zQB3c24-8wxqC610-65zaY0P4
> 
> 可以了，感觉这玩意儿太容易失效了

是的，主要是母 license 要不停的维护更新。

现在为了大家更好的体验，做法是无论你是否使用 plus，后台都默认提前准备好一个key，这时如果用户不使用的话，那个license就是浪费的。

我初步估计使用的人可能只有1/10到 1/50，意味着1个使用本脚本创建 plus的话，其实已经建了10个到50个license了，以现在每天5万的用户推算，浪费了4.5万到4.9万个的，显然这样的处理办法不好，倒不是浪费注册的资源，而是浪费用于克隆的母key 的可用次数，大大增加我的维护量。

暂时先这样，后续可能考虑只有当用户选择了脚本生成 license ，才开始生成，预计时间是10秒到30秒不行。

**Comment by fscarmen** [comment]
现在使用脚本生成的 license 应该很快吧

**Comment by GreatMichaelLee** [comment]
> > > 8zQB3c24-8wxqC610-65zaY0P4
> > 
> > 
> > 可以了，感觉这玩意儿太容易失效了
> 
> 是的，主要是母 license 要不停的维护更新。
> 
> 现在为了大家更好的体验，做法是无论你是否使用 plus，后台都默认提前准备好一个key，如果用户使用，就不用等生成 license 的10-30秒，而如果用户不使用的话，那个license就是浪费的。
> 
> 我初步估计使用的人可能只有1/10到 1/50，意味着1个使用本脚本创建 plus的话，其实已经建了10个到50个license了，以现在每天5万的用户推算，浪费了4.5万到4.9万个的，显然这样的处理办法不好，倒不是浪费注册的资源，而是浪费用于克隆的母key 的可用次数，大大增加我的维护量。
> 
> 暂时先这样，后续可能考虑只有当用户选择了脚本生成 license ，才开始生成，预计时间是10秒到30秒不行。

又不行了

**Comment by fscarmen** [comment]
是，自从他通知说11月停之后，大家都在刷，导致官方停了克隆 license 的方法了。

**Comment by GreatMichaelLee** [comment]
> 是，自从他通知说11月停之后，大家都在刷，导致官方停了克隆 license 的方法了。

是不是意味着以后warp+没得玩了？

**Comment by fscarmen** [comment]
是啊，之前给你几个，你可以试试，留着用吧
