### ISSUE TITLE
什么时候支持openwrt和istoreos呀？

### ISSUE THREAD

**Issue by mftvbox** [fscarmen/warp-sh#98]
![16ab6f2b79ca0c7389f726f7b524ff2](https://github.com/user-attachments/assets/1d872739-7544-43eb-bfcc-e51aa2adfee4)

**Comment by fscarmen** [comment]
openwrt 已经适配过了，但没有经过大量不同的系统测试，你可以试试。
istoreos 我也不会用，估计用户不多，短期内不作适配了。
